### ISSUE TITLE
Cannot create unprivileged container on non-systemd system

### ISSUE THREAD

**Issue by bitshark** [lxc/lxcfs#106]
Hey guys -- not sure if this is an issue with my configuration, lxcfs, or something else, but this is the best I can figure so I'll start here.   

**Problem**:  Cannot create an unprivileged container on non-systemd system
**Error**: lxc_cgfsng - cgfsng.c:all_controllers_found:431 - no systemd controller mountpoint found
**Version**: lxcfs 2.0.0
**OS**: Void Linux (Linux computer 4.5.1_1 #1 SMP PREEMPT Wed Apr 13 02:54:58 UTC 2016 x86_64 GNU/Linux)
**Comments**: Creating containers as root seems to work just fine
**References**:  The only other relavent thread or discussion I can find is linked here... https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg4893624.html
```bash
[user@computer ~]$ lxc-create -t download -n ubuntu -- -d ubuntu -r trusty -a amd64
Using image from local cache
Unpacking the rootfs

---
You just created an Ubuntu container (release=trusty, arch=amd64, variant=default)

To enable sshd, run: apt-get install openssh-server

For security reason, container images ship without user accounts
and without a root password.

Use lxc-attach or chroot directly into the rootfs to set a root password
or create user accounts.

[user@computer ~]$ lxc-start -n ubuntu 
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 346 To get more details, run the container in foreground mode.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
[user@computer ~]$ 
[user@computer ~]$ lxc-start -n ubuntu -d -o /dev/stdout -l debug -F
      lxc-start 20160417172123.446 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /home/user/.local/share/lxc/ubuntu/config
      lxc-start 20160417172123.446 WARN     lxc_confile - confile.c:config_pivotdir:1877 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20160417172123.447 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 20160417172123.447 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
      lxc-start 20160417172123.447 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
      lxc-start 20160417172123.448 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
      lxc-start 20160417172123.448 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
      lxc-start 20160417172123.448 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
      lxc-start 20160417172123.448 DEBUG    lxc_console - console.c:lxc_console_peer_default:437 - opening /dev/tty for console peer
      lxc-start 20160417172123.448 DEBUG    lxc_console - console.c:lxc_console_peer_default:443 - using '/dev/tty' as console
      lxc-start 20160417172123.448 DEBUG    lxc_console - console.c:lxc_console_sigwinch_init:142 - 3378 got SIGWINCH fd 9
      lxc-start 20160417172123.448 DEBUG    lxc_console - console.c:lxc_console_winsz:72 - set winsz dstfd:6 cols:125 rows:34
      lxc-start 20160417172123.468 INFO     lxc_start - start.c:lxc_init:488 - 'ubuntu' is initialized
      lxc-start 20160417172123.468 DEBUG    lxc_start - start.c:__lxc_start:1302 - Not dropping cap_sys_boot or watching utmp
      lxc-start 20160417172123.468 INFO     lxc_start - start.c:resolve_clone_flags:999 - Cloning a new user namespace
      lxc-start 20160417172123.468 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for ubuntu
      lxc-start 20160417172123.469 ERROR    lxc_cgfsng - cgfsng.c:all_controllers_found:431 - no systemd controller mountpoint found
lxc-start: cgfsng.c: all_controllers_found: 431 no systemd controller mountpoint found
      lxc-start 20160417172123.469 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
lxc-start: start.c: lxc_spawn: 1079 failed initializing cgroup support
      lxc-start 20160417172123.469 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'ubuntu'
lxc-start: start.c: __lxc_start: 1329 failed to spawn 'ubuntu'
      lxc-start 20160417172123.469 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'ubuntu', config section 'lxc'
      lxc-start 20160417172123.972 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
lxc-start: lxc_start.c: main: 344 The container failed to start.
      lxc-start 20160417172123.972 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
[user@computer ~]$
```

Thanks... What's wierd is it works fine if I create the container as root.  Is this behavior expected?  Perhaps I have something misconfigured?  

```bash
[root@computer pam.d]# lxc-create -t download -n ubuntu2 -- -d ubuntu -r trusty -a amd64
Setting up the GPG keyring
Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs

---
You just created an Ubuntu container (release=trusty, arch=amd64, variant=default)

To enable sshd, run: apt-get install openssh-server

For security reason, container images ship without user accounts
and without a root password.

Use lxc-attach or chroot directly into the rootfs to set a root password
or create user accounts.
[root@computer pam.d]# lxc-start -n ubuntu2 -d
[root@computer pam.d]# 
```

Other users of our distro are having a similar problem... I've referenced the github issue here where you may find some additional detail.   Thanks for the help.
https://github.com/voidlinux/void-packages/issues/4018

**Comment by hallyn** [comment]
On Mon, Apr 18, 2016 at 12:30:39AM -0700, bitsharkz wrote:
> Hey guys -- not sure if this is an issue with my configuration, lxcfs, or something else, but this is the best I can figure so I'll start here.   
> 
> **Problem**:  Cannot create an unprivileged container on non-systemd system
> **Error**: lxc_cgfsng - cgfsng.c:all_controllers_found:431 - no systemd controller mountpoint found

Hi,

you need commit c30b61c37695a88f07ed5641ad270e4785a3a918:
    cgfsng: don't require that systemd subsystem be mounted

This is not in the 2.0 release, it came immediately after.

Alternatively, simply create a name=systemd mount:

mkdir -p /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd /sys/fs/cgroup/systemd

**Comment by bitshark** [comment]
Ah nice ... well so I actually did that mount of the directory but was still having issues even with that mount. . .  I eventually decided to revert back down to LTC 1.x and finally got that working.  I'll take a look at that commit and see if it resolves the problem for the 2.0 release.  Thanks!

**Comment by mdkuser** [comment]
> Alternatively, simply create a name=systemd mount:

> mkdir  -p /sys/fs/cgroup/systemd
> mount -t cgroup -o none,name=systemd /sys/fs/cgroup/systemd

where to put this to make it permanent after system reboot?
I have to put it in /etc/sv/lxc-autostart/run to make autostart working

stange thing is it without those line it loggs errors about missing systemd mount point and does not start the guests, however if manully doing a 

sv restart lxc-autostart 

it works and no errors logged.

So why I doesn't work at system reboot?
Putting above lines in th lxc-autostart run stcript is supposed to be a dirty hack...

**Comment by mdkuser** [comment]
commit c30b61c37695a88f07ed5641ad270e4785a3a918 is already published in official repos?
I applied all recent updates via xbps-install but still having lxc-autostart issue if not creating systemd mount point manually...

**Comment by hallyn** [comment]
On Tue, Apr 26, 2016 at 07:23:14AM -0700, mdkuser wrote:
> commit c30b61c37695a88f07ed5641ad270e4785a3a918 is already published in official repos?

It is in upstream git.  It's not in 2.0 so most distros probably do not yet
have it.  You'll likely need to build your own package, or ask your distro
to pull the patch into the package.

**Comment by mdkuser** [comment]
understood. thanks

**Comment by Songzhongrang** [comment]
Hi,
While I'm trying to start an unprivileged container, I meet the same problem also. And trying to following instruction above, and also I add the modify of commit c30b61c37695a88f07ed5641ad270e4785a3a918, but unfortunately, It doesn't work either.

**Before I add commit c30b61c37695a88f07ed5641ad270e4785a3a918, log as follows:**
lxc-start 20170105182841.368 ERROR    lxc_cgfsng - cgfsng.c:all_controllers_found:431 - **no systemd controller mountpoint found**
lxc-start 20170105182841.380 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
lxc-start 20170105182841.380 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'u4'
lxc-start 20170105182846.385 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
lxc-start 20170105182846.396 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
lxc-start 20170105182846.400 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

**After I add the commit, error as follows:**
lxc-start 20170105183141.716 ERROR    lxc_cgfsng - cgfsng.c:all_controllers_found:437 - **no freezer controller mountpoint found**
lxc-start 20170105183141.719 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
lxc-start 20170105183141.719 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'u4'
lxc-start 20170105183146.722 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
lxc-start 20170105183146.742 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
lxc-start 20170105183146.744 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

So, I'm trying to add some debug info on src/lxc/cgfsng.c, also I revert the modify of commit c30b61c37695a88f07ed5641ad270e4785a3a918, and I found that:
In src/lxc/cfgsng.c 
static bool parse_hierarchies(struct cgfsng_handler_data* d){
  ...
  if (!test_writeable(mountpoint, base_cgroup)) {
    ...
    // The debug info I add;
    ERROR("No access write '%s'", mountpoint);
    free(mountpoint);
    ...
  }
  ...
}
When I use non-root user to start unprivileged container, It'll print the ERROR msg, so In my opinion, I think this is the reason.

Does anyone know what should I do to fix it.

**Comment by brauner** [comment]
The freezer cgroup is a hard requirement we have in `LXC`'s `cgfsng`, so there is not similar fix available. However, the pam module that ships with `LXCFS` should take care of placing you in a writeable cgroup for the `freezer` controller on login. This is the default for `Ubuntu`/`Debian`. You might have to do it manually for other distributions.

**Comment by Songzhongrang** [comment]
I try to change the property of "/sys/fs/cgroup" and subdirectory file's property, use
sudo chmod 0777 $(find /sys/fs/cgroup/*);
Then I use lxc-start, there's no errno any more, but I still feel confused about this change, I'm not sure it safe or not, any ideas?

**Comment by Songzhongrang** [comment]
Another question, If I use unprivileged container, when I create a container, someone say only "download" template can used, But why?

**Comment by hallyn** [comment]
No, chmoding everything under /sys/fs/cgroup to 777 is not safe.
