### ISSUE TITLE
Can't  compile lxcfs without PAM libs  even the option 'with-pamdir=none'  is passed to configure

### ISSUE THREAD

**Issue by kllk2320** [lxc/lxcfs#110]
Hi, guys. I'm not sure whether pam_cgfs becomes a required part of lxcfs as it still tries to compile lxcfs even if the option "with-pamdir=none" is passed to configure.
I think the configuration option "with-pamdir=none" should disable building pam_cgfs according to the comment:
     --with-pamdir=PATH      Specify the directory where PAM modules are stored,
                                            or "none" if PAM modules are not to be built
otherwise what's the point of this option?
  
The version I tried to compile is lxc-2.0.0  but I couldn't compile it because there's no PAM module in our system.

**Comment by hallyn** [comment]
Yup, this is a bug.  If you have the time, patch to fix it would be greatly
appreciated.

**Comment by kllk2320** [comment]
OK, let me figure out how to fix it first.
