### ISSUE TITLE
statvfs("/proc/sys") does not have os.ST_RDONLY

### ISSUE THREAD

**Issue by martinpitt** [lxc/lxcfs#111]
lxcfs' view on `/proc/sys` is supposed to be read-only, so that containers cannot change sysctls. However, when `statvfs()`ing `/proc/sys`, it is not marked as read-only:
```
$ lxc launch images:ubuntu/xenial/amd64 x1
$ lxc exec x1 -- python3 -c 'import os; s=os.statvfs("/proc/sys"); print(s.f_flag & os.ST_RDONLY)'
0
```
This is 1 on "real" read-only mounts. This is what systemd's `ConditionPathIsReadWrite=` is using, and since this is not marked as read-only, `ConditionPathIsReadWrite=/proc/sys` is met which causes `systemd-sysctl.service` to start, but fail, in an unprivileged LXC container.

This is mostly just a cosmetic problem, but it was reported in https://launchpad.net/bugs/1576341 .

**Comment by stgraber** [comment]
lxcfs isn't responsible for the /proc/sys view in the container.

It's also quite correct for unprivileged containers to have a writable /proc/sys given that it's the kernel doing the access control in such case through good old ownership checks, that is, only the paths that are properly namespaced can be written to, the rest gets you EACCES.

**Comment by hallyn** [comment]
Sorry, where did you get the idea that lxcfs would make /proc/sys readonly?  It currently only virtualizes a few procfiles, which must be individually bind-mounted.

Virtualizing /proc/sys may be a nice-to-have, and might be worth doing.  However it should not be seen as a security feature since the container could simply umount it.  Rather we have apparmor protections in place to protect non-namespaced /proc/sys files.

**Comment by stgraber** [comment]
Note that even in privileged containers, it's not particularly rare for /proc/sys to be writable, instead relying on a MAC like AppArmor or SELinux to do the per-file filters.

Mounting /proc/sys read-only is usually the wrong approach as there are paths under there that are properly namespaced and should be writable (all of /proc/sys/net, some of the /proc/sys/kernel files like hostname or the IPC knobs, ...).

**Comment by martinpitt** [comment]
Thanks for the heads-up! I was mis-thinking that `/proc/sys` should be r/o and sysctls forbidden in containers, but if (some) of them are namespaced, so much the better. Sorry for the noise then!

**Comment by martinpitt** [comment]
I. e. it is actually correct/desirable to apply `/etc/sysctl.d/` and friends in containers, right?

**Comment by stgraber** [comment]
@martinpitt yes, so long as you treat EACCES as a normal error which should just be ignored (sysctl not allowed by this particular kernel for this particular key).
I in fact very much rely on the net.x.y.z ones applying in a bunch of my containers.
