### ISSUE TITLE
How to use lxcfs elegantly while docker doesn't allow users to mount on /proc

### ISSUE THREAD

**Issue by wangxing1517** [lxc/lxcfs#112]
Hi, guys! When I tried to mount /var/lib/lxcfs/proc on CONTAINER:/proc, I got error like this:

> _cannot be mounted because it is located inside "/proc"._

How to solve this problem?

**Comment by hallyn** [comment]
I'm not sure how you're trying to mount it, but /var/lib/lxcfs/proc is
not meant to be mounted as a directory.  Rather, each file is meant
to be bind-mounted onto the same-named file under /proc.

**Comment by wangxing1517** [comment]
I solved it and your answer do help me a lot, thanks! @hallyn 
But now I have another question, could I mount /var/lib/lxcfs/cgroup as a directory?

**Comment by hallyn** [comment]
Hi - well lxc mounts each subdirectory of /var/lib/lxcfs/cgroup.  For one
thing it allows mounting things like "cpu,cpuset" separately as cpu and
cpuset.  But mounting the whole thing *should* be fine in that case.
Somehow it never even occurred to me to try that :)
