### ISSUE TITLE
Allow chdir to the paths the user can otherwise access

### ISSUE THREAD

**Issue by stgraber** [lxc/lxcfs#116]
This is from: https://bugs.launchpad.net/ubuntu/+source/lxcfs/+bug/1587688

Basically, we currently have this weird behavior on cd:
 - /var/lib/lxcfs => EINVAL
 - /var/lib/lxcfs/proc => EACCESS
 - /var/lib/lxcfs/cgroup => EIO

All of those should succeed so long as the user otherwise has permissions to view those paths (which should always be the case for those three).

It would probably also be nice to make sure that all paths under /var/lib/lxcfs probably return a "." and ".." entry and plausible ownership and permissions for all of those.

That would make lxcfs behave a bit more like an actual filesystem.

This is a nice to have, probably beginner contributor kind of issue as it's not at all required for the normal operation of lxcfs.

**Comment by hallyn** [comment]
Very simple special handling of path "/" at lxcfs_open and lxcfs_access() is
probably the solution here.  Patches welcome.
