### ISSUE TITLE
mount lxcfs on start

### ISSUE THREAD

**Issue by ameyaGit** [lxc/lxcfs#118]
Hi,
How do i make sure lxcfs mounts on startup , coz on reboot it's not mounts, I tried editing the /etc/fstab  did not work

**Comment by stgraber** [comment]
what distribution, what version of the distribution, what version of lxcfs, where did you get it from, ...

context is kind of important for bug reports...

**Comment by stgraber** [comment]
lxcfs is usually mounted by init scripts shipped by your Linux distribution, it's a fuse filesystem and so can't be listed in /etc/fstab

**Comment by ameyaGit** [comment]
Hi,
Apologies, 
kernel - 3.10.0-327.18.2.el7.x86_64
os - CentOS Linux release 7.2.1511 (Core)
lxcfs - 2.0.1

lxcfs compiled it from the tar

**Comment by ameyaGit** [comment]
I have compiled lxcfs with prefix /usr/local/lxcfs-bin/

**Comment by ameyaGit** [comment]
Hey,
I resolved it .
thanks for your help stgraber :)
