### ISSUE TITLE
RAM info is not properly containerized [glances]

### ISSUE THREAD

**Issue by loru** [lxc/lxcfs#119]
# Required information

 * Distribution: Ubuntu 16.04
 * Distribution version: Ubuntu 16.04
   * Kernel version: 4.4.0-22-generic
   * LXD version: 2.0.2
   * Storage backend in use: ZFS

# Issue description

The host server runs with 4 Gigs of ram. The container is set to use only 256MB of ram and can't exceed its limit. Even though you can find the proper /proc/meminfo, running (i.e.) glances will show the entire RAM of the host, and not only the 256MB supposedly set earlier:

/proc/meminfo:
```
MemTotal:         262144 kB
MemFree:          173640 kB
MemAvailable:     173640 kB
Buffers:               0 kB
Cached:            58916 kB
SwapCached:            0 kB
Active:           830952 kB
Inactive:         137448 kB
Active(anon):     111448 kB
Inactive(anon):    65648 kB
Active(file):     719504 kB
Inactive(file):    71800 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                52 kB
Writeback:             0 kB
AnonPages:         89192 kB
Mapped:            77764 kB
Shmem:             87876 kB
Slab:               0 kB
SReclaimable:     101908 kB
SUnreclaim:       701888 kB
KernelStack:       11488 kB
PageTables:         6996 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1983828 kB
Committed_AS:     640552 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     26624 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      148068 kB
DirectMap2M:     3971072 kB
```

htop:

![screen shot 2016-06-12 at 12 26 27 pm](https://cloud.githubusercontent.com/assets/19887885/15990633/460435b0-3099-11e6-826e-0445e9d035e0.png)

atop:

![screen shot 2016-06-12 at 12 27 30 pm](https://cloud.githubusercontent.com/assets/19887885/15990636/4ff5ba30-3099-11e6-8b3e-7e5af8e9002e.png)

glances:

![screen shot 2016-06-12 at 12 26 53 pm](https://cloud.githubusercontent.com/assets/19887885/15990638/555e95dc-3099-11e6-82c5-9d53ed04f4ee.png)

# Steps to reproduce

 1. Inside the container, set a hard memory limit, for example 256MB
 2. Install the package glances (available in ubuntu/debian)
 3. Run glances as root (in the container): it will display the entire ram, not the ram you configured earlier

Note: as suggested by @stgraber, I open this issue here but it has already been opened there with explanations:
https://github.com/lxc/lxd/issues/2109

I can not submit a patch, sysadmin but no dev, I do my part as much as I can.

**Comment by hallyn** [comment]
Yeah this would be good to fix - thanks.

**Comment by hallyn** [comment]
Got a plane flight coming up, I'll aim to virtualize all the remaining fields in meminfo during that flight.

**Comment by loru** [comment]
Hi,

Okay, I got some more information, this time with the public console available on https://linuxcontainers.org/lxd/try-it/

Create a container: lxc launch ubuntu:16.04
Access it through lxc shell [your-container]
Install htop and glances.

htop: 
![screen shot 2016-08-24 at 6 56 27 pm](https://cloud.githubusercontent.com/assets/19887885/17939911/dd882b40-6a2c-11e6-979a-544d7a512f61.png)

glances:
![screen shot 2016-08-24 at 6 56 46 pm](https://cloud.githubusercontent.com/assets/19887885/17939920/e9b83572-6a2c-11e6-878b-03653d8c5ea2.png)


I missed it but you can see the entire ram of the host (12GB, with around 6GB of RAM currently used), and the CPU (12 cores), also the uptime (15 days). Is the root filesystem sizing around 20GB too?

Yes, I get it, you can't use 12 cores in it, nor you can use 12GB of ram. But you still see this kind of information, this shouldn't happen as it doesn't on OpenVZ for example. :)

Hopefully this is gonna help you on this issue!

**Comment by hallyn** [comment]
The proposed fix is in git HEAD, not on the try-me server.
