### ISSUE TITLE
fuse: error creating thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by davereiner** [lxc/lxcfs#122]
We recently started getting the above error on one of the Ubuntu 16.04 4.4.0-24 LXD host machines:
```
lxcfs[1467]: fuse: error creating thread: Resource temporarily unavailable
lxcfs[1467]: Timed out waiting for scm_cred: No such file or directory
lxcfs[1467]: fuse: error creating thread: Resource temporarily unavailable
lxcfs[1467]: Timed out waiting for scm_cred: Resource temporarily unavailable
```
All the system limits were set to fairly high numbers:
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 838276
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 500000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 65535
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
however stack size is one that has only been raised since last reboot. The error only appears periodically and then "goes away" for some time.

```
ls -1d /proc/*/task/* | wc -l
31582
```

Any ideas? Thanks!

**Comment by brauner** [comment]
Seems the same as: #73.

**Comment by davereiner** [comment]
I read through that prior to posting (and everything else Google threw at me), however "fuse: error creating thread: Resource temporarily unavailable" seems to be an important distinction, but of course I'm not too familiar with the internals of lxcfs.

**Comment by davereiner** [comment]
Turns out it was completely unrelated to lxcfs: **kernel.pid_max** is set to 32768 by default... Raising that made this problem go away too.
