### ISSUE TITLE
errors when trying `lxcfs -h` as a user

### ISSUE THREAD

**Issue by evgeni** [lxc/lxcfs#135]
Ohai,

```
% ./lxcfs -h
failed to create directory '/run/lxcfs/': Permission deniedFailed to create lxcfs cgroup mountpoint.
Usage:

lxcfs [-p pidfile] mountpoint
  Default pidfile is /run/lxcfs.pid
lxcfs -h
```

Why does lxcfs try to do something while I only wanted to see the help? This is esp annoying as this line is added to the manpage if the build is not running as root :)

**Comment by evgeni** [comment]
I think this was introduced in 237e200e8d117c83c246e34248dd4b39acd7e033 (which started to print the cgroup hiararchy). and then made an error out of it in 29a73c2fe59c13cc0707e66412cdeb80bcabfd33

**Comment by stgraber** [comment]
https://github.com/lxc/lxcfs/pull/134 fixed this.

**Comment by evgeni** [comment]
@stgraber nope, #134 was different.

I still get
```
% ./lxcfs -h
failed to create directory '/run/lxcfs/': Permission deniedFailed to create lxcfs cgroup mountpoint.
Usage:

lxcfs [-p pidfile] mountpoint
  Default pidfile is /run/lxcfs.pid
lxcfs -h
```

see the failed messages in the first line

**Comment by brauner** [comment]
I'm getting the suspicion that this has to do with how `libtool` behaves on `Fedora`. `Debian` and `Ubuntu` don't seem to link `lxcfs` against `liblxcfs.so`:

```
chb@conventiont|~
> apt search lxcfs
Sorting... Done
Full Text Search... Done
libpam-cgfs/yakkety,now 2.0.3-0ubuntu2 amd64 [installed,automatic]
  PAM module for managing cgroups for LXC

lxcfs/yakkety,now 2.0.3-0ubuntu2 amd64 [installed]
  FUSE based filesystem for LXC

chb@conventiont|~
> ldd /usr/bin/lxcfs
        linux-vdso.so.1 =>  (0x00007ffe9c9c6000)
        libfuse.so.2 => /lib/x86_64-linux-gnu/libfuse.so.2 (0x00007f3c07825000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3c07621000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3c07403000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3c0703c000)
        /lib64/ld-linux-x86-64.so.2 (0x000055febbdff000)
chb@conventiont|~
>
```

Compiled from git current master on `Fedora 24`:

```
[root@fed24 lxcfs-2]# ldd .libs/lxcfs
        linux-vdso.so.1 (0x00007fff865c8000)
        libfuse.so.2 => /lib64/libfuse.so.2 (0x00007fbb37786000)
        liblxcfs.so.0 => /usr/local/lib/liblxcfs.so.0 (0x00007fbb3756e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fbb3736a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbb3714e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbb36d8b000)
        /lib64/ld-linux-x86-64.so.2 (0x0000558c40d6a000)
```

I think we should explicitly not link `lxcfs` against `liblxcfs.so`. I already tested that this also prevents `Fedora` from linking. I see no downsides and we use `dlopen()` anyway. Plus: We can get rid of the `__attribute__(constructor)` being run before main(). Rather, we can ensure it is run iff we call `dlopen()`.
