### ISSUE TITLE
get_cgroup failed to receive response

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxcfs#142]
Hello,

Under Gentoo ARMv8 + 3.14LTS for Odroid C2, app-emulation/lxc-2.0.1, sys-fs/lxcfs-2.0.2, I have:
      lxc-start 20160830214713.789 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
I note a strange:
name=openrc on /run/lxcfs/controllers/name=openrc type cgroup (rw,relatime,release_agent=/lib64/rc/sh/cgroup-release-agent.sh,name=openrc)

Cheers,

**Comment by hallyn** [comment]
Sorry, this has been open awhile - is this still happening?  Is simply emerging lxcfs on a gentoo system enough to reproduce it?  Can you also reproduce it with upstream git?

**Comment by alphaonex86** [comment]
Now work, but the bug of name=openrc remain into /proc/mounts

**Comment by hallyn** [comment]
If I understand you right, that is expected.
