### ISSUE TITLE
 /var/lib/lxcfs provides unexpected behavior

### ISSUE THREAD

**Issue by smoser** [lxc/lxcfs#149]
`/var/lib/lxcfs` being mounted in the container provides unexpected behavior for users of `/var`.

    root@x1:~# find /var >/dev/null  2>err; echo $?
    1
    root@x1:~# tail -n 5 err 
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/system.slice/systemd-update-utmp.service/devices.deny': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/system.slice/dev-random.mount/devices.allow': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/system.slice/dev-random.mount/devices.deny': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.allow': Permission denied
    find: '/var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.deny': Permission denied

    root@x1:~# ls -l /var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.allow
    ls: cannot access '/var/lib/lxcfs/cgroup/devices/lxc/x1/user.slice/devices.allow': Permission denied
    root@x1:~# ls -l /var/lib/lxcfs/cgroup/devices/lxc/x1/                        
    ls: cannot access '/var/lib/lxcfs/cgroup/devices/lxc/x1/devices.allow': Permission denied
    ls: cannot access '/var/lib/lxcfs/cgroup/devices/lxc/x1/devices.deny': Permission denied
    total 0
    -rw-r--r-- 1 nobody nogroup 0 Oct  6 18:36 cgroup.clone_children
    -rw-rw-r-- 1 nobody root    0 Oct  6 18:36 cgroup.procs
    ?????????? ? ?      ?       ?            ? devices.allow
    ?????????? ? ?      ?       ?            ? devices.deny
    -r--r--r-- 1 nobody nogroup 0 Oct  6 18:36 devices.list
    drwxr-xr-x 2 root   root    0 Oct  6 18:36 init.scope
    -rw-r--r-- 1 nobody nogroup 0 Oct  6 18:36 notify_on_release
    drwxr-xr-x 2 root   root    0 Oct  6 18:36 system.slice
    -rw-rw-r-- 1 nobody root    0 Oct  6 18:36 tasks
    drwxr-xr-x 2 root   root    0 Oct  6 18:36 user.slice

Root generally expects to be able to read things, likely tools or users will find errors here.

# Steps to reproduce
 1. `lxc launch ubuntu-daily:xenial x1`
 2. `lxc exec x1 find /var/`

Note, originally opened at https://github.com/lxc/lxd/issues/2468

**Comment by brauner** [comment]
Hm, I've got a fix for this. Just need to think through whether this is safe.
