### ISSUE TITLE
Memory seems never released

### ISSUE THREAD

**Issue by mayasd** [lxc/lxcfs#163]
Hi,

There are something I don't understand with LXC and memory. On a fresh LXC install (lxc 2.0.6 and lxcfs 2.0.5, Debian Jessie), I created a debian container.
On this container, I have a postgresql database. I executed a SELECT on a table, the request finishes correctly but all memory appear used and not released.

Container memory stats before sql request : https://paste.ubuntu.com/23693584/
Container memory stats after sql request : https://paste.ubuntu.com/23693595/

On LXC host I see memory used but it's cached : https://paste.ubuntu.com/23693535/

**Comment by hallyn** [comment]
The memory.stat file shows this is 'cache', which iiuc is the pagecache.  That will slowly get released on the system as it needs to be.

**Comment by mayasd** [comment]
Ok but if you look this (https://paste.ubuntu.com/23693595/) :

```
             total       used       free     shared    buffers     cached
Mem:          4096       4094          1         42          0          0
-/+ buffers/cache:       4094          1
Swap:         2048          0       2048
```

Can you explain to me how « used buffers/cache » can be equal to 4094 ?

**Comment by hallyn** [comment]
Not really, I'm afraid I'm not that familiar with how free generates its numbers.  What do you think they should read?

The actual /proc/meminfo contents (which free -m uses) are generated in the function proc_meminfo_read() in bindings.c.  You can see that the 'memory usage' number is taken from the memory.usage_in_bytes cgroup value.  I think it'll help us to fix your issue if we see simultaneous values for free -m  and memory.usage_in_bytes and memory.limit_in_bytes.

The original issue subject was about memory not getting released.  My claim was that it would be released over time as pagecache is released.  If that is not happening, please reply and we should re-open this issue.

**Comment by theredcat** [comment]
I have the exact same problem. As you can see on this screenshot https://i.snag.gy/ud3bIo.jpg I have 7.8Gb of memory that show as used but i only have a really basic system running.

If you're not familliar with htop, the green bar is the memory used and the yellow one is the cache. As you can see there is almost no cache but the memory is claimed as used.

Numbers with free -m are the exact same thing.
