### ISSUE TITLE
Issues with cg_rmdir - SEGFAULT

### ISSUE THREAD

**Issue by Xeno22** [lxc/lxcfs#167]
Hi there,

Could this check in cg_rmdir be an issue?

```
	if (!caller_is_in_ancestor(initpid, controller, cgroup, &next)) {
		if (!last || strcmp(next, last) == 0)
			ret = -EBUSY;
		else
			ret = -ENOENT;
		goto out;
	}
```

If caller_is_in_ancestor returns false and next = NULL, strcmp would crash hardly.
Shouldn't it be more like (if ret = noerror is correct):
```
    if (!caller_is_in_ancestor(initpid, controller, cgroup, &next)) {
         if (!next)
            ret = 0;
        else if (!last || strcmp(next, last) == 0)
            ret = -EBUSY;
        else
            ret = -ENOENT;
        goto out;
    }
```

Just tried to understand a problem of our cloud provider where lxcfs crashes when multiple containers run the phpsessioncleanup.timer service via systemd in Ubuntu 16.04 (Many thanks to Mr. Kaymaz).

**Comment by brauner** [comment]
@Xeno22, indeed this is a problem. Care to send that as a patch?

**Comment by Xeno22** [comment]
Sure, but is in this state a `ret = 0` correct?

**Comment by brauner** [comment]
Na, i think correct would by:

```
if (!last || (next && (strcmp(next, last) == 0)))
```

**Comment by brauner** [comment]
Feel free to grab this code piece, I waive all rights. :)

**Comment by Xeno22** [comment]
So ENOENT could be corrent, here it goes:

```
diff --git bindings.c bindings.c
index 3516be6..a23c349 100644
--- bindings.c
+++ bindings.c
@@ -2908,7 +2908,7 @@ int cg_rmdir(const char *path)
 	if (initpid <= 0)
 		initpid = fc->pid;
 	if (!caller_is_in_ancestor(initpid, controller, cgroup, &next)) {
-		if (!last || strcmp(next, last) == 0)
+		if (!last || (next && (strcmp(next, last) == 0)))
 			ret = -EBUSY;
 		else
 			ret = -ENOENT;
```

**Comment by brauner** [comment]
Can you send a pr here and don't forget to sign-off your commit. :)

**Comment by Xeno22** [comment]
So, I created my first PR ... hope this went well.

**Comment by brauner** [comment]
Forgot to close when we merged the fix. Closing now.
