### ISSUE TITLE
lscpu shows all cpu cores of physical server

### ISSUE THREAD

**Issue by k-hristov** [lxc/lxcfs#181]
Hey there,

First a little bit of useful information:
OS: Ubuntu 16.04 LTS
LXD: 2.0.9
LXCFS: 2.0.6
Kernel: 4.8.0-39-generic

In reference to https://github.com/lxc/lxd/issues/3131 when executing lscpu it shows the cpu cores of the host machine.

I have a container with cpu limit of 4 cpu cores:

> cat /proc/cpuinfo |grep processor
> processor	: 0
> processor	: 1
> processor	: 2
> processor	: 3

when running `lscpu` i get the following output

> Architecture:          x86_64
> CPU op-mode(s):        32-bit, 64-bit
> Byte Order:            Little Endian
> CPU(s):                32
> On-line CPU(s) list:   0-31
> Thread(s) per core:    2
> Core(s) per socket:    8
> Socket(s):             2
> NUMA node(s):          2
> Vendor ID:             GenuineIntel
> CPU family:            6
> Model:                 45
> Model name:            Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
> Stepping:              7
> CPU MHz:               1648.388
> BogoMIPS:              4399.94
> Virtualization:        VT-x
> L1d cache:             32K
> L1i cache:             32K
> L2 cache:              256K
> L3 cache:              20480K
> NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
> NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31

Another thing ( not sure if it requires another issue )
When running a custom C code with the following content:

> #include <unistd.h>
> #include <stdio.h>
> #include <stdlib.h>
> 
> int main() {
> 
>   long nprocs = -1;
>   long nprocs_max = -1;
> 
>   nprocs = sysconf(_SC_NPROCESSORS_ONLN);
>   nprocs_max = sysconf(_SC_NPROCESSORS_CONF);
> 
>   printf("Processors online: %ld\n", nprocs);
>   printf("Processors configured: %ld\n", nprocs_max);
> 
> }

i get this result:

> Processors online: 32
> Processors configured: 32

which is the amount of cpu cores on the host machine.

**Comment by stgraber** [comment]
There's unfortunately nothing we can do about that. We can mask files like /proc/cpuinfo but we can't hijack kernel syscalls to return a different value...

The only way to fix this would be to convince the upstream kernel developers that returning the effective limit (cgroups) rather than the global host value would be preferred. This has been attempted many times and failed every single one of those though...

Closing the lxcfs bug since it can only mask filesystem entries and this isn't one.
