### ISSUE TITLE
Proposal: Calculate uptime for container with start time of init process in container

### ISSUE THREAD

**Issue by hustcat** [lxc/lxcfs#184]
Now, we use  [/proc/$init_pid](https://github.com/lxc/lxcfs/blob/master/bindings.c#L3475) 's ctime as container's uptime.  However, when kernel drop inode cache, such as run `echo 3 > /proc/sys/vm/drop_caches`, will cause `/proc/$init_pid` inode newly created, this will make uptime in container become zero. @hallyn

**Comment by hallyn** [comment]
Sure, we can just use the start_time field in /proc/pid/stat.  Would
you like to propose a patch to make that change?

**Comment by stgraber** [comment]
Oh, so that's what's happening there, interesting!

@brauner if @hustcat doesn't have the time to send a fix, can you take care of this?

**Comment by brauner** [comment]
@stgraber, can you assign the issue to me, please?
