### ISSUE TITLE
Wrong STIME on processlist inside container

### ISSUE THREAD

**Issue by wociscz** [lxc/lxcfs#189]
* Distribution: Ubuntu
 * Distribution version:  Xenial 16.04.2
 * lxc info:
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-22-generic
  server_version: "2.14"
  storage: zfs
  storage_version: 0.6.5.9-2

processes inside container has/shows STIME in future. Right now it is +4days (vary on different servers, dont see any "rule" for that) from server time.
when i run ps -ef it looks like this:
```
root@fresh-platypus:~# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Jun16 ?        00:00:00 /sbin/init
root        37     1  0 Jun16 ?        00:00:00 /lib/systemd/systemd-udevd
root        38     1  0 Jun16 ?        00:00:00 /lib/systemd/systemd-journald
syslog      95     1  0 Jun16 ?        00:00:00 /usr/sbin/rsyslogd -n
root        98     1  0 Jun16 ?        00:00:00 /usr/sbin/cron -f
root       139     1  0 Jun16 ?        00:00:00 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.
root       161     1  0 Jun16 console  00:00:00 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
root       187     0  0 Jun16 ?        00:00:00 /bin/bash
root       202   187  0 Jun16 ?        00:00:00 ps -ef
root@fresh-platypus:~# date
Mon Jun 12 08:51:25 UTC 2017
root@fresh-platypus:~# cat /etc/timezone 
Etc/UTC
root@fresh-platypus:~# uptime
 08:51:38 up 5 min,  0 users,  load average: 0.06, 0.08, 0.03
root@fresh-platypus:~#
```

lxc info fresh-platypus:
```
root@s1:~# lxc info fresh-platypus
Name: fresh-platypus
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/06/12 08:46 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 6215
Ips:
  eth0:	inet	10.228.80.178	vethIM2OLJ
  eth0:	inet6	fd42:aa1a:65cd:d5bb:216:3eff:fed2:324b	vethIM2OLJ
  eth0:	inet6	fe80::216:3eff:fed2:324b	vethIM2OLJ
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 9
  Disk usage:
    root: 2.40MB
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 30.44MB
    Memory (peak): 32.57MB
  Network usage:
    eth0:
      Bytes received: 7.45kB
      Bytes sent: 1.69kB
      Packets received: 69
      Packets sent: 15
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
```

default profile:
```
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
```

Don't know from which version of lxd/lxcfs is this happened. On my older servers with lxd 2.6.2 ps -ef shows right values.
Right now i'm on 4.10.x kernel but this happened with 4.4.x (default ubuntu server kernel) too.

Process to reproduce:
1) install newest lxd
2) lxc launch images:ubuntu/xenial newcontainer
3) lxc exec newcontainer -- /bin/bash
4) ps -ef

**Comment by brauner** [comment]
So yes, this is unfortunate but it *might* be out of scope to fix this for us. I suspect that `ps` is reading the `STIME` value from the `/proc/<pid>/status` file's `starttime` field. If that's the case then we'd effectively would need to virtualize `/proc/<pid>/status` for each process relative to the container's uptime we calculate for `/proc/uptime`. That's quite a lot of fuse (pun intended) we'd burn in terms of syscalls. @hallyn, or am I thinking wrong?

**Comment by wociscz** [comment]
as i wrote - on server with
lxcfs=2.0.5-0ubuntu2~ubuntu16.04.1~ppa
liblxc1=2.0.7-0ubuntu1~16.04.2
lxc-common=2.0.7-0ubuntu1~16.04.2
lxd=2.6.2-0ubuntu3~ubuntu16.04.1~ppa1
ps -ef shows proper values in container.. so were there changes from 2.0.5 > 2.0.7 (lxcfs) which are involved in this behaviour (i know there were lot of changes, but i'm not programmer...)?

**Comment by brauner** [comment]
@wociscz oh cool, thanks for the pointers. I'll compile and test.

**Comment by brauner** [comment]
So I identified the "bad" commit that causes this. But this is a trade-off decision. So basically someone virtualized the btime field in `/proc/stat` to show the container's value. This is fair. But unfortunately this also means that `ps` will miscalculate the `STIME` field because it does so (At least I think so.) based on the `starttime` field `/proc/<pid>/status` which needs to be accounted for against the btime value of the host not the container. So in order for the `ps` output to be correct we'd effectively need to do exactly what I've mentioned above which is not doable given the overhead this would cause.

**Comment by wociscz** [comment]
hmm, and what is purpose of virtualized btime in containers /proc/stat if this is some bogus value in (random?) future? Is this value used somewhere else - dont understand the need of this, but maybe i'm missing the point. 
Thanks for tracking it down, at least i know it is a "feature" now :)

**Comment by stgraber** [comment]
@brauner where is the btime field in /proc/stat used? I suspect we'll have to decide which of the two has the most user impact. Correct btime in /proc/stat or correct stime rendering for all processes. Then pick that one and document why we can't do the other.

**Comment by hallyn** [comment]
Quoting Christian Brauner (notifications@github.com):
> So yes, this is unfortunate but it *might* be out of scope to fix this for us. I suspect that `ps` is reading the `STIME` value from the `/proc/<pid>/status` file's `starttime` field. If that's the case then we'd effectively would need to virtualize `/proc/<pid>/status` for each process relative to the container's uptime we calculate for `/proc/uptime`. That's quite a lot of fuse (pun intended) we'd burn in terms of syscalls. @hallyn, or am I thinking wrong?

Well we'd have to overmount all of proc, would definately have an impact.

**Comment by wociscz** [comment]
If there is some way how to display/count/whatever correct value inside container in userspace? So - i'll be able to "create" ps variant (script/wrapper) for using inside lxc container(?) In old days i remember we've had something similar within openvz. But don't know how bad is this approach.

But imho i think these values is something what i should need/want.

**Comment by wociscz** [comment]
yesterday update of ubuntu package lxcfs 2.0.7-0ubuntu3~ubuntu16.04.1~ppa1 made some changes in this.
Now the STIME is not ~3days in future, but only ~52 minutes.. so this is much more better. And gives me the clue when the processes were started.. so i could live with that :-)
Whoever made this change, thanks!

**Comment by stgraber** [comment]
Because my host has two weeks of uptime, "ps" shows all processes in the container as having been spawned two weeks in the future. We need to fix that as that's going to confuse the heck out of people and monitoring systems...

**Comment by hallyn** [comment]
@brauner let's revert the btime patch at least temporarily.

**Comment by brauner** [comment]
@hallyn, sounds good. Do you want me to send a branch or do you want to?

**Comment by hallyn** [comment]
@brauner please go ahead. I'm away today.
