### ISSUE TITLE
Anyone think about the problem of restart the lxcfs.service？

### ISSUE THREAD

**Issue by jshachm** [lxc/lxcfs#193]
Use  Dokcer，and use `-v  /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw `to mount .Problems happen when l`xcfs.service` restart.  Surely to get the correct `meminfo`， I need to remount it into the docker without restart the container !
Anyone has ideas about this issue?

**Comment by brauner** [comment]
`systemctl restart lxcfs` will cause `lxcfs` to be stopped and restarted completely such that it will be unmounted in the process. However, we implemented `lxcfs` in such a way that you can reload it without having to umount it. Everything it needs is located in a simple-reloadable shared library. So if you update `lxcfs` and want it to use the new shared library you can simply send `SIGUSR1` to it via `kill -s USR1 $(pidof lxcfs)` and it will reload at the next possible instance:

    Jun 19 10:13:50 conventiont lxcfs[32306]: lxcfs.c: 97: do_reload: lxcfs: reloaded

This may not be entirely clear from the current project `README.md`. I'll send a PR to clarify this.

**Comment by jshachm** [comment]
Maybe,I didn't make it clear . I mean when lxcfs meets a crash when a docker is running，how to remount it to the docker

**Comment by brauner** [comment]
Well, in case `lxcfs` crashes the only option is to restart the container since the mount will be gone. However, that shouldn't usually happen.

**Comment by jshachm** [comment]
yeap，brauner ，Sign....  it takes me a lot of time to solve the problem. Seems like that using cmd
`docker run -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo ubuantu:mytag /bin/bash ` 
can't be remounted when` lxcfs` crashes as you said.

I suggest another way to make it up. You know ,restarting a container may be really difficult for some cases. 
To get it down，we need to mount  the upper directory of the /proc with` shared`
like 
`docker run -v /var/lib/lxc/:/var/lib/lxc/:shared -v /var/lib/lxc/lxcfs/proc/meminfo:/proc/meninfo`
the directory` /lxc/ `is  a local directory I added for a test,JUST need to change it when start lxcfs :
`/usr/bin/lxcfs /var/lib/lxc/lxcfs`

when `lxcfs` crashes use cmd like
 `docker exec -d  $Dokcername mount -B /var/lib/lxc/lxcfs/proc/meminfo  /proc/meminfo`to remount the lxcfs to the running container 

docker name can use `docker ps` and some `grep` and `cut` to get them.
I have tested it right. Can you check it? Is it  one way  to solve  the crashes and  make it HA?

**Comment by jshachm** [comment]
Write a toolkit， and solve the event when crashes happen，get it down~

**Comment by elianka** [comment]
@jshachm good job. @brauner Is there any potential issues for this solution?

**Comment by hallyn** [comment]
IIUC what you're suggesting should be fine and should solve this for you.

I do hope that as you run into crashes you'll send us crashdumps  :)

**Comment by tossmilestone** [comment]
I used @brauner 's solution, but error occured:
```
[root@~]# docker exec 86584e81f78a mount -o bind /var/lib/lxcfs/proc/meminfo /proc/meminfo
mount: permission denied (are you root?)
```
How can I mount it as root user?

**Comment by hallyn** [comment]
I suspect you are root - what does "docker exec 86584e81f78a id" show?

There might be an apparmor denial, does your syslog show anything?

**Comment by tossmilestone** [comment]
> I suspect you are root - what does "docker exec 86584e81f78a id" show?

```
[root@host ~]# docker exec 86584e81f78a id
uid=0(root) gid=0(root) groups=10(wheel)
```
>There might be an apparmor denial, does your syslog show anything?

Nothing printed in syslog.

And my os is centos 7.3, kernel 3.10.0

**Comment by stgraber** [comment]
apparmor or dropped caps may prevent you from re-setting that mount in Docker.

**Comment by tossmilestone** [comment]
I found that I missed the mount of `/var/lib/lxc`, but after I mount it, it still has an error when i remount the `meminfo`. The errors:
```
[root@host ~]# docker exec 818a8d308233 mount -B /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo
mount: mount point /proc/meminfo is not a directory
```

**Comment by tossmilestone** [comment]
Finally, I use `nsenter` to remount successfully, here is the command:
```
nsenter --target ${PID} --mount -- mount -B /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo
```
`${PID}` is the container pid.

**Comment by jshachm** [comment]
@tossmilestone  cap  and even --privilged is needed.Dir `/var/lib/lxc` is used to shared mount and created by myself in our solution. `nsenter` is another way of cause.

**Comment by tossmilestone** [comment]
@jshachm thanks for your reply! I run the container with `--privilged`, and it works with your solution. But `--privilged` is not allowed in my scenarios, so `nsenter` is the right way for me.

**Comment by markzhang0928** [comment]
@tossmilestone  hi,  i had already tried this command,
`nsenter --target ${PID} --mount -- mount -B /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo`
 but it doesn't work and return `mount: mount point /proc/meminfo does not exist`.

 I also found a [solution](http://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/)  for remount a volume to a running docker container , it's said that the major:minjor device id of block dev should be send to container mnt namespace via nsenter . But , lxcfs seems to be a special device in container. 

when i tried this command,
`./importenv /proc/2738/environ  nsenter --target 2738 --mount --uts --ipc --net --pid -- sh -c "mount -t fuse.lxcfs lxcfs /tmpmnt"`

it returns:
`mount: wrong fs type, bad option, bad superblock on /lxcfs,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so`

i'm really confused. looking forward to your answer. thx!

**Comment by tossmilestone** [comment]
@markzhang0928 what's your bind propagation of your volume mounts? It should be `slave` or `rslave` in my case.

**Comment by jshachm** [comment]
@tossmilestone @markzhang0928 

yeap, `slave` and `rslave` mount flag is needed.

**Comment by fanhaozzu** [comment]
@tossmilestone hi, i had already tried this command as you mentioned,
nsenter --target ${PID} --mount -- mount -B /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo
but it doesn't work，it return:
mount: mount /var/lib/lxcfs/proc/meminfo on /proc/meminfo failed: Transport endpoint is not connected.

my bind propagation of my volume mounts is slave

**Comment by fanhaozzu** [comment]
@jshachm

**Comment by tossmilestone** [comment]
@fanhaozzu I mounted the whole `/var/lib/lxcfs/proc` to container, and it works.

**Comment by jshachm** [comment]
First of all, upper dir like `/var/lib/lxc/` should be add to the `docker`'s volumes path.
Using cmd like `docker run -tid -v /var/lib/lxc:/var/lib/lxc:shared busybox`

And then the `nsenter` can work.

Because of the issue of `mount propagtion`, this method is the best way to satisfy the usage.

**Comment by fanhaozzu** [comment]
@jshachm @tossmilestone sorry to bother you，thank you. i did, but error is still，i am very confused, I have tried two days.
container：
        {
                "Source": "/var/lib/lxcfs",
                "Destination": "/var/lib/lxcfs",
                "Mode": "rshared",
                "RW": true,
                "Propagation": "rshared"
            },
.
1.cat /etc/mtab
![image](https://user-images.githubusercontent.com/5517088/47919415-466c0d00-deea-11e8-8589-1db6d611b0f9.png)

2.when i restart lxcfs.service，
![image](https://user-images.githubusercontent.com/5517088/47919321-115fba80-deea-11e8-9d7a-6d59ffeae37e.png)

![image](https://user-images.githubusercontent.com/5517088/47919524-83d09a80-deea-11e8-8948-e8fe159782ff.png)

3.nsenter
![image](https://user-images.githubusercontent.com/5517088/47919673-e88bf500-deea-11e8-8d75-f6599c84b3b8.png)

**Comment by tossmilestone** [comment]
@fanhaozzu Restart lxcfs service will cause the mount point lost, you should restart the container to make it remount again.

**Comment by fanhaozzu** [comment]
must restart container?I need to remount it into the docker without restart the container .......

**Comment by fanhaozzu** [comment]
@tossmilestone thank your reply

**Comment by tossmilestone** [comment]
But this is how the mount mechanism work
 :(

**Comment by huzhengchuan** [comment]
test the soulution, restart lxcfs and seem work well, but in container, it will cause many same mountpoints
> [root@testnew2-sit-nginx-25069-8697667655-mmkhg /]# mount | grep lxcfs | sort
lxcfs on /proc/cpuinfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/cpuinfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/diskstats type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/diskstats type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/meminfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/meminfo type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/stat type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/stat type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/swaps type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/swaps type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/uptime type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /proc/uptime type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
lxcfs on /var/lib/lxc/lxcfs type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)

**Comment by markzhang0928** [comment]
> ......



> @jshachm @tossmilestone sorry to bother you，thank you. i did, but error is still，i am very confused, I have tried two days.
> container：
> "Mounts": [
> {
> "Source": "/var/lib/lxcfs/proc/uptime",
> "Destination": "/proc/uptime",
> "Mode": "rslave",
> "RW": true,
> "Propagation": "rslave"
> },
> {
> "Source": "/var/lib/lxcfs",
> "Destination": "/var/lib/lxcfs",
> "Mode": "rshared",
> "RW": true,
> "Propagation": "rshared"
> },
> {
> "Source": "/var/lib/lxcfs/proc/stat",
> "Destination": "/proc/stat",
> "Mode": "rslave",
> "RW": true,
> "Propagation": "rslave"
> },
> {
> "Source": "/var/lib/lxcfs/proc/cpuinfo",
> "Destination": "/proc/cpuinfo",
> "Mode": "rslave",
> "RW": true,
> "Propagation": "rslave"
> },
> {
> "Source": "/var/lib/lxcfs/proc/meminfo",
> "Destination": "/proc/meminfo",
> "Mode": "rslave",
> "RW": true,
> "Propagation": "rslave"
> },
> {
> "Source": "/var/lib/lxcfs/proc/swaps",
> "Destination": "/proc/swaps",
> "Mode": "rslave",
> "RW": true,
> "Propagation": "rslave"
> },
> {
> "Source": "/var/lib/lxcfs/proc/diskstats",
> "Destination": "/proc/diskstats",
> "Mode": "rslave",
> "RW": true,
> "Propagation": "rslave"
> },
> .
> 1.cat /etc/mtab
> ![image](https://user-images.githubusercontent.com/5517088/47919415-466c0d00-deea-11e8-8589-1db6d611b0f9.png)
> 
> 2.when i restart lxcfs.service，
> ![image](https://user-images.githubusercontent.com/5517088/47919321-115fba80-deea-11e8-9d7a-6d59ffeae37e.png)
> 
> ![image](https://user-images.githubusercontent.com/5517088/47919524-83d09a80-deea-11e8-8948-e8fe159782ff.png)
> 
> 3.nsenter
> ![image](https://user-images.githubusercontent.com/5517088/47919673-e88bf500-deea-11e8-8d75-f6599c84b3b8.png)

"Transport endpoint is not connected."  
I used to be frustrated with this problem and finally solved it .
cause your upper directory of lxcfs(/var/lib/ ) is not mount into the container. The bind mount mechanism makes you can't find the inode of this directory "/var/lib/lxcfs" in the container. because when you restart the lxcfs process in the host, the inode of "/var/lib/lxcfs" directory will be changed.

**Comment by jackloveme** [comment]
@markzhang0928 can you share your method？

**Comment by markzhang0928** [comment]
> @markzhang0928 can you share your method？

you could try the methods as @jshachm mentioned.  

https://github.com/lxc/lxcfs/issues/193#issuecomment-309417126

"we need to mount the upper directory of /var/lib/lxc/lxcfs , like this: 

docker run **-v /var/lib/lxc/:/var/lib/lxc/:shared** -v /var/lib/lxc/lxcfs/proc/meminfo:/proc/meninfo

**Comment by xigang** [comment]
I wrote a script and hope to help everyone:)
https://github.com/xigang/lxcfs-admission-webhook/blob/dev/script/container_remount_lxcfs.sh

**Comment by stgraber** [comment]
Not an actual lxcfs issue but one with how it's passed into containers, closing.
