### ISSUE TITLE
`sysinfo` uptime virtualisation

### ISSUE THREAD

**Issue by zerkms** [lxc/lxcfs#200]
Not sure if it's relevant to the now closed (but not fixed) https://github.com/lxc/lxcfs/issues/164#issuecomment-315638100

But `sysinfo`'s `uptime` field returns the uptime value from the host.

A code sample to reproduce:

```c
#include <stdio.h>
#include <sys/sysinfo.h>

int main ()
{
 struct sysinfo si;
 sysinfo (&si);
 printf ("uptime %lu\n", si.uptime);
 return 0;
}
```

And `btime` in `/proc/stat` also shows the boot time of the host machine.

Host OS:  Ubuntu 16.04.2
Versions:
```
ii  liblxc1                            2.0.8-0ubuntu1~16.04.2                     amd64        Linux Containers userspace tools (library)
ii  lxc-common                         2.0.8-0ubuntu1~16.04.2                     amd64        Linux Containers userspace tools (common tools)
ii  lxcfs                              2.0.7-0ubuntu1~16.04.2                     amd64        FUSE based filesystem for LXC
```

**Comment by hallyn** [comment]
Sorry, sysinfo is a separate system call.  This does not and cannot fall in the scope of lxcfs.

See issue #88 regarding btime in /proc/stat

**Comment by zerkms** [comment]
@hallyn is #88 a wrong reference? I don't see anything about btime there

**Comment by hallyn** [comment]
Quoting Ivan Kurnosov (notifications@github.com):
> @hallyn is #88 a wrong reference? I don't see anything about btime there

Indedd worng reference - should be issue #164.

https://github.com/lxc/lxcfs/issues/164
