### ISSUE TITLE
`sysinfo` virtualisation (`totalram`)

### ISSUE THREAD

**Issue by zerkms** [lxc/lxcfs#202]
I just posted https://github.com/lxc/lxcfs/issues/200 specifically about `sysinfo.uptime`, but now I found that at least some other fields are not virtualised either

```c
#include <stdio.h>
#include <sys/sysinfo.h>

int main ()
{
 struct sysinfo si;
 sysinfo (&si);
 printf ("totalram %lu\n", si.totalram);
 return 0;
}
```
This outputs the total amount of memory the host machine has, not the container.

    totalram 8369901568

`/proc/meminfo` has the correct numbers.

    MemTotal:        1048576 kB

**Comment by hallyn** [comment]
Sorry, sysinfo cannot be handled by lxcfs.

**Comment by zerkms** [comment]
@hallyn but openvz could do that, or am I confusing something?

**Comment by hallyn** [comment]
> @hallyn but openvz could do that, or am I confusing something?

Nope you're right, but it did that by having a custom kernel.  See
the do_sysinfo() function at
https://github.com/OpenVZ/vzkernel/blob/branch-rh7-3.10.0-123.1.2-ovz/kernel/sys.c

lxcfs only helps programs which use the procfs to get their info.  If
you can succeed in getting a patch like openvz's into upstream, that
would be terrific.

**Comment by zerkms** [comment]
Oh, I see now. Thanks for the clarification!

**Comment by hallyn** [comment]
Note depending on your workload, one option would be to use seccomp
with SECCOMP_RET_TRACE to have a ptracer intercept the syscall exit
and fix up the results :)

**Comment by zerkms** [comment]
It actually is zabbix that does it, so I think it's time to report them when I have enough time what they have in the `master` branch.

**Comment by hallyn** [comment]
Right - the actual using seccomp-ptrace to fixup the results would be pretty trivial,
the problem is that the container must be traced for that to work, which in turn
means it can't do any tracing itself.  I've not looked at zabbix source so don't
know whether that would be a problem.
