### ISSUE TITLE
tar gives error on /var/lib/lxcfs

### ISSUE THREAD

**Issue by keestux** [lxc/lxcfs#214]
Not sure if this is truly a bug for lxcfs, but it certainly is an unpleasant behaviour. Running tar gives an error on /var/lib/lxcfs. This can easily be shown as follows:

    # /bin/tar --create --file /dev/null --directory /var/lib --one-file-system --ignore-failed-read --exclude lxd --totals .
    /bin/tar: ./lxcfs: file changed as we read it
    /bin/tar: ./samba/private/msg.sock/4284: socket ignored
    /bin/tar: ./samba/private/msg.sock/27637: socket ignored
    /bin/tar: ./sss/pipes/private/sbus-dp_ghs.nl.19709: socket ignored
    /bin/tar: ./sss/pipes/private/sbus-monitor: socket ignored
    Total bytes written: 1248829440 (1,2GiB, 22GiB/s)
    # echo $?
    1

I'm getting this error with my Amanda backups, which runs tar on the backup clients. The workaround is to exclude /var/lib/lxcfs.

**Comment by brauner** [comment]
I'm not sure if this will work correctly. `lxcfs` uses fuse and I'm not sure that backing up `fuse` files works nicely. The `socket ignored` warnings are standard for `tar` though since `tar` doesn't handle sockets.

**Comment by keestux** [comment]
I'm not trying to backup /var/lib/lxcfs. I use --one-file-system and that should skip /var/lib/lxcfs. In fact, it does skip it. Nevertheless it gives an error.

**Comment by brauner** [comment]
Are you sure that `--one-file-system` handles `fuseblk` filesystems correctly? If not you might want to add an `--exclude` that explicitly excludes the `lxcfs` fs.

**Comment by keestux** [comment]
As mentioned above, I'm adding exclude lists to avoid it. For me that's a sufficient workaround.
I don't know whether `fuseblk` filesystems are properly skipped. But I do know that often I see a message that it is skipping followed by a message with the error. The (amanda) log then shows something like this:

      ? /bin/tar: ./var/lib/lxcfs: directory is on a different filesystem; not dumped
      ? /bin/tar: ./var/lib/lxcfs: file changed as we read it

**Comment by brauner** [comment]
Yeah, when fuse modifies the file tar will likely be confused. I don't think there's something we can do about it though.
