### ISSUE TITLE
Does lxcfs has a logo or something like that?

### ISSUE THREAD

**Issue by allencloud** [lxc/lxcfs#229]
Hi, All,

Does lxcfs has a logo or something like that? 
I think it is good to have one for tech spreading.

Allen

**Comment by hallyn** [comment]
Oh this could be fun.

**Comment by stgraber** [comment]
LXC, LXD and LXCFS all share the same logo right now.

https://linuxcontainers.org/static/img/containers.png

**Comment by hallyn** [comment]
Quoting Stéphane Graber (notifications@github.com):
> LXC, LXD and LXCFS all share the same logo right now.
> 
> https://linuxcontainers.org/static/img/containers.png

There must be *some* good fable about someone or something
that helps you see through the self-aggrendizing lies.  The
world wants to tell you "you can do ALL THIS", but really you
want to hear "no, no, you shouldn't think so big, you're just
a small fish"

**Comment by brauner** [comment]
On Tue, Dec 05, 2017 at 07:27:36AM -0800, Serge Hallyn wrote:
> Quoting Stéphane Graber (notifications@github.com):
> > LXC, LXD and LXCFS all share the same logo right now.
> > 
> > https://linuxcontainers.org/static/img/containers.png
> 
> There must be *some* good fable about someone or something
> that helps you see through the self-aggrendizing lies.  The
> world wants to tell you "you can do ALL THIS", but really you
> want to hear "no, no, you shouldn't think so big, you're just
> a small fish"

Is it time for our own per-project spirit animal?

**Comment by stgraber** [comment]
:)

**Comment by brauner** [comment]
Currently not but if you want to suggest something, feel free. :)
