### ISSUE TITLE
when replace the liblxcfs.so，lxcfs coredump

### ISSUE THREAD

**Issue by y123456yz** [lxc/lxcfs#230]
root@ob-xxx-xxx.gz01:/home/odin/xxx$ uname -a
Linux ob-xxx-xxx.gz01 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@ob-xxx-xxx.gz01:/home/odin/xxx$ 

root@ob-xxx-xxx.gz01:/home/odin/xxx$ /usr/local/bin/lxcfs --version
2.0.7
root@ob-xxx-xxx.gz01:/home/odin/xxx$ 

root@ob-xxx-xxx.gz01:/home/odin/xxx$ ll /usr/lib/lxcfs/liblxcfs.so
lrwxrwxrwx 1 root root 26 Nov 16 13:56 /usr/lib/lxcfs/liblxcfs.so -> /usr/local/lib/liblxcfs.so
root@ob-xxx-xxx.gz01:/home/odin/xxx$ 

root@ob-xxx-xxx.gz01:/home/odin/xxx$ /usr/local/bin/lxcfs -s -f -o allow_other /usr/local/var/lib/lxcfs/ &
[1] 17118
root@ob-slave-465.gz01:/home/odin/xxx$ hierarchies:
  0: fd:   5: devices
  1: fd:   6: perf_event
  2: fd:   7: blkio
  3: fd:   8: cpuset
  4: fd:   9: hugetlb
  5: fd:  10: cpuacct,cpu
  6: fd:  11: net_prio,net_cls
  7: fd:  12: pids
  8: fd:  13: freezer
  9: fd:  14: memory
 10: fd:  15: name=systemd

root@ob-xxx-xxx.gz01:/home/odin/xxx$ cp /usr/local/lib/liblxcfs.so ./
root@ob-xxx-xxx.gz01:/home/odin/xxx$ cp ./liblxcfs.so /usr/local/lib
cp: overwrite /usr/local/lib/liblxcfs.so  y
root@ob-xxx-xxx.gz01:/home/odin/xxx$ kill -s USR1 $(pidof lxcfs)
root@ob-xxx-xxx.gz01:/home/odin/xxx$ cat /usr/local/var/lib/lxcfs/
cat: /usr/local/var/lib/lxcfs/: Transport endpoint is not connected
[1]+  Segmentation fault      (core dumped) /usr/local/bin/lxcfs -s -f -o allow_other /usr/local/var/lib/lxcfs/
root@ob-slave-465.gz01:/home/odin/xxx$ 

@brauner
@hallyn
@brauner 
when I cp liblxcfs.so to /usr/local/lib/liblxcfs.so , kill -s USR1 $(pidof lxcfs), then I cat  /usr/local/var/lib/lxcfs/proc/meminfo,  coredump appear immediately

**Comment by y123456yz** [comment]
[root@localhost lxcfs]# gdb ./lxcfs /tmp/coredump/corefile-lxcfs-22141-1513935839
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/huangchunhua/lxcfs/lxcfs/lxcfs...done.
[New LWP 22142]
[New LWP 22143]
[New LWP 22141]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./lxcfs /test'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fdf7d3754f0 in check_match.9440 () from /lib64/ld-linux-x86-64.so.2
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.5.x86_64
(gdb) bt
#0  0x00007fdf7d3754f0 in check_match.9440 () from /lib64/ld-linux-x86-64.so.2
#1  0x00007fdf7d375d3b in do_lookup_x () from /lib64/ld-linux-x86-64.so.2
#2  0x00007fdf7d37601f in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2
#3  0x00007fdf7ca823a9 in do_sym () from /lib64/libc.so.6
#4  0x00007fdf7cf2e0d4 in dlsym_doit () from /lib64/libdl.so.2
#5  0x00007fdf7d37b364 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#6  0x00007fdf7cf2e5bd in _dlerror_run () from /lib64/libdl.so.2
#7  0x00007fdf7cf2e128 in dlsym () from /lib64/libdl.so.2
#8  0x000000000040210f in do_proc_getattr (sb=0x7fdf7c728c70, path=0x7fdf74000c10 "/proc") at lxcfs.c:143
#9  lxcfs_getattr (path=<optimized out>, sb=0x7fdf7c728c70) at lxcfs.c:452
#10 0x00007fdf7d13c860 in lookup_path (f=f@entry=0x1453c90, nodeid=nodeid@entry=1, name=name@entry=0x7fdf7d54e038 "proc", path=<optimized out>, e=e@entry=0x7fdf7c728c60, fi=fi@entry=0x0) at fuse.c:2472
#11 0x00007fdf7d13ca6a in fuse_lib_lookup (req=0x7fdf74000b40, parent=1, name=0x7fdf7d54e038 "proc") at fuse.c:2671
#12 0x00007fdf7d146a56 in fuse_ll_process_buf (data=0x1453f80, buf=0x7fdf7c728ec0, ch=<optimized out>) at fuse_lowlevel.c:2443
#13 0x00007fdf7d143989 in fuse_do_work (data=0x1453680) at fuse_loop_mt.c:117
#14 0x00007fdf7cd18dc5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007fdf7ca4776d in clone () from /lib64/libc.so.6
(gdb) quit

**Comment by stgraber** [comment]
Going to assume that this was a transient bug as the described behavior is exactly what we do on every package update for hundreds of thousands of users and lxcfs reloads the library properly for all of those.
