### ISSUE TITLE
monitoring of container uptime

### ISSUE THREAD

**Issue by skyxx** [lxc/lxcfs#232]
Hi all. 
Im found problem when I run in container netdata or prometheus_node_exporter monitoring. The system uptime is wrong. Both (netdata and prometheus) report uptime of the host not a container.

In container command uptime and file /proc/uptime shows correct value.

Im running LXCFS with latest snap of LXD 2.21 and LXC 2.1.1 on ubuntu 16.04.3

Both get info looks like from /proc/uptime
Netdata 
https://github.com/firehol/netdata/blob/364c4fa2de20eb6ccb60256ce94c34835b79cb0f/src/proc_uptime.c#L15

Prometheus node exporter (for me more complicated to find concrete flow)
https://github.com/prometheus/procfs/blob/master/stat.go
https://github.com/prometheus/node_exporter/blob/master/collector/stat_linux.go

Can you please take a look on it ?
Thanks.

**Comment by brauner** [comment]
Prometheus is running on the host and is monitoring your containers?

**Comment by brauner** [comment]
Is suspect that Prometheus is not attaching to the mount namespace of the container thus

            snprintfz(filename, FILENAME_MAX, "%s%s", netdata_configured_host_prefix, "/proc/uptime");

will read the value from the host. If Prometheus or whatever were to attach to the mount namespace of the container than it would read the correct value.

**Comment by skyxx** [comment]
Hi @brauner, monitoring programs is running inside the container not on host.

**Comment by brauner** [comment]
Ok, can you show me the output of `findmnt` inside the container, please.

**Comment by skyxx** [comment]
[root@test]# findmnt
TARGET                                SOURCE                                                              FSTYPE      OPTIONS
/                                     /dev/sdb1[/common/lxd/storage-pools/default/containers/test/rootfs] xfs         rw,relatime,attr2,inode64,noquota
├─/run                                tmpfs                                                               tmpfs       rw,nosuid,nodev,mode=755,uid=1000000,gid=1000000
│ └─/run/lock                         tmpfs                                                               tmpfs       rw,nosuid,nodev,noexec,relatime,size=5120k,uid=1000000,gid=1000000
├─/dev                                none                                                                tmpfs       rw,nodev,relatime,size=492k,mode=755,uid=1000000,gid=1000000
│ ├─/dev/pts                          devpts                                                              devpts      rw,relatime,gid=1000005,mode=620,ptmxmode=666,max=1024
│ ├─/dev/ptmx                         devpts[/ptmx]                                                       devpts      rw,relatime,gid=1000005,mode=620,ptmxmode=666,max=1024
│ ├─/dev/shm                          tmpfs                                                               tmpfs       rw,nosuid,nodev,uid=1000000,gid=1000000
│ ├─/dev/fuse                         udev[/fuse]                                                         devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/net/tun                      udev[/net/tun]                                                      devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/mqueue                       mqueue                                                              mqueue      rw,relatime
│ ├─/dev/lxd                          tmpfs                                                               tmpfs       rw,relatime,size=100k,mode=755
│ ├─/dev/.lxd-mounts                  tmpfs[/test]                                                        tmpfs       rw,relatime,size=100k,mode=711
│ ├─/dev/null                         udev[/null]                                                         devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/zero                         udev[/zero]                                                         devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/full                         udev[/full]                                                         devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/urandom                      udev[/urandom]                                                      devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/random                       udev[/random]                                                       devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ ├─/dev/tty                          udev[/tty]                                                          devtmpfs    rw,nosuid,relatime,size=1004048k,nr_inodes=251012,mode=755
│ └─/dev/console                      devpts[/1]                                                          devpts      rw,relatime,gid=5,mode=620,ptmxmode=666
├─/proc                               proc                                                                proc        rw,nosuid,nodev,noexec,relatime
│ ├─/proc/sys/fs/binfmt_misc          binfmt_misc                                                         binfmt_misc rw,relatime
│ ├─/proc/cpuinfo                     lxcfs[/proc/cpuinfo]                                                fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/diskstats                   lxcfs[/proc/diskstats]                                              fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/meminfo                     lxcfs[/proc/meminfo]                                                fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/stat                        lxcfs[/proc/stat]                                                   fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/swaps                       lxcfs[/proc/swaps]                                                  fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ └─/proc/uptime                      lxcfs[/proc/uptime]                                                 fuse.lxcfs  rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
└─/sys                                sysfs                                                               sysfs       rw,nodev,relatime
  ├─/sys/fs/cgroup                    tmpfs                                                               tmpfs       ro,nosuid,nodev,noexec,mode=755,uid=1000000,gid=1000000
  │ ├─/sys/fs/cgroup/systemd          cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
  │ ├─/sys/fs/cgroup/devices          cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,devices
  │ ├─/sys/fs/cgroup/pids             cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,pids
  │ ├─/sys/fs/cgroup/freezer          cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,freezer
  │ ├─/sys/fs/cgroup/memory           cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,memory
  │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,net_cls,net_prio
  │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,cpu,cpuacct
  │ ├─/sys/fs/cgroup/perf_event       cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,perf_event
  │ ├─/sys/fs/cgroup/hugetlb          cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,hugetlb
  │ ├─/sys/fs/cgroup/blkio            cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,blkio
  │ └─/sys/fs/cgroup/cpuset           cgroup                                                              cgroup      rw,nosuid,nodev,noexec,relatime,cpuset
  ├─/sys/fs/fuse/connections          fusectl                                                             fusectl     rw,relatime
  ├─/sys/fs/pstore                    pstore                                                              pstore      rw,nosuid,nodev,noexec,relatime
  ├─/sys/kernel/debug                 debugfs                                                             debugfs     rw,relatime
  └─/sys/kernel/security              securityfs                                                          securityfs  rw,nosuid,nodev,noexec,relatime

**Comment by brauner** [comment]
Please show uptime on the host and uptime in the container, i.e.

    cat /proc/uptime

on the host and in the container.

**Comment by skyxx** [comment]
[root@lxd298p]# cat /proc/uptime
695264.32 1381357.28

[root@test]# cat /proc/uptime
12378.00 12186.00

**Comment by brauner** [comment]
That clearly shows that the container and lxcfs is doing the right thing. So it seems that Prometheus somehow is accessing either the underlying file or the host `/proc/uptime`. Can you please show me:

    ps auxf

from inside the container?

**Comment by skyxx** [comment]
```
[root@test]# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       136  0.0  0.1  23276  3892 ?        Ss   11:52   0:00 bash
root      1800  0.0  0.1  43680  3404 ?        R+   15:38   0:00  \_ ps -auxf
root         1  0.0  0.3  72428  8040 ?        Ss   11:52   0:00 /sbin/init
root        41  0.0  0.9  98204 20464 ?        Ss   11:52   0:00 /lib/systemd/systemd-journald
root        42  0.0  0.1  41856  3376 ?        Ss   11:52   0:00 /lib/systemd/systemd-udevd
systemd+    57  0.0  0.2  66452  4684 ?        Ss   11:52   0:00 /lib/systemd/systemd-networkd
systemd+    75  0.0  0.2  65768  4848 ?        Ss   11:52   0:00 /lib/systemd/systemd-resolved
root        78  0.0  0.2  65772  5700 ?        Ss   11:52   0:00 /lib/systemd/systemd-logind
prometh+    81  0.0  0.9 688184 19792 ?        Ssl  11:52   0:20 /usr/bin/prometheus-node-exporter --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvmed+nd+p)d+$ --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)
syslog      85  0.0  0.1 182800  3216 ?        Ssl  11:52   0:00 /usr/sbin/rsyslogd -n
root        91  0.0  0.1  31208  3052 ?        Ss   11:52   0:00 /usr/sbin/cron -f
message+    92  0.0  0.1  47520  3968 ?        Ss   11:52   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root       106  0.0  0.1  15888  2216 console  Ss+  11:52   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
netdata    109  0.0  1.1  24416 22764 ?        SNsl 11:52   0:56 /opt/netdata/bin/srv/netdata -P /run/netdata/netdata.pid -D
root       132  0.0  0.0   1188   516 ?        SN   11:52   0:21  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
netdata   1666  0.0  0.0   1612  1232 ?        SN   15:17   0:01  \_ bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

**Comment by brauner** [comment]
So is this `netdata` thing somehow connect over a socket and requests data from the host?

**Comment by skyxx** [comment]
I dont know if I correctly understand you question, but im check if netdata use some unix socket files with command

`lsof -u netdata | grep unix`

which return zero rows..

**Comment by Blub** [comment]
I think they're using `/proc/stat`'s btime value actually: https://github.com/prometheus/procfs/blob/master/stat.go#L160
btime virtualization has been reverted because of #189

**Comment by brauner** [comment]
Yeah, btime virtualization is really not something we can **currently** do.

**Comment by skyxx** [comment]
Hi guys,
From Prometheus i get answer that they dont support run exporter in containers and close my request.
From Netdata they find problem in code and correct it.

Thanks for help.

**Comment by brauner** [comment]
Oh, that's cool of https://github.com/firehol/netdata/ . Thanks.
