### ISSUE TITLE
Init scripts for sysvinit and systemd not using configuration pathes

### ISSUE THREAD

**Issue by DickerDackel** [lxc/lxcfs#238]
Hi,

looks as if the mountpoint for the fuse fs in both, sysvinit/lxcfs and systemd/lxcfs.service are hardwired to /var/lib/lxcfs.

If you ./configure lxc and lxcfs with --prefix, then PREFIX/share/lxc.mount.hook is properly set up to use PREFIX/var/lib/lxcfs, while the init scripts point to /var/lib/lxcfs, so the mount.hook script points to a non-existing directory.

**Comment by brauner** [comment]
Patches welcome.

**Comment by DickerDackel** [comment]
I'm familiar with code, but that automake/autoconf stuff is over my head.  So I can't volunteer.

Problem still exists in 3.0.2.
