### ISSUE TITLE
`/proc/meminfo` `SwapTotal` incorrectly interprets `memory.memsw.limit_in_bytes`

### ISSUE THREAD

**Issue by zerkms** [lxc/lxcfs#240]
lxcfs: 3.0.0-0ubuntu1
os: ubuntu bionic 18.04

```
# cat /sys/fs/cgroup/memory/lxc/<containername>/memory.memsw.limit_in_bytes 
1879048192

# cat /sys/fs/cgroup/memory/lxc/<containername>/memory.limit_in_bytes 
805306368

# lxc exec <containername> cat /proc/meminfo | grep -i swap
SwapCached:            0 kB
SwapTotal:       1835008 kB
SwapFree:        1834348 kB

# lxc exec <containername> -- free -m
              total        used        free      shared  buff/cache   available
Mem:            768         112         466          59         189         655
Swap:          1792           0        1791
```
As you can see the swap total is taken directly from `memory.memsw.limit_in_bytes` as-is, while it combines memory + swap.

References:

* https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
```
 memory.limit_in_bytes		 # set/show limit of memory usage
 memory.memsw.limit_in_bytes	 # set/show limit of memory+Swap usage
```

**Comment by Blub** [comment]
It's not technically wrong, it's just confusing: You _can_ in fact be using as much swap as `memsw.limit_in_bytes`, you just can't _also_ be using memory which is _not_ swapped out. IIRC we've been going back and forth on that, and whichever way we go, it'll make some people unhappy.
Add to that that with cgroup v2 the story is different yet again and memory and swap limits are separated.
I wonder if we should have configurable options for this?

**Comment by brauner** [comment]
I'm not sure we want to change that yet again so I'm closing but I won't NACK a patch proposal. :)

**Comment by kobuki** [comment]
I don't get at all how an interpretation that's confusing and vastly different from that of any other virtual and physical one gets through to implementation in LXCFS. I just don't get it. It isn't even technically correct when anyone tries to interpret values the usual, well-known way, it's just confusing. And for instance, what would be a reliable programmatic way to tell the exact size of RAM and swap in an LCX container in LXCFS 3.0+?

**Comment by hallyn** [comment]
@brauner did say he wouldn't necessarily nack a patch proposal.  Note that libresource is considered the more reliable way to handle this.

**Comment by kobuki** [comment]
Thanks for the hint. Though it would still be better to be able to rely on the old usual metrics. Now from `/proc/meminfo` the actual swap size is not decipherable without knowing the exact LXCFS version used for the CT. To satisfy both mentioned concepts the configurable option might be the good approach.
