### ISSUE TITLE
Issues with some LXCFS features

### ISSUE THREAD

**Issue by tsch157** [lxc/lxcfs#251]
Hello,

I´m running LXCFS on CentOS 7 but I have some trouble with getting it running properly. Some features of LXCFS seem to not work as I expected. I see the nodes load avg in a container although this should be working since https://github.com/lxc/lxcfs/pull/237. I´m using the latest LXCFS version. Also from containers it is possible to change system wide values in /proc, such as /proc/sys/fs/file-max. LXCFS is implemented as suggested on this page. Can you tell me if this behavour can be explained somehow? I can not track this anymore. Can you give me a hint what might be wrong or is it probably some kind of bug?

Greetings!

**Comment by brauner** [comment]
Hey,
- `/proc/sys/fs/file-max` is currently not virtualized by `LXCFS`
- in order to use the loadaverage feature `lxcfs` needs to be passed the `-l` option at startup

**Comment by tsch157** [comment]
Hello,

Thank you for your fast and helpful response. It would be great to see this in future since settings like these can be changed from a container from an unprivileged user. Unfortunately im not a good dev. I guess there might be some more settings like that I did not check for yet. I currently can´t see any way to prevent containers from doing such changes in /proc or do you might havea hint for me? I´m trying LXC as VPS solution, without LXCFS there would be no way of using it.

Greetings!

**Comment by brauner** [comment]
Are you using privileged containers?
By default `LXC` will remount `/proc/sys` read-only and will block any remounts attempts to make it read-write via AppArmor. So the output of `findmnt` in your container should look like this:
```
|-/proc                                 proc                                 proc       rw,nosuid,nodev,noexec,noatime
| |-/proc/sys                           proc[/sys]                           proc       ro,nosuid,nodev,noexec,noatime
| | `-/proc/sys/net                     proc[/sys/net]                       proc       rw,nosuid,nodev,noexec,noatime
| |-/proc/sysrq-trigger                 proc[/sysrq-trigger]                 proc       ro,nosuid,nodev,noexec,noatime
```
