### ISSUE TITLE
Trying to run lxcfs inside a container

### ISSUE THREAD

**Issue by max8899** [lxc/lxcfs#254]
Hi,

I'm trying to run lxcfs inside a container, but other containers using subsystem under /proc didn't work,
docker run command: 
`docker run -d --privileged=true -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /mnt/lib/lxcfs/:/var/lib/lxcfs:shared -v /dev:/dev --name ubuntu ubuntu:16.04`

and lxvfs started as 

`lxcfs -s -f -o allow_other /var/lib/lxcfs`

**Comment by max8899** [comment]
ping @brauner

**Comment by brauner** [comment]
On Thu, Aug 23, 2018 at 08:02:56PM -0700, max8899 wrote:
> Hi,
> 
> I'm trying to run lxcfs inside a container, but other containers using subsystem under /proc didn't work,
> docker run command: 
> `docker run -d --privileged=true -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /mnt/lib/lxcfs/:/var/lib/lxcfs:shared -v /dev:/dev --name ubuntu ubuntu:16.04`

Why are you mounting /mnt/lib/lxcfs to /var/lib/lxcfs? Is /mnt/lib/lxcfs
where lxcfs is mounted on the host?

**Comment by max8899** [comment]
@brauner  I try to run lxcfs inside the container, /var/lib/lxcfs is the dir inside container, and /mnt/lib/lxcfs is the dir on the host. So the sub system under /var/lib/lxcfs/proc inside container will be available on the host. And other container can use these sub systems.

**Comment by Zexi** [comment]
@max8899 Maybe you should add '--pid=host' to docker run command?

**Comment by databill** [comment]
'--pid=host' won't help to fix this issue. 
I get nothing in the host directory after running lxcfs in the container.

```
docker run -ti --privileged  --pid=host -v /var/lib/lxcfs:/var/lib/lxcfs --name lxcfs2 --name ubuntu ubuntu-with-lxcfs /bin/bash

# lxcfs /var/lib/lxcfs/
```

In the host
```
$ docker exec ubuntu ls /var/lib/lxcfs/
cgroup
proc

$ ls -la /var/lib/lxcfs
total 8
drwxr-xr-x  2 root root 4096 Jan  5 17:11 .
drwxr-xr-x 78 root root 4096 Jan  5 16:58 ..
```

**Comment by g0194776** [comment]
@max8899 
Please DO NOT run lxcfs in the container especially run it by DaemonSet in the Kubernetes cluster.

We've tested it, after lxcfs container crashed it COULD NOT restart successfully again.  Due to lxcfs mount points in the host, It has to be unmount manually before the lxcfs container becomes to UP status.

**Comment by stgraber** [comment]
The preferred way to handle lxcfs with containers is to bind-mount /var/lib/lxcfs into the container from the host.

If you really need to, a properly configured continer with both cgroup namespaces and fuse setup can run lxcfs just fine:

```
root@c1:~# lxcfs /mnt/
mount namespace: 5
hierarchies:
  0: fd:   7: pids
  1: fd:   8: hugetlb
  2: fd:   9: memory
  3: fd:  10: freezer
  4: fd:  11: net_cls,net_prio
  5: fd:  12: devices
  6: fd:  13: blkio
  7: fd:  14: cpuset
  8: fd:  15: rdma
  9: fd:  16: cpu,cpuacct
 10: fd:  17: perf_event
 11: fd:  18: name=systemd
 12: fd:  19: unified
^Z
[1]+  Stopped                 lxcfs /mnt/
root@c1:~# bg 
[1]+ lxcfs /mnt/ &
root@c1:~# ls -lh /mnt/
total 0
drwxr-xr-x 2 root root 0 Mar  3 11:31 cgroup
dr-xr-xr-x 2 root root 0 Mar  3 11:31 proc
root@c1:~# 
```

**Comment by joez** [comment]
it works to serve lxcfs in a container with lxcfs 4.04

```bash
# host directory to mount lxcfs
mkdir lxcfs
# create a container to serve lxcfs
docker run -d --name lxcfs --privileged --pid=host -v /sys/fs/cgroup:/sys/fs/cgroup -v $(pwd)/lxcfs:/var/lib/lxcfs:shared ubuntu:18.04 sleep infinity
# step into the container
docker exec -it lxcfs bash

# setup env to build
apt-get update && apt-get install -y build-essential curl pkg-config libfuse-dev

# build and install lxcfs
mkdir build && cd build \
  && curl -q https://linuxcontainers.org/downloads/lxcfs/lxcfs-4.0.4.tar.gz | tar xz --strip-components 1 \
  && ./configure && make && make install \
  && cd - && rm -rf build

# start lxcfs and exit container
/usr/local/bin/lxcfs --enable-cfs /var/lib/lxcfs/ &
exit

# run into another container with files in lxcfs bind-mounted for verification
docker run -it --rm --memory 256m --cpuset-cpus 0,1 \
  -v $(pwd)/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
  -v $(pwd)/lxcfs/proc/diskstats:/proc/diskstats:rw \
  -v $(pwd)/lxcfs/proc/meminfo:/proc/meminfo:rw \
  -v $(pwd)/lxcfs/proc/stat:/proc/stat:rw \
  -v $(pwd)/lxcfs/proc/uptime:/proc/uptime:rw \
  -v $(pwd)/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online \
  ubuntu:18.04 /bin/bash
# check these information
cat /proc/cpuinfo | grep processor
cat /sys/devices/system/cpu/online
head -n1 /proc/meminfo
exit

# stop the lxcfs
docker exec -it lxcfs bash
kill $(cat /run/lxcfs.pid)
exit

# and kill the serving container
docker kill lxcfs
```

**Comment by cndoit18** [comment]
👀
