### ISSUE TITLE
Can't limit swap usage

### ISSUE THREAD

**Issue by hurelhuyag** [lxc/lxcfs#258]
I'm using `lxd-3.0.1` with `lxcfs-3.0.1` on ubuntu 16.04, 18.04 both. 

memory related config is 
```
raw.lxc: |-
    lxc.cgroup.memory.limit_in_bytes=7516192768
    lxc.cgroup.memory.memsw.limit_in_bytes=10737418240
```
but `free -h` report this:
```
              total        used        free      shared  buff/cache   available
Mem:           7.0G        4.2G          0B         14M        2.8G        2.8G
Swap:           10G        183M        9.8G
```
I think this swap size must be 3GB.

**Comment by Blub** [comment]
In cgroup v1 the limits shown above work as follows:
- You can use 7G of RAM
- The sum of your RAM and swap usage can be 10G

This means if you're currently using up all 7G of RAM, you can additionally use 3G of swap.
But if you're currently only using 1G of RAM, you can use 9G of swap.
You can also be using almost no RAM but 9G of swap.

All these situations can happen because the host can be running out of physical RAM, or quite simply have a very high swappiness set sp the kernel preemptively moves idle processes to swap when they're not doing anything.

**Comment by hurelhuyag** [comment]
When I was using old lxcfs. `free -h` report looks like:

```
              total        used        free      shared  buff/cache   available
Mem:           7.0G        4.2G          0B         14M        2.8G        2.8G
Swap:           3G        183M        2.8G
```

Which one is correct?

**Comment by Blub** [comment]
The reality is that neither is correct when using cgroupv1.
More accurate would be showing 5.8 in this example as 5.8 plus the 4.2 currently-in-use RAM equals 10.
@brauner, now there's an idea, maybe we should actually use `memswlimit - memusage` for SwapTotal... it would be constantly changing, but at least it would reflect the actual behavior...
;-)

**Comment by sergey-dryabzhinsky** [comment]
@Blub It would be even more confusing, I think.
Why not just show expected values?

**Comment by hurelhuyag** [comment]
Still facing this problem.
I'm trying to create container with 1GB RAM, 512MB swap. But there is no way to do it.

Below config wont work because `memory.memsw.limit_in_bytes` is can not lower than `memory.limit_in_bytes`
```
raw.lxc: |-
    lxc.cgroup.memory.limit_in_bytes=1073741824
    lxc.cgroup.memory.memsw.limit_in_bytes=536870912
```

Error log:
```
lxc solre1 20190424033343.431 WARN     cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2228 - Failed to set "memory.memsw.limit_in_bytes" to "536870912"
lxc solre1 20190424033343.431 ERROR    start - start.c:lxc_spawn:1723 - Failed to setup cgroup limits for container "solre1"
```

Then I increased `memory.memsw.limit_in_bytes` to same value with `memory.limit_in_bytes`
Then result is:

```
$ lxc exec solre1 -- free -h
              total        used        free      shared  buff/cache   available
Mem:           1.0G         34M        989M         84K         84K        989M
Swap:          1.0G          0B        1.0G
```

Is there any way to set swap lower than RAM?

**Comment by dmaj** [comment]
I had a similar problem. But for me it was sufficient if I could set the swap to 0. For this there is the parameter "-u" in the command line.

**Comment by stgraber** [comment]
I don't think this is a LXCFS bug, it's a kernel limitation.

The memsw.limit_in_bytes must include the normal memory.

So you get:
 - limit_in_bytes = 1GB
 - memsw.limit_in_bytes = 1.5GB

This means you get to use up to 1GB of RAM and can go up to 1.5GB with swap included.
This doesn't mean you get 512MB of swap either. The kernel may be swapping out more of your memory to the point where you're actually using 512MB of RAM and 1GB of swap.

As the upper bound for the swap usage in this case is 1.5GB, it would be incorrect to show 512MB.
The fact is, there just isn't a good way to render this in Meminfo and some of our previous attempts have failed miserably by causing situations where you could get negative values.

So I don't think we're going to be messing with this unless the kernel offers us a better way to configure this, probably through cgroupv2.
