### ISSUE TITLE
Unable to setup lxcfs on RHEL 7.5

### ISSUE THREAD

**Issue by vamche** [lxc/lxcfs#259]
I am not able to setup lxcfs on RHEL 7.5. Below are the steps I followed.

I couldn’t find alternatives for the below packages(mentioned here https://linuxcontainers.org/lxcfs/getting-started/) except for libfuse-dev (i.e, fuse-devel for RHEL).

> Building lxcfs requires the following libraries and development headers:

> libcgmanager-dev
> libnih-dbus-dev
> libnih-dev
> libfuse-dev

So, I installed fuse-devel + other necessary packages.
`yum install -y autoconf automake libtool fuse fuse-devel`

And executed the below steps
```
git clone git://github.com/lxc/lxcfs
cd lxcfs
./bootstrap.sh
./configure
make
sudo make install
sudo mkdir -p /usr/local/var/lib/lxcfs/
sudo ./lxcfs -s -f -o allow_other /usr/local/var/lib/lxcfs/
```
The process gets stuck like shown in the below screenshot.
<img width="545" alt="screen shot 2018-10-22 at 9 26 04 pm" src="https://user-images.githubusercontent.com/9653338/47340828-07091980-d6bd-11e8-8a51-9aa8fa755abc.png">

I am unable to proceed further and not sure if I am missing anything. I would like to know if someone has setup ‘lxcfs’ on RHEL successfully and steps to do it.

**Comment by tomponline** [comment]
That is it running OK 😃 take a look at my rpm spec file for lxcfs on centos 7 for how to start it as a systemd service https://github.com/tomponline/rpmbuild-el7/blob/master/SPECS/lxcfs.spec

**Comment by vamche** [comment]
Thank you @tomponline! lxcfs.spec worked like a charm! 🙇
