### ISSUE TITLE
Didn't work when use busybox

### ISSUE THREAD

**Issue by wacxt** [lxc/lxcfs#263]
1, start container

`docker run -it -m 256m       -v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw       -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw       -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw       -v /var/lib/lxcfs/proc/stat:/proc/stat:rw       -v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw       -v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw busybox /bin/sh`

2, get meminfo
I found that it didn't work, as it shows the host meminfo

`docker exec containerid free
`

```
/ # free -m
             total       used       free     shared    buffers     cached
Mem:         32124       3607      28517        852          0          0
-/+ buffers/cache:       3606      28518
Swap:        15259       1051      14208
```

3, version
`3.0.3`

**Comment by stgraber** [comment]
Yes, busybox doesn't appear to be using /proc/meminfo, so unfortunately doesn't show the lxcfs values.

**Comment by Blub** [comment]
FYI: busybox's free uses `sysinfo(2)`, there's no way for lxcfs to catch that.

**Comment by wacxt** [comment]
thanks a lot.
