### ISSUE TITLE
There is no cpuacct.usage_all file in CentOS 7.2，should use cpuacct.usage_percpu ?

### ISSUE THREAD

**Issue by lijiaocn** [lxc/lxcfs#273]
OS:  CentOS Linux release 7.2.1511 (Core)
Kernel:  3.10.0-693.11.6.el7.x86_64
Commit:   `d8addb023a0e96b7d42e253703ba909bbc81dd26`

I can't find file cpuacct.usage_all in cgroup cpuacct controller directory, but find file cpuacct.usage_percpu.  cpuacct.usage_all has been instead by cpuacct.usage_percpu?

Now, lxcfs reads cgroup info from cpuacct.usage_all to generate file /proc/stat, if this file doesn't exist, it will just use host's /proc/stat file. So, we'll see host's cpu usage in container.

Open debug mode, will see the error: 

`bindings.c: 4821: proc_stat_read: proc_stat_read failed to read from cpuacct, falling back to the host's /proc/stat`

**Comment by lijiaocn** [comment]
I try to solve this problem:  https://github.com/lxc/lxcfs/pull/274/files

**Comment by hallyn** [comment]
You don't have cpuact.usage_all?  What kernel and distro are you on?

**Comment by lijiaocn** [comment]
After upgrade  kernel to 4.20.12-1.el7.elrepo.x86_64, I find cpuact.usage_all, kernel 3.10 may be too old .

OS: CentOS Linux release 7.2.1511 (Core)
Kernel: 3.10.0-693.11.6.el7.x86_64

<img width="1254" alt="图片" src="https://user-images.githubusercontent.com/6396775/56499502-4237b880-6539-11e9-86a2-647d82d3bc11.png">

**Comment by hallyn** [comment]
Ok then i'm tempted to close this issue and PR #275.  @brauner what do you think?

**Comment by brauner** [comment]
Yeah, I think 3.13 at this point is our cut-off point.
