### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by sheepa** [lxc/lxcfs#276]
Running `docker run -it ubuntu:18.04` inside a lxc container with `security.nesting true` will cause top in the docker container to report the hosts system data. Is there any way to get lxcfs to work with nesting?

**Comment by hallyn** [comment]
You should only need docker to mount the lxcfs files (see /var/lib/lxcfs/proc/*) over the /proc files in the docker container.

**Comment by stgraber** [comment]
Right, this is a Docker issue, the Docker runtime could learn to use lxcfs to improve the behavior of container resource tracking or if that's not an option, you should be able to manually pass all the needed files as bind-mounts for Docker to setup.

There's unfortunately nothing that lxcfs itself can really do about this. Nested LXC and LXD containers both detect lxcfs and pass it through properly as part of their normal lxcfs integration. Docker doesn't have lxcfs integration even at the host level, so nested is unfortunately even worse.
