### ISSUE TITLE
Feature request: Disk quota for 'dir' backingstore (limits & guest info)

### ISSUE THREAD

**Issue by narcisgarcia** [lxc/lxcfs#277]
"simfs" in OpenVZ id the equivalent to LXC's "dir".
vzquota controls disk quotas for Virtuozzo/OpenVZ container.  These are per-container disk quotas set from Virtuozzo/OpenVZ host system.

What makes OpenVZ the difference to LinuXContainers in this?

Many system administrators do need to keep disk space overbooking (host free space share for containers), and let containers to release host space (on guest files removal) at same time: same effect as automatic VPS disk shrink.
This is possible using a single Ext4 filesystem for whole /var/lib/lxc with "dir" containers.
btrfs doesn't completely solve this, because containerized users don't see VPS quota as total disk space.

In an OpenVZ environment you can do this for a simfs (dir) container:
`vzctl set $ContainerID  --diskspace 100G --save`
then, inside container, guest users and programs see only 100GiB as disk space.
Just after this host space doesn't change:
`vzctl set $ContainerID  --diskspace 50G --save`
And just after guest removes files inside a container, host filesystem gains free space.

**Comment by stgraber** [comment]
We're planning on adding project quota support to LXD for XFS and EXT4. I don't know how statfs behaves with those, best case scenario the space is properly reported, worst case we may need to do some lxcfs trickery to report the right value (and possibly do the same for btrfs quotas)

**Comment by stgraber** [comment]
We've got project quota support in LXD now which will handle disk space quotas on ext4/xfs just fine and have the kernel properly report the usage.

**Comment by narcisgarcia** [comment]
Will this LXD project cover LXC-only containers?

**Comment by stgraber** [comment]
No, if you're using LXC directly, then you need to manually create the project quota using the `quota` command options and apply it to your container's rootfs. Then everything inside the container will behave properly.
