### ISSUE TITLE
Fake dmesg

### ISSUE THREAD

**Issue by Harvie** [lxc/lxcfs#279]
It would be nice to have some kind of dmesg filter that only passes messages related to the container cgroup. For example if i run out of memory in one of the containers, it triggers OOM and it's logged to dmesg. All other containers then see the OOM message in dmesg and inexperienced users think it's problem with their container... So it's kinda confusing.

**Comment by stgraber** [comment]
That's not something we can do with lxcfs. lxcfs can fake regular files on the filesystem, but dmesg is usually read through /dev/kmsg which is a character device.

Even if this was possible, it'd be quite difficult to do as the kernel log isn't structured so knowing what set of lines constitutes a message and then what container that belongs to is pretty much impossible.

The right way to fix this, but there has so far been little interest for it would be a logging namespace at the kernel level. I believe @hallyn looked into this quite a while back but it's not really been a priority so far and most seem to just disable dmesg access from inside containers.
