### ISSUE TITLE
no btime in /proc/stat when running with 160 cpus

### ISSUE THREAD

**Issue by raharper** [lxc/lxcfs#28]
On the p8 box, if I leave SMT=8 on, the host has 160 cpus. When I run ps aux in a container, it complains that there is no btime in /proc/stat output. If I disable SMT and have 20 cores, then btime shows up in the guest /proc/stat.

**Comment by hallyn** [comment]
Could you show what /proc/stat looks like with the 160 cpus (on native /proc)?

**Comment by raharper** [comment]
http://paste.ubuntu.com/11106313/

**Comment by hallyn** [comment]
Thanks - sorry for not asking for these together, but can you
also show /var/lib/lxcs/proc/stat in the same case?

I assume the whole file is simply cut short, but want to make
sure I've got the right idea.

**Comment by raharper** [comment]
it was cut short, but I've not recreated it  so /var/lib/lxcfs/proc/stat
looks sane now.  =(

ubuntu@diamond:~$ cat /var/lib/lxcfs/proc/stat
cpu  24413 119 25164 587859166 2524 1074 2038 0 19608 0
cpu0  347 0 485 4410354 578 33 258 0 0 0
intr 3578066 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 253354 3338 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 20 38875 15645 2147 1377 1083 15627 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 19 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 22967
ctxt 6567085
btime 1431478755
processes 5131
procs_running 1
procs_blocked 1
softirq 1561198 144 580312 8962 54718 61611 61753 3666 363905 2395 423732

**Comment by raharper** [comment]
ok, it reproduces; odd, inside it doesn't seem to be getting the lxcfs
mount version:

http://paste.ubuntu.com/11113475/

**Comment by hallyn** [comment]
I think this has gotten inadvertently fixed.  In xenial:

in container:
root@c1:~# wc !$
wc /proc/stat
168 3498 9090 /proc/stat

on host:
ubuntu@lxcfs1:~$ wc /proc/stat
168 3499 9092 /proc/stat

**Comment by hallyn** [comment]
Please reopen if you see this again.
