### ISSUE TITLE
LXCFS giving “unexpected cpu time:”

### ISSUE THREAD

**Issue by riddhiterminator** [lxc/lxcfs#283]
I have already posted query on ==> https://discuss.linuxcontainers.org/t/lxcfs-giving-unexpected-cpu-time/4858
Feel like I had posted on wrong place. So posting it here.

I am using `lxc 2.0.9` and for correct view of /proc I am using `lxcfs 3.0.0` on my custom hardware.
I am starting lxcfs in background and then starting lxc manually.

Out of 6 cpu cores, I have assign/shared four cores to my container via,
lxc.cgroup.cpuset.cpus = 2,3,4,5

My container is working fine , however I am seeing below logs on cosole.

`bindings.c: 4917: proc_stat_read: cpu2 from /lxc/Container has unexpected cpu time: 29173 in /proc/stat, 31975 in cpuacct.usage_all; unable to determine idle time`

Is this expected or something is wrong here ?
Why am I getting this logs ?

**Comment by aither64** [comment]
LXCFS is putting together CPU usage data from two sources: `/proc/stat` and the cpuacct cgroup, i.e. `cpuacct.usage_all`. These files are read at slightly different times, are using different units (USER_HZ vs ns) and possibly are accounted differently, so putting them together is really not that accurate, but I think it's the best we can do.

I've put in this warning just to show when the idle time cannot be calculated from data read from cpuacct. It's nothing fatal, idle time from `/proc/stat` is used in this case.

How frequently do you see this message?

**Comment by tssge** [comment]
Can confirm this on LXCFS 3.0.0

htop will randomly show 600% CPU usage on all processes when this happens

**Comment by yinhongbo** [comment]
lxcfs[987]: bindings.c: 4503: cpuview_proc_stat: cpu0 from / has unexpected cpu time: 265682 in /proc/stat, 286267 in cpuacct.usage_all; unable to determine idle time
I meet too. Is there a solution?

**Comment by stgraber** [comment]
Oh, this may be related to #284 then.
