### ISSUE TITLE
/proc/uptime unnecessarily truncates microseconds

### ISSUE THREAD

**Issue by blackboxsw** [lxc/lxcfs#292]
lxfs: 3.0.3-0ubuntu1

When looking at a /proc/uptime in a container microsecond granularity is automatically truncated to seconds. This makes it hard to properly calculdate start times of processes in microseconds relative to container start time. 

The code related to this truncation is:

bindings.c:proc_uptime_read:5061 which only attempts to represent uptime in seconds @
        total_len = snprintf(d->buf, d->buflen, "%"PRIu64".00 %"PRIu64".00\n", reaperage, idletime);

There are additional comments that describe the intent behind only using seconds as the granularity of get_reaper_age:

./bindings.c:get_reaper_age:~3991 
                /* We could make this more precise here by using the tv_nsec
                 * field in the timespec struct and convert it to milliseconds
                 * and then create a double for the seconds and milliseconds but
                 * that seems more work than it is worth.
                 */

```
# example from within the container
root@x1:~# cat /proc/uptime 
91622.00 91520.00

# on the host we do get more specific uptime
1031969.86 8152657.65
```

**Comment by hallyn** [comment]
Are you interested in writing a patch to increase the granularity?
