### ISSUE TITLE
single CPU appearing in cpuinfo when using limits.cpu.allowance in combination with multiple cores config

### ISSUE THREAD

**Issue by layer7gmbh** [lxc/lxcfs#298]
Hi, 

at very first, thank you for your time and effort in this project !

I will try to contribute a bit by reporting a little bug when cpuset and CFS quotas both are applied. In our case we set limits.cpu to 3 with the result:

`lxc exec lxc5703-3660 cat /proc/cpuinfo | grep processor`
processor : 0
processor : 1
processor : 2

which is showing the 3 cpu cores.
Then we added the allowance:

`lxc config set lxc5703-3660 limits.cpu.allowance 30ms/100ms`
`lxc exec lxc5703-3660 cat /proc/cpuinfo | grep processor`
processor : 0

which results in 1 cpu core to be shown. Same with other rendering applicaitons like top/atop/htop and so on.

While the self status seems to be ok:

`lxc exec lxc5703-3660 grep Cpus_allowed_list /proc/self/status`
Cpus_allowed_list: 1,4,8

This cause some applications to have trouble starting threads on different available cores because they think they are on a single core machine.

If it please you, we would be thankful if you could change this behaviour. So that we could assign multiple cores to a container and at the same time limit the cputime while not loosing the cpu count causing top and others to be unable to see all the cores.

Thank you very much !
Greetings
Oliver

**Comment by stgraber** [comment]
@aither64 thoughts on what should be done in such cases?

As we have software that's directly basing their threading behavior on the number of CPUs rendered in cpuinfo, the cpu quota handling code may end up causing some problems there.

Should we only restrict cpuinfo entries when no cpuset is at play too or is there something even more clever that we can do to indicate that you do have access to multiple CPUs and can run code concurrently but also that your amount of CPU time is limited.

**Comment by aither64** [comment]
I'd suggest adding a command line option to decide if cpu quotas should be used to restrict visible cpus  or not, because someone might want to use both. The default behaviour could be to use quotas only when cpuset matches online cpus, I guess. I'm not aware of any better way unfortunately.

**Comment by stgraber** [comment]
Ok, so let's got with adding a command line option to control this behavior then.

**Comment by stgraber** [comment]
Ok, so the plan here is something like a `--disable-cfs` option to turn off this particular bit.
At the same time, can you make `--help` a bit less crappy and also add long options for the existing flags?

I'd say we'd want:
 - `-f | --foreground`
 - `-d | --debug`
 - `-l | --enable-loadavg`
 - `-u | --disable-swap`
 - `--disable-cfs` (wouldn't make a short option for that)

Sounds good?
