### ISSUE TITLE
How to run two lxcfs seprately?

### ISSUE THREAD

**Issue by wavezhang** [lxc/lxcfs#299]
I have run lxcfs-2.0.6 for a long time, but it need update to lxcfs3 for the new feature. And I am planning to use a separate liblxcfs.so path and a separate lxcfs binary and  a new mount point. It works for a while. But I see some error logs like following:

> Aug 13 20:08:34 centos0 lxcfs3[2327]: 11: fd:  17: name=systemd
Aug 15 09:02:54 centos0 systemd[1]: lxcfs3.service: main process exited, code=killed, status=11/SEGV
Aug 15 09:02:54 centos0 systemd[1]: Unit lxcfs3.service entered failed state.
Aug 15 09:02:54 centos0 systemd[1]: lxcfs3.service failed.
Aug 15 09:02:54 centos0 systemd[1]: lxcfs3.service holdoff time over, scheduling restart.
Aug 15 09:02:54 centos0 systemd[1]: Stopped FUSE filesystem for LXC.

And I noticed that two lxcfs are using same RUNTIME_PATH. 
In order to run two lxcfs，would it be OK if I just change pidfile name？ do I need to recompile lxcfs to use a new RUNTIME_PATH ? Any thing else I need to do to make two lxcfs run normally?

**Comment by brauner** [comment]
Hm, you need a custom pidfile and that should probably work so long as you don't start two lxcfs instances at the exact same time.
But what you should really do is write a patch that uses a temporary directory for the `lxcfs/controllers` and `lxcfs/root` setup or temporary directories.
And also a patchset that lets LXCFS skip the cgroup emulation part when a suitable command line option is passed. This way this problem goes away too. :)

**Comment by wavezhang** [comment]
You mean  separate pidfile is enough if I can make sure two process would never run  at the exact same time?
new directory of ```lxcfs/controllers``` and ```lxcfs/root``` is only needed when two instance  run  at the exact same time?

**Comment by stgraber** [comment]
```
root@castiana:~# lxcfs -p /tmp/lxcfs.1.pid /mnt/lxcfs-1/ &
[1] 790396
root@castiana:~# mount namespace: 5
hierarchies:
  0: fd:   6: pids
  1: fd:   7: hugetlb
  2: fd:   8: memory
  3: fd:   9: freezer
  4: fd:  10: net_cls,net_prio
  5: fd:  11: devices
  6: fd:  12: blkio
  7: fd:  13: cpuset
  8: fd:  14: rdma
  9: fd:  15: cpu,cpuacct
 10: fd:  16: perf_event
 11: fd:  17: name=systemd
 12: fd:  18: unified

root@castiana:~# lxcfs -p /tmp/lxcfs.2.pid /mnt/lxcfs-2/ &
[2] 790473
root@castiana:~# mount namespace: 5
hierarchies:
  0: fd:   6: pids
  1: fd:   7: hugetlb
  2: fd:   8: memory
  3: fd:   9: freezer
  4: fd:  10: net_cls,net_prio
  5: fd:  11: devices
  6: fd:  12: blkio
  7: fd:  13: cpuset
  8: fd:  14: rdma
  9: fd:  15: cpu,cpuacct
 10: fd:  16: perf_event
 11: fd:  17: name=systemd
 12: fd:  18: unified

root@castiana:~# 
root@castiana:~# jobs
[1]-  Running                 lxcfs -p /tmp/lxcfs.1.pid /mnt/lxcfs-1/ &
[2]+  Running                 lxcfs -p /tmp/lxcfs.2.pid /mnt/lxcfs-2/ &
root@castiana:~# ls -lh /mnt/lxcfs-1
total 0
drwxr-xr-x 2 root root 0 Mar  3 11:52 cgroup
dr-xr-xr-x 2 root root 0 Mar  3 11:52 proc
root@castiana:~# ls -lh /mnt/lxcfs-2
total 0
drwxr-xr-x 2 root root 0 Mar  3 11:53 cgroup
dr-xr-xr-x 2 root root 0 Mar  3 11:53 proc
root@castiana:~# 
```

So there's no problem with lxcfs running multiple instances. The packaging/init scripts will usually have some expectations around the location of the mount and pid files, but if you're doing your own setup, it will work just fine.
