### ISSUE TITLE
lxcfs provides a blank /proc/meminfo when memory controller on host is unavailable

### ISSUE THREAD

**Issue by shinji257** [lxc/lxcfs#30]
When the kernel isn't supplying a memory controller on the host then lxcfs fails to provide a proper /proc/meminfo to the containers.  In this situation lxcfs should reflect the host values so that processes like procps and top can work properly inside the container.

These are situations where the memory controller may be unavailable.
The memory cgroup isn't compiled into the kernel being used at all
The memory cgroup functions are compiled in but are disabled at boot time (cgroup_disable=memory)
The memory cgroup functions are compiled in but are disabled by default at boot time

In the last 2 if you did lxc-checkconfig it may still report that the memory controller was enabled even though it was disabled either via default kernel configuration or boot time parameters.

In all cases doing a cat against /proc/self/cgroup confirms the memory controller is missing.

Examples of end result of current issue.
ProcPS can't report memory values.  It actually throws a FPE when it tries.
shinji@trusty-x86:~$ ps -o %mem
%MEM
Signal 8 (FPE) caught by ps (procps-ng version 3.3.9).
ps:display.c:66: please report this bug
Floating point exception

Top reports a value of inf (infinity) in the memory column.

Additional relevant information:
OS: Ubuntu 14.04.2
Using Ubuntu-LXC daily PPA
lxcfs:
  Installed: 0.7-0ubuntu2~ubuntu14.04.1~ppa1
  Candidate: 0.7-0ubuntu2~ubuntu14.04.1~ppa1
  Version table:
 *** 0.7-0ubuntu2~ubuntu14.04.1~ppa1 0
        500 http://ppa.launchpad.net/ubuntu-lxc/daily/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by hallyn** [comment]
Thanks, obviously the proc_read() functions need to detect when cgroup isn't found and fall back to returning the stock file in that case, rather than returning 0.  I'll write a patch to fix that tomorrow, unless there is a pull request for it tonight.
