### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by cao-hui** [lxc/lxcfs#306]
The memory occupied by lxcfs keeps increasing as it runs

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7512 root      20   0  751692   9996   1336 S   0.0  0.1  28:14.59 lxcfs  
```

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND            
 7288 root      20   0  833756  79028   1428 S   0.3  0.5 254:35.14 lxcfs    
```
Is there any memory leak in lxcfs or it's a normal phenomenon？

**Comment by stgraber** [comment]
What version is this?
Are you running it with expensive options like loadavg tracking?

**Comment by cao-hui** [comment]
> What version is this?
> Are you running it with expensive options like loadavg tracking?

The version  is 3.0.0 
and lxcfs started as
```
lxcfs -s -l -o allow_other /var/lib/lxcfs
```

**Comment by stgraber** [comment]
3.0.0 is pretty outdated, you should at least run the latest bugfix release for that series, 3.0.4

**Comment by cao-hui** [comment]
Is the above phenomenon related to the version of lxcfs? ( The latest Git commit ID of lxcfs I used is 037dd289 )

If I use the latest version of lxcfs like version 3.1.2 and everything is ok, how much memory will it probably take?

**Comment by stgraber** [comment]
Closing as this was on an outdated version and reporter didn't comment on this happening with more recent releases.
