### ISSUE TITLE
lxcfs man page on 0.7 appears to have been generated incorrectly

### ISSUE THREAD

**Issue by shinji257** [lxc/lxcfs#31]
Reproduction: man lxcfs
OS: Ubuntu 14.04.2 on Ubuntu-LXC daily ppa

Expected results: A man page about lxcfs that looks appropriate
Actual results: I think it is still a man page about lxcfs but it is titled "FAILED" instead.  I believe it generated improperly during compile time.

File contents (Note the FAILED title header and the failure/error messages mixed in the contents):
shinji@icarus:/usr/share/man/man1> zcat lxcfs.1.gz
.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.44.1.
.TH FAILED "1" "April 2015" "Failed opening dbus connection: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /sys/fs/cgroup/cgmanager/sock: No such file or directory" "User Commands"
.SH NAME
Failed \- Set up cgroup fs for containers
.SH DESCRIPTION

lxcfs implements a FUSE fs which allows containers to have virtualized
cgroup filesystems and virtualized views of /proc/cpuinfo and /proc/meminfo.
.PP
Usage:
.PP
\&./lxcfs [FUSE and mount options] mountpoint
.PP
WARNING: failed to escape to root cgroup
Failed opening dbus connection: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /sys/fs/cgroup/cgmanager/sock: No such file or directory
.SH "SEE ALSO"
cgmanager(1),
lxc(1)

**Comment by hallyn** [comment]
I believe this is fixed.
