### ISSUE TITLE
Support for shared PID namespace

### ISSUE THREAD

**Issue by 3XX0** [lxc/lxcfs#310]
Right now LXCFS depends on a PID namespace as it looks for the subreaper cgroups through `lookup_initpid_in_store`. This means it won't support things like `docker run --pid=host` or similar.

Could we add a mount flag or have an option to turn it off and always use the caller's pid to lookup the cgroup hierarchy?

**Comment by brauner** [comment]
Sure, not opposing this at all. Do you have a patch already?

**Comment by 3XX0** [comment]
Not yet, but I can make the patch as long as we agree on how to toggle it.

Should it be a mount option, or should we try to detect it automatically?

**Comment by brauner** [comment]
Automatic detection seems preferable to me.

**Comment by stgraber** [comment]
@3XX0 any progress on this?

**Comment by brauner** [comment]
Implemented in https://github.com/lxc/lxcfs/commit/c9236032f87c3d8f4be9a76e29fe1fd0c623bba2

**Comment by 3XX0** [comment]
Hey sorry I completely dropped the ball on this one.

I tried the patch, most of it works as expected.
However I still see some inconsistencies on things like `/proc/stat` and `/sys/devices/system/cpu/online`. 

I think this is because not all the checks have been patched:
```
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
cgroup_fuse.c:  if (initpid <= 1 || is_shared_pidns(initpid))
proc_cpuview.c: if (initpid <= 1 || is_shared_pidns(initpid))
proc_fuse.c:    if (initpid <= 1 || is_shared_pidns(initpid))
proc_fuse.c:    if (initpid <= 1 || is_shared_pidns(initpid))
proc_fuse.c:    if (initpid <= 0)
proc_fuse.c:    if (initpid <= 0)
proc_fuse.c:    if (initpid == 1) {
proc_fuse.c:    if (initpid <= 1 || is_shared_pidns(initpid))
proc_loadavg.c: if (initpid <= 1 || is_shared_pidns(initpid))
sysfs_fuse.c:   if (initpid <= 0)
```

Although it seems intentional in some cases?
```
/*
* when container run with host pid namespace initpid == 1, cgroup will "/"
* we should return host os's /proc contents.
* in some case cpuacct_usage.all in "/" will larger then /proc/stat
*/
if (initpid == 1) { 
      return read_file_fuse("/proc/stat", buf, size, d);                                                                      
}
```
