### ISSUE TITLE
Wrong idle time randomly appearing in /proc/stat

### ISSUE THREAD

**Issue by ebiiii** [lxc/lxcfs#311]
Following a discussion on the Proxmox forum, I'm opening the issue here as it seems related to lxcfs (https://forum.proxmox.com/threads/proc-stat-has-too-much-idle.59265/).

To summarize, it seems that sometimes the idle time value is getting to something like 10^18 (in the order of magnitude of the maximum of an unsigned long on 64bits) and stays constant. Thus making monitoring tools, like htop, believe that the CPU is 100% busy and never idle. From our observations over hundreds of containers, we have now a bit less than 50% of them that are affected, having at least one cpu reporting a wrong idle time, and sometimes more than one cpu.

We are running Proxmox 5.4, with the build of lxcfs from their repository: http://download.proxmox.com/debian/pve/dists/stretch/pve-no-subscription/binary-amd64/ version 3.0.3-pve1, which seems to be built from a snapshot of master from February 2019.

Here is a sample of running : `cat /proc/stat | grep "cpu "` inside a few containers:

```
cpu  10162498 0 0 1135120557 0 0 0 0 0 0
cpu  13337485 0 0 8317131874320235395 0 0 0 0 0 0
cpu  1091037 0 0 11732815868058135187 0 0 0 0 0 0
cpu  984963 0 0 284785536 0 0 0 0 0 0
cpu  1163008 0 0 15910903933238771776 0 0 0 0 0 0
cpu  3611741 0 0 11430588482391718183 0 0 0 0 0 0
cpu  11421149 0 0 1133482391 0 0 0 0 0 0
cpu  2947830 0 0 7666908213704610131 0 0 0 0 0 0
cpu  1026401 0 0 285293437 0 0 0 0 0 0
cpu  10235171 0 0 7598452630140695659 0 0 0 0 0 0
cpu  10216832 0 0 16181035045102515931 0 0 0 0 0 0
cpu  1772137 0 0 1144883582 0 0 0 0 0 0
cpu  10267558 0 0 4424062475040688088 0 0 0 0 0 0
cpu  1031294 0 0 4212112933404370785 0 0 0 0 0 0
cpu  975692 0 0 7453468611269178424 0 0 0 0 0 0
cpu  48816842 0 0 1091961237 0 0 0 0 0 0
cpu  8077355 0 0 5147085506 0 0 0 0 0 0
cpu  1157468 0 0 570024116 0 0 0 0 0 0
cpu  1052334 0 0 285170314 0 0 0 0 0 0
cpu  1126415 0 0 1143356976 0 0 0 0 0 0
cpu  2120711 0 0 4867504942 0 0 0 0 0 0
cpu  1185092 0 0 330692288688499736 0 0 0 0 0 0
cpu  1000288 0 0 7955942389543023664 0 0 0 0 0 0
cpu  2814379 0 0 4027685933726328606 0 0 0 0 0 0
cpu  1145146 0 0 1143943988 0 0 0 0 0 0
cpu  2832622 0 0 3468104267714643453 0 0 0 0 0 0
cpu  1112126 0 0 3776020056425540882 0 0 0 0 0 0
cpu  1120777 0 0 8170409803457372260 0 0 0 0 0
cpu  2189759 0 0 8390052218882221575 0 0 0 0 0 0
cpu  1155235 0 0 15338096684326571490 0 0 0 0 0
...
```
Let me know what additional information might be useful for you.

**Comment by brauner** [comment]
Puh, this should hopefully be fixed in current LXCFS master. Sorry it's been so long. If the issue still persists, please reopen.
