### ISSUE TITLE
Support for cgroup v2 controllers?

### ISSUE THREAD

**Issue by irnes** [lxc/lxcfs#313]
Are there any plans to fully support cgroup v2 controllers?

**Comment by brauner** [comment]
Yes, there is. But we won't be able to look into this soon.

This would make for a great contribution from the community imho.

**Comment by brauner** [comment]
This should be fixed now in master.

**Comment by irnes** [comment]
I checked out the latest changes and encountered the following issues. (OS: Gentoo)

- Service lxcfs fails to start on the system with legacy cgroup with the following error:
```
# /usr/local/bin/lxcfs -o allow_other,nonempty /var/lib/lxcfs
bindings.c: 696: cgfs_setup_controllers: Failed to set up private lxcfs cgroup mounts.
```
- Service lxcfs successfully starts on the same system when configured to use unified cgroup.
However there something suspicious in the following output when I try to list files:
```
# ls /var/lib/lxcfs/ -lah
ls: cannot access '/var/lib/lxcfs/cgroup': Input/output error
total 1.5K
drwxr-xr-x  2 root root  0 Feb 26 18:58 .
drwxr-xr-x 25  501   20 28 Nov 18 09:20 ..
??????????  ? ?    ?     ?            ? cgroup
dr-xr-xr-x  2 root root  0 Feb 26 18:58 proc
dr-xr-xr-x  2 root root  0 Feb 26 18:58 sys
```

**Comment by brauner** [comment]
On February 27, 2020 9:21:37 AM GMT+01:00, Irnes Mujkanovic <notifications@github.com> wrote:
>I checked out the latest changes and encountered the following issues.
>(OS: Gentoo)
>
>- Service lxcfs fails to start on the system with legacy cgroup with
>the following error:
>```
># /usr/local/bin/lxcfs -o allow_other,nonempty /var/lib/lxcfs
>bindings.c: 696: cgfs_setup_controllers: Failed to set up private lxcfs
>cgroup mounts.

That's odd and I'll look in a few.

>```
>- Service lxcfs successfully starts on the same system when configured
>to use unified cgroup.
>However there something suspicious in the following output when I try
>to list files:
>```
># ls /var/lib/lxcfs/ -lah
>ls: cannot access '/var/lib/lxcfs/cgroup': Input/output error
>total 1.5K
>drwxr-xr-x  2 root root  0 Feb 26 18:58 .
>drwxr-xr-x 25  501   20 28 Nov 18 09:20 ..
>??????????  ? ?    ?     ?            ? cgroup
>dr-xr-xr-x  2 root root  0 Feb 26 18:58 proc
>dr-xr-xr-x  2 root root  0 Feb 26 18:58 sys
>```

That's fine. Virtualizing the cgroup filesystem itself is not supported. But that doesn't have any impact on the cgroup part that is needed to virtualize various proc files.

**Comment by irnes** [comment]
The issue with cgroup mounts is no more present with the latest code. Thanks

**Comment by luodw** [comment]
> The issue with cgroup mounts is no more present with the latest code. Thanks

hello, which version do you use? I use the latest version 4.0.5 and in env(debian 9 + kernal 5.4 + cgroupv2),  cgroup mount still err, show as follow
![image](https://user-images.githubusercontent.com/14847074/89713124-325f1480-d9c8-11ea-892b-8368a22e0e96.png)

**Comment by stgraber** [comment]
I expect the `cgroup` dir to be unavailable/broken on cgroup2 only systems but that shouldn't prevent you from using lxcfs as a kernel that's recent enough to provide cgroup2 is also recent enough to provide cgroup namespaces and so making that particular feature irrelevant.

**Comment by mdione-cloudian** [comment]
> a kernel that's recent enough to provide cgroup2 is also recent enough to provide cgroup namespaces

But that mostly depends on the distro mounting those, which seems toi have changed between Ubuntu 21.04 and 21.10:

```
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
```

vs 

```
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
```

is this difference covered by the current code?

**Comment by mdione-cloudian** [comment]
I had to boot with `systemd.unified_cgroup_hierarchy=0` and now it's working again.
