### ISSUE TITLE
Memory usage through the roof. 

### ISSUE THREAD

**Issue by rewolff** [lxc/lxcfs#317]
My Raspberry pi running Ubuntu uses LXCFS. The raspberry regularly runs out of memory, so I started investigating. 

The top memory-using program is LXCFS. It is using 15% of my total RAM in my system. This is outrageous for "just another deamon". There are tens of deamons that need to run on a simple deamon of each of them uses 1/6th of total physical memory we will get the windows-bloat and slowness that I hope to avoid by using Linux. 

> root       296  0.0  0.0 298460  1688 ?        Ssl  Feb07   0:02 /usr/bin/lxcfs /var/lib/lxcfs/

**Comment by stgraber** [comment]
What version of LXCFS is that?

**Comment by rewolff** [comment]
Ehh. The machine that this is about is currently "off". It was running Ubuntu 18.04 for raspberry pi.

**Comment by stgraber** [comment]
Ok and those have a similar memory leak issue?

**Comment by rewolff** [comment]
You asked for the version of lxcfs. I didn't know of a way to get you that information (quickly) other than looking on another Ubuntu 18.04 system. In my experience, such program versions stay the same across a released Ubuntu version, independent of the architecture. 

I just checked two other Ubuntu-18.04 systems and they don't run lxcfs automatically. 

Let me add that I don't know what lxcfs does and that I don't really care that there are 10 or 20 deamons running on my system that I don't precisely know the reason for. I used to know that, but I've given up caring.  However I start caring (*) about it when it is using a significant portion of my system resources. 

(*) Often not enough to go and figure out what it does, but sometimes enough to write a bugreport.

**Comment by stgraber** [comment]
Looking at your output again, LXCFS only shows 1.6MB of resident memory usage.
The other number is the virtual address space that was allocated, this one can effectively be ignored, a lot of software will have rather large maps but not much used memory in practice.

So when debugging out of memory conditions, I'd strongly recommend looking at resident memory usage (RSS/RES) and not the virtual memory usage.

As an example on my laptop, the top RSS user is Firefox at 400MB.
While the top VIRT user is some graphical rendering process at 26.4GB.

It's worth noting that my laptop only has 16GB of RAM and there's no problem there whatsoever, virt can and almost always will far exceed the amount of memory you actually have.

**Comment by stgraber** [comment]
`top -o RES` vs `top -o VIRT` will show the difference quite easily.

**Comment by rewolff** [comment]
Looking at my output again..... your right. Sorry for wasting your time.
