### ISSUE TITLE
guest_nice CPU stats missing in /proc/stat

### ISSUE THREAD

**Issue by adamaflynn** [lxc/lxcfs#35]
/proc/stat in a container has 1 column fewer on CPU entries than on the host under Linux 3.13. It looks like (since Linux 2.6.33), that column is guest_nice. 

Looking at lxcfs.c:proc_stat_read(), it looks like guest_nice isn't included under any codepath.

Impact I've noticed from this is running top in a container fails with "top: failed /proc/stat read". I'm guessing this is related to guest_nice missing.

**Comment by hallyn** [comment]
I do see one fewer column, but top isn't failing for me (in a wily container on 4.2.0).  Which distro/release is in the container?

Would you be able to provide a patch to add the last column when it is available (without breaking the case where it is not)?

**Comment by adamaflynn** [comment]
I'm running Precise (12.04.5) container with top version 3.2.8. 

Patch looks simple enough, but I don't have a pre-2.6.33 environment to test in, so the blocker is finding the time to build one and verify backwards-compatibility. If I find time to patch & test, I'll send a PR.

**Comment by hallyn** [comment]
Uh, don't worry about pre-2.6.33.

**Comment by lege** [comment]
I don't see the difference after i limit  the cpuset.cpus, I don't know why???
