### ISSUE TITLE
Don't mess with containers that don't have /sys/fs/cgroup configured

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxcfs#39]
Hello, into /usr/share/lxcfs/lxc.mount.hook:
Don't mess with containers that don't have /sys/fs/cgroup configured
Why I need open a file to see that's?
Maybe more info into README?
Cheers,

**Comment by hallyn** [comment]
What do you mean by containers that don't have /sys/fs/cgroup configured?  That would only happen if sys wasn't mounted at all.  In which case you should not include the lxcfs hooks in your container configuration.  I'm not sure there's anything lxcfs should be doing differently.  Closing this issue, but please feel free to comment/reopen if you have a specific suggestion for what lxcfs should do differently.
