### ISSUE TITLE
Compile lxcfs on centos7 failed

### ISSUE THREAD

**Issue by zhanghuanzhong** [lxc/lxcfs#41]
when I try to compile  lxcfs on centos7,met the problem:

configure: error: Package requirements (libnih >= 1.0.2) were not met:
No package 'libnih' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables NIH_CFLAGS
and NIH_LIBS to avoid the need to call pkg-config.

However,I have make&make install the libnih(v1.0.2) on my server.

Would you help me?

**Comment by hallyn** [comment]
Hm, this is simply done using 

PKG_CHECK_MODULES([NIH], [libnih >= 1.0.2])

What does

pkg-config --libs libnih

show?

Note that I'll be switching this to not using libnih soon (to enable
threading), so if you'd like to just wait a month you should be able
to build without libnih.

**Comment by zhanghuanzhong** [comment]
@hallyn , Thanks for your reply.

as the "pkg-config --libs libnih" show, I set the PKG_CONFIG_PATH , and the problem has solved.

BTW, looks forward the new  lxcfs(enable threading)
