### ISSUE TITLE
[Debian] Do you have a scheduled 3.0.5 release?

### ISSUE THREAD

**Issue by P-EB** [lxc/lxcfs#419]
Hi,

Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955499 mentions an issue fixed in your stable branche for LXC 3.

Do you have a plan to release a 3.0.5 version of LXCFS at some point? I'd be glad to include the fix in Debian without making a custom patch!

Cheers!

-- 
PEB

**Comment by stgraber** [comment]
We usually like to have more than one commit in between bugfix releases :)

**Comment by P-EB** [comment]
Ack, so no timeline yet?

**Comment by stgraber** [comment]
Nope. We do expect to do one last bugfix round of releases for 3.0 before going for security fixes only but that's mostly held up by the LXD side which needs some work to make 3.0 buildable on modern systems.
