### ISSUE TITLE
mount cgroup dir err when in kernal 5.4 and cgroupv2

### ISSUE THREAD

**Issue by luodw** [lxc/lxcfs#424]
hello, we use lxcfs to enhance the virtualization capabilities of docker containers. My env is: debian 9 + 5.4 kernal + cgroupv2。When i run 'lxcfs /opt/test', i come across a problem, as below shows
![image](https://user-images.githubusercontent.com/14847074/89531079-39e4b900-d822-11ea-8d14-38c7e73fc9cb.png)

i read the lxcfs code, but can not find where mount the cgroup.  i find lxcfs will mount cgroup in /run/lxcfs/controllers/sys/fs/cgroup, so i hava no idea why cgroup is mounted incorrectly.

**Comment by luodw** [comment]
> hello, we use lxcfs to enhance the virtualization capabilities of docker containers. My env is: debian 9 + 5.4 kernal + cgroupv2。When i run 'lxcfs /opt/test', i come across a problem, as below shows
> ![image](https://user-images.githubusercontent.com/14847074/89531079-39e4b900-d822-11ea-8d14-38c7e73fc9cb.png)
> 
> i read the lxcfs code, but can not find where mount the cgroup. i find lxcfs will mount cgroup in /run/lxcfs/controllers/sys/fs/cgroup, so i hava no idea why cgroup is mounted incorrectly.

I find, the error is raised by https://github.com/lxc/lxcfs/blob/master/src/cgroup_fuse.c#L526, 
![image](https://user-images.githubusercontent.com/14847074/89713975-034ba180-d9ce-11ea-9ee2-8eb0541a84cf.png), so the cgroup dir is not necessary?

**Comment by stgraber** [comment]
It is not, it's only needed on old kernels that predate cgroup namespacing. If your kernel is recent enough to provide cgroup2, it's also recent enough not to need this in the first place.

**Comment by luodw** [comment]
thank you for your reply. i find even in cgroupv1,  lxcfs use the cgroup  in the '/run/lxcfs/controllers/', not in fuse directory. so what is the purpose of the cgroup dir in fuse dir?

**Comment by luodw** [comment]
> It is not, it's only needed on old kernels that predate cgroup namespacing. If your kernel is recent enough to provide cgroup2, it's also recent enough not to need this in the first place.

thank you for your reply. i find even in cgroupv1, lxcfs use the cgroup in the '/run/lxcfs/controllers/', not in fuse directory. so what is the purpose of the cgroup dir in fuse dir?

**Comment by luodw** [comment]
> > It is not, it's only needed on old kernels that predate cgroup namespacing. If your kernel is recent enough to provide cgroup2, it's also recent enough not to need this in the first place.
> 
> thank you for your reply. i find even in cgroupv1, lxcfs use the cgroup in the '/run/lxcfs/controllers/', not in fuse directory. so what is the purpose of the cgroup dir in fuse dir?

i read the code, this is my thought: is the fuse cgroup dir used to do the job as cgroup namespace do? so the fuse cgroup dir should also mount into container. As cgroupv2 support cgroup namespace, so the fuse cgroup dir is not needed. is it right?

**Comment by stgraber** [comment]
Correct

**Comment by luodw** [comment]
> Correct

thanks, one last question，why lxcfs should  mount cgroup controllers in '/run/lxcfs/controllers/'?  why not use /sys/fs/cgroup directly in host?  '/run/lxcfs/controllers/' is in a private mount namespace, why lxcfs can find the cgroup hierarchies in '/run/lxcfs/controllers/'?

**Comment by stgraber** [comment]
lxcfs wants to be able to mount the controllers regardless of whether your system has them mounted already and regardless of how they may have been mounted.

This allows lxcfs to work on a very wide variety of distributions and init systems.

**Comment by luodw** [comment]
> lxcfs wants to be able to mount the controllers regardless of whether your system has them mounted already and regardless of how they may have been mounted.
> 
> This allows lxcfs to work on a very wide variety of distributions and init systems.

but the cgroup of any containers(include already existed and new add) is in the cgroup in host mount namespace, how the private mount namespace(/run/lxcfs/controllers/) knows the container cgroup? i see the mount namespace doc, child mount namespace is isolated with parent mount namespace.

**Comment by stgraber** [comment]
The content of the cgroups remains identical

**Comment by luodw** [comment]
@stgraber Hi, Is lxcfs now support cgroupv2?  I run lxcfs(version: v4.0.12) in cgroupv2 env, the cgroup dir is empty.

**Comment by stgraber** [comment]
The cgroup dir exists for systems that predate the cgroup namespace. To my knowledge there are no systems which run on cgroup2 only and don't support cgroup namespaces.

**Comment by luodw** [comment]
> The cgroup dir exists for systems that predate the cgroup namespace. To my knowledge there are no systems which run on cgroup2 only and don't support cgroup namespaces.

Thanks for your reply, I run lxcfs with directory `/var/lib/lxcfs` in cgroupv2 machine, but `/var/lib/lxcfs` shows as follow
![image](https://user-images.githubusercontent.com/14847074/162472239-9e0717a9-b880-4c70-adb6-c89b05d53543.png)
Is anything wrong?

**Comment by stgraber** [comment]
Yeah, the /sys output looks wrong, any error in the lxcfs output?

**Comment by luodw** [comment]
> As mentioned earlier `/cgroup` being empty on cgroup2 is perfectly normal. `/sys` failing however isn't.
> 
> Can you run `strace -f -p PID-OF-LXCFS` and then attempt to access the `sys` directory again to see what may be going on.

ok, it looks like
![image](https://user-images.githubusercontent.com/14847074/162475532-3eeaec82-cc8e-457f-9b1e-4502c61af376.png)

**Comment by luodw** [comment]
@stgraber I use different compile machine, `/sys` looks ok, maybe my compile env is not  ok.

**Comment by stgraber** [comment]
I'd need to see the few pages prior to that `write` entry as that just shows the error being sent to the user, it doesn't show what actually led to the error.
