### ISSUE TITLE
CPU number seems not correct

### ISSUE THREAD

**Issue by julyclyde** [lxc/lxcfs#433]
I'm using stable-4.0 branch (signed 4.0.5) in a Kubernetes environment.
Kubelet assigned No. 8,9,24,25 cores to a container.

/sys/devices/system/cpu/online gives the correct answer:
```
# cat /sys/devices/system/cpu/online
8-9,24-25
```
and, lspci command (it has access to /sys/devices/system/cpu/present and knows the complete list of CPU cores):
```
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   8,9,24,25
Off-line CPU(s) list:  0-7,10-23,26-31
Thread(s) per core:    0
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2101.000
BogoMIPS:              4191.41
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              11264K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
```
but /proc/cpuinfo differs:
```
# egrep 'processor|^physical|^core|^apic|^$' /proc/cpuinfo
processor       : 0
physical id     : 1
core id         : 0
apicid          : 16

processor       : 1
physical id     : 1
core id         : 1
apicid          : 18

processor       : 2
physical id     : 1
core id         : 0
apicid          : 17

processor       : 3
physical id     : 1
core id         : 1
apicid          : 19
```

It has only No.0 to No.3 CPU cores in /proc/cpuinfo .
It's confusing. Is this expected?

**Comment by julyclyde** [comment]
It would fail when some script uses /proc/cpuinfo as reference information to call taskset, because taskset respects 8,9,24,25 numbers.

**Comment by stgraber** [comment]
That's expected as we've seen that not having sequential processor numbers in /proc/cpuinfo tends to break more things than the few which use it as input for taskset or cgroups (most tools that perform pinning will use sysfs or a syscall to retrieve the available set).

**Comment by julyclyde** [comment]
Thank you for explaination.
