### ISSUE TITLE
Is it normal CPU spike this high? 

### ISSUE THREAD

**Issue by cmingxu** [lxc/lxcfs#446]
All, I want give lxcfs4.0.7 a performance test before run it into production, I run 50 containers with command line 
```
 while true; do cat /proc/cpuinfo ; cat /proc/meminfo ;cat /proc/stat ;cat /proc/uptime ;cat /proc/diskstats ; cat /proc/swaps ; done
```

lxcfs process CPU usage reached to 270%
```
592158 root      20   0 9575536  36104   1728 S 270.2   0.0  61702:19 lxcfs
```
from top command outout.

 strace -f -c -p $(pidof lxcfs)
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 48.35  133.058505         562    236669           read
 14.77   40.639171        2375     17106      3784 futex
  8.65   23.809157         335     70900      1125 openat
  8.30   22.836582         327     69739           close
  5.29   14.556593         326     44533           fstat
  4.67   12.846168         339     37886           writev
  3.82   10.514954    10514954         1           restart_syscall
  3.26    8.975215         327     27445           fcntl
  2.01    5.520780         346     15947           stat
  0.57    1.568901         346      4526           getdents64
  0.15    0.403660         358      1127           clock_gettime
  0.04    0.117757         212       554           rt_sigprocmask
  0.04    0.107212         388       276           madvise
  0.02    0.060401         397       152           munmap
  0.02    0.057156         206       277           set_robust_list
  0.02    0.053630         193       277           clone
  0.01    0.036908         172       214           mprotect
  0.01    0.026891         138       194           mmap
------ ----------- ----------- --------- --------- ----------------
100.00  275.189641                527823      4909 total
```

I want to know is this normal or not? any idea how can make it better performance?

**Comment by ZhangZhenhua** [comment]
Same issue here. 

There is a monitoring job running besides apps in container. The lxcfs CPU usage is really **HIGH.**

Any updates?

**Comment by stgraber** [comment]
Yes, opening files in a tight loop is going to cause LXCFS to similarly have to open parse and return files in a tight loop too, burning a lot of CPU in the process.

**Comment by ZhangZhenhua** [comment]
@stgraber Thanks for your reply. 

Is there any plan to improve this situation? For example, adding a cache layer in the user space to avoid the open-read-parse-return cycle in about 10s period(10s is the typical period of a monitoring cycle). This will lose some accuracy for sure. However, as the userspace/kernel data path can't be modified, I don't know how much performance we can gain.

What's your opinion?

**Comment by stgraber** [comment]
I doubt that we'd want to try to do caching. Knowing who the cache would be valid for would be quite tricky and if we make it PID-specific then it would have very little use. Not to mention, caching information for proc files is usually a bad idea as there are many tools that very much want the data refreshed every second or so (think top/htop) and will be very unhappy if part of their information is cached and the rest isn't (as would happen here since lxcfs only covers a few files in proc).

**Comment by ZhangZhenhua** [comment]
OK. Get it. We may let the apps querying /proc or /sys less aggressively to reduce CPU usage.

**Comment by stgraber** [comment]
Yeah, that's really your best bet. We usually recommend running strace on lxcfs to see what files are constantly accessed and looking at the PID which shows up in the trace you can figure out what container and process is the culprit.

We don't really expect to be able to do much about performance, FUSE is slow and proc/sys aren't particularly fast themselves, so just fetching all the data can take some time. The actual computation on the data is trivial (simple math) so it's almost never LXCFS itself using the CPU so much as waiting for syscalls to return.

Over the years there have been many attempts to move more of that stuff in the kernel. We're still hopeful that one day part of /proc will be natively cgroup aware and we can start phasing out lxcfs. It's always been meant as a userspace workaround for something that the kernel doesn't do and at least historically had no intention of doing.

**Comment by ZhangZhenhua** [comment]
Agreed. The container may be the most popular way to run  modern applications, thus proc should be cgroup aware.
