### ISSUE TITLE
Reading files can result in zero data being returned to client (very low frequency)

### ISSUE THREAD

**Issue by sparlane** [lxc/lxcfs#450]
With lxcfs 4.0.7 and fuse3 or fuse2:
Somewhere between 1 in 1000 and 1 in 5000 reads of /proc/cpuinfo inside a container results in no data being read (i.e. the file appears empty)

from tracing this we can see that the kernel thinks 4k of file data was received from lxcfs, and then it asks for the next block of data, which confuses lxcfs which sends 0 bytes and then the client only gets zero bytes.

linux: 5.10.9 (later versions from this LTS also tested)
fuse: 3.2.2 (also tested 2.9.7)

I suspect this is caused by the over reporting of file size from: 25982f5d7e008e6ad13df28af3006ab8286f4c97

**Comment by Blub** [comment]
While I have not investigated this directly, this sounds very similar to an issue I ran into today with fuse3 specifically, where fuse3 seems to ignore the size we return on `read()` and and takes the value it *previously* got from *stat* instead as an upper bound.
This is IMO a bug in fuse assuming that returning using some random outdated size value makes more sense than what we actually return *now*. This is simply wrong.
However, I did not have this issue with fuse2, or at least it did not happen for the file I was debugging this with (`/proc/stat`), where the `st_size` value comes from scanning the host's `/proc/stat` which, after a formatting fix, just happened to have always been a byte shorter than the in-container one, cutting off the newline, which I just noticed when testing via `cat`.

If fuse2 really is also affected in a similar manner I fear that's another reason for me to believe that we need to move to low-level fuse at some point.

I'll need to try to reproduce this.

**Comment by mihalicyn** [comment]
With FUSE3 we discovered this bug recently https://github.com/lxc/lxcfs/pull/568 so it may be related to this problem.
But if you have FUSE2 stable reproducer please feel free to share I can help with debugging the kernel side and fuse side.
