### ISSUE TITLE
cpu0 usage exceeds 100%

### ISSUE THREAD

**Issue by huweihuang** [lxc/lxcfs#452]
lxcfs version 3.1.2 

CPU0 usage exceeded 100%.

the data source is /proc/stat
cpu_total=user+nice+system+idle+iowait+irq+softirq
cpu_used=user+nice+system+irq+softirq

**Comment by stgraber** [comment]
Can you try to reproduce this on current 4.0.x?

Also such usage may be normal if lxcfs is being hammered from within a container, so you may want to strace it to see if it's just responding to requests in a loop.
