### ISSUE TITLE
Allow custom FUSE arguments

### ISSUE THREAD

**Issue by hailin84** [lxc/lxcfs#454]
Hello, we are trying to run android in docker, with selinux enabled. We using lxcfs for resource seperate.
We found that files like /var/lib/lxcfs/proc/stat have selinux security label system_u:object_r:fusefs_t:s0, we hope to change it  to u:r:proc_stat:s0 or some other label.

Is that possible? Thanks.

**Comment by stgraber** [comment]
Did you find a way to do it?
I'm not familiar with what FUSE may allow at that level. It feels unlikely to be easy for a FUSE filesystem to do as that would allow anyone on the system to fake any labels which presumably SELinux wouldn't want :)

**Comment by hailin84** [comment]
@stgraber lxcfs just prevents options(-o) except nonempty, and those options supposed to be used on mounting file systems(check system call mount). So I made a little bit change, just on file lxcfs.c, let options go pass to mount. Luckily, it works. Run like this:
./lxcfs -o nonempty,context=u:object_r:proc_cpuinfo:s0 /var/lib/lxc/01
./lxcfs -o nonempty,context=u:object_r:proc_stat:s0 /var/lib/lxc/02

It's quite simple. Thanks.

**Comment by hailin84** [comment]
@stgraber If you plan to support it, maybe I can submit a pull request.

**Comment by brauner** [comment]
> Yeah, so I'd expect `-o` to allow you to set additional options on top of our default set. The current logic looks a bit more complicated than I think it needs to be.

The logic stems when fuse had a few bugs so we had to make sure that some options were simply not used plus there were some backwards compat quirks that we had to account for.

> 
> I think we should have a default list of `-o` arguments for both FUSE3 and other versions and then append whatever the user specifies on top of that, then iterate through that list to remove duplicates (apparently that's the reason for our current logic, duplicates confuse some versions of fuse) and finally override the argument with the resulting `-o`'.
> 
> @brauner does that sound good to you?

Sounds good to me.

> If so, then we'd definitely welcome a PR to sort this out, making it possible to pass `-o nonempty,context=...` to lxcfs and getting the expected result.

**Comment by hailin84** [comment]
@brauner @stgraber I just submitted a PR. Please check it. Thanks.
