### ISSUE TITLE
bad mount point

### ISSUE THREAD

**Issue by minlearn** [lxc/lxcfs#459]
1,/var/lib/lxcfs exists
2,/sys/fs/cgroups exists and contents are regluar

in systemctl status lxcfs.service,there are:

bad mount point /var/lib/lxcfs

**Comment by stgraber** [comment]
What version of LXCFS, on what kernel, does it actually end up running (see `ps aux` output), can you show `ls -lh /var/lib/`?

**Comment by minlearn** [comment]
debian buster 4.19.0-14,lxcfs version:4.0.6
yes,no lxcfs process in ps aux results
the /var/lib/lxcfs did exists,the lxcfs directory are empty,no contents
------
it is worth to mention that: i use lxcfs in an aufs chrooted rootfs /

**Comment by stgraber** [comment]
Anything in `dmesg`?

It could be that aufs is making fuse unhappy somehow.

**Comment by minlearn** [comment]
below is the mini-journalreader output:

> May 06 12:36:32 tinydebianlive kernel: new mount options do not match the existing superblock, will
>  be ignored

(but i googled it,some said this is a common warning,which can be safely ignored)
.....

> May 06 12:36:32 tinydebianlive lxcfs[670]: fuse: bad mount point `/var/lib/lxcfs': No such file or 
> directory

(this i explained as above,the /var/lib/lxcfs did exists)

**Comment by minlearn** [comment]
i setup the aufs fs with dio and xino options

**Comment by stgraber** [comment]
Can you try running (as root) `lxcfs -f -d /var/lib/lxcfs` ?

**Comment by minlearn** [comment]
i setup the aufs fs with dio and xino options

**Comment by minlearn** [comment]
lxcfs -f -d /var/lib/lxcfs

remain failure above

**Comment by stgraber** [comment]
Got your link to poke at the system, thanks.

This definitely looks like a kernel issue with aufs. The reason why I'm saying that is that lxcfs fails with that FUSE error only if the directory you're passing it doesn't exist in the aufs underlay.

 - lxcfs -f /mnt/a => fails with "No such file or directory"
 - lxcfs -f /mnt => Works fine
 - lxcfs -f /var/lib/lxcfs => fails

Of those 3, only /mnt is likely to have excited in your aufs underlay. This behavior indicates a kernel bug, actually one bad enough that it could potentially be used as the basis for a security issue (something running on the overlay shouldn't be able to tell what came from the underlay vs what was created in the overlay).

**Comment by minlearn** [comment]
lxcfs -f /mnt => Works fine
i dont think this is true
1,none cgroup files was generated under /mnt
2,no success message show in the output produced by -d option

**Comment by stgraber** [comment]
Closing this one as it's clearly an issue with the host system or kernel which is causing some major confusion for fuse.

**Comment by minlearn** [comment]
problem solved
@stgraber you are right, in systemd+aufs systems,/var/lib/lxcfs should be in the inital branch(or any branch?) of a aufs tree in advance,,so that later in systemd system it can take effects.
