### ISSUE TITLE
Using cat on /proc/cpuinfo inside a container produces an invalid argument error

### ISSUE THREAD

**Issue by BillyMorgan** [lxc/lxcfs#47]
Just ran across this problem when running ansible against a container I had created.

I have a workaround for my particular case by setting 'gather_facts: false' in my ansible config but just thought I'd let you guys know.

Let me know what other info would be useful for debugging.

**Comment by hallyn** [comment]
Hi,

can you test with the latest ad say whether it still breaks?

If it does, please tell us (a) what exactly is reporting invalid argument (cat, lxcfs itself, what), what does strace of cat.  I'll probably end up asking you for strace output of lxcfs itself.
