### ISSUE TITLE
does lxcfs support containerd

### ISSUE THREAD

**Issue by xiaods** [lxc/lxcfs#470]
I only have seen more tutorials abt docker runtime. But now contained is the standard engine. please give some Infos for the case.

**Comment by stgraber** [comment]
The question should really be the other way around :)

There is nothing in lxcfs that's specific to a particular runtime, it really all depends on whether your runtime of choice supports bind mounting stuff over /proc and /sys.

**Comment by stgraber** [comment]
Closing as there doesn't appear to be anything for us to fix in LXCFS.
