### ISSUE TITLE
In the readme, the package name written by the yum command is wrong.

### ISSUE THREAD

**Issue by moweiraul** [lxc/lxcfs#478]
wrong:
yum install fuse fuse-lib fuse-devel 

right:
yum install fuse _**fuse-libs**_ fuse-devel 

And in some systems, I found that the compilation depends on **fuse3** instead of **fuse**. 
For example:centos8

**Comment by stgraber** [comment]
Could you send a pull request updating the README?

**Comment by moweiraul** [comment]
> Could you send a pull request updating the README?

Yes,I already sent.

**Comment by stgraber** [comment]
Thanks!
