### ISSUE TITLE
Header files and compilation issues

### ISSUE THREAD

**Issue by ysysljjyjq** [lxc/lxcfs#480]
I am using lxcfs, but I encountered some difficulties while learning its source code and design philosophy.
1. In the master branch, I cannot find the header file `#include"config.h"`. And almost all files under `src` refer to this header file.
2. `src/lxcfs.c` calls a large number of `dlsym` functions to dynamically search for functions in this warehouse, such as the process of `do_proc_read` obtaining and calling `proc_read`. This is confusing.
3. In the section about build in the README.md file of the master branch, neither `./bootstrap.sh` nor `./configure` are in the master branch. These files exist in stable4.0 (although I did not run them). Is the README.md file of the master branch not updated in time?
4. I apply lxcfs to the docker container. When I run the container for more than a certain period of time (5-6 days) and look for the mount point in the container (using `mount`), I found repeated mounting information  such as `"lxcfs on /var/lib/lxc/lxcfs type fuse.lxcfs..." `  (maybe thousands). I forcibly `umount` lxcfs (it shows that this operation was successful), but the mount information cannot be reduced. I don’t know why it appears. Maybe someone can provide me with a way to locate the problem?

Can someone with good intentions answer these questions for me?

**Comment by brauner** [comment]
> I am using lxcfs, but I encountered some difficulties while learning its source code and design philosophy.
> 
> 1. In the master branch, I cannot find the header file `#include"config.h"`. And almost all files under `src` refer to this header file.

The master branch has switched from autotools to meson which makes for a way nicer build experience. To compile LXCFS on master you should install meson at least version `0.46`. If your distro doesn't provide a new enough version you can use:

```
pip3 install meson==0.55.1 ninja
```

the it's just a matter of:
```
meson setup -Ddebug=true -Dtests=true -Dinit-script=systemd build/
meson compile -C build/
```

The setup step will also generate the config.h header same as autotools would have.

> 2. `src/lxcfs.c` calls a large number of `dlsym` functions to dynamically search for functions in this warehouse, such as the process of `do_proc_read` obtaining and calling `proc_read`. This is confusing.

Seems more of a comment than a question.

> 3. In the section about build in the README.md file of the master branch, neither `./bootstrap.sh` nor `./configure` are in the master branch. These files exist in stable4.0 (although I did not run them). Is the README.md file of the master branch not updated in time?

Ah, I forgot to update that when we switched to meson. I'll send a patch in a bit.

> 4. I apply lxcfs to the docker container. When I run the container for more than a certain period of time (5-6 days) and look for the mount point in the container (using `mount`), I found repeated mounting information  such as `"lxcfs on /var/lib/lxc/lxcfs type fuse.lxcfs..." `  (maybe thousands). I forcibly `umount` lxcfs (it shows that this operation was successful), but the mount information cannot be reduced. I don’t know why it appears. Maybe someone can provide me with a way to locate the problem?

Did LXCFS on the host crash or did get restarted by something?

**Comment by ysysljjyjq** [comment]
Thank you very much for your prompt response! I tried successfully compiling config.h in the build directory using the meson command you provided. The process is really simple, and it automatically generates the corresponding variables for different systems. But like the cmake, it added to my learning costs, and yet I did learn something. I'm going to learn the lxcfs code.

> Did LXCFS on the host crash or did get restarted by something?

On issue 4, I do think lxcfs crashes and reboots multiple times. The lxcfs may be restarted repeatedly due to some reasons, and the mount point information is not deleted after the restart. But I don't know how to locate the cause. Maybe the lxcfs has a dedicated log to view, or run the journalctl command to view log information (I started the lxcfs through the systemctl command). If so, please let me know. Thank you!
