### ISSUE TITLE
Incorrect cpu idle time in /proc/stat when cpu.cfs_quota_us=-1

### ISSUE THREAD

**Issue by phanhuy1502** [lxc/lxcfs#500]
### Summary

- When a container uses cpu.cfs_quota_us=-1, the cpu idle time shown in /proc/stat is strange. (No increase even if cpu is free, or even decrease)

### Reproduce

- Issue observed on the current master branch (https://github.com/lxc/lxcfs/commit/6e764f329aa50bfb86dfa5fb29d64a3c22f5d41d)

```bash
# launch a docker container with `--cpuset-cpus 1 --cpu-quota -1`
docker run --rm -it -m 256m --cpuset-cpus 1 --cpu-quota -1 \
  -v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
  -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw  \
  -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw  \
  -v /var/lib/lxcfs/proc/stat:/proc/stat:rw  \
  -v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw  \
  -v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw  \
ubuntu:18.04 /bin/bash

# check /proc/stat
watch "head -n2 /proc/stat"
```
<img width="1788" alt="Screenshot 2021-11-09 at 6 20 24 PM" src="https://user-images.githubusercontent.com/7282697/140915601-f8615b16-0798-42ca-be6f-e94edca48813.png">

- when cfs quota is enabled, the cpu idle time is correct

```bash
# launch a docker container with `--cpuset-cpus 1 --cpu-quota 50000`
docker run --rm -it -m 256m --cpuset-cpus 1 --cpu-quota 50000 \
  -v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
  -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw  \
  -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw  \
  -v /var/lib/lxcfs/proc/stat:/proc/stat:rw  \
  -v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw  \
  -v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw  \
ubuntu:18.04 /bin/bash

# check /proc/stat
watch "head -n2 /proc/stat"
```

<img width="1789" alt="Screenshot 2021-11-09 at 6 19 13 PM" src="https://user-images.githubusercontent.com/7282697/140915892-f9c58980-b9f2-4362-a09f-3997a0d12b3a.png">

### Fix (?)

Check if cfs quota is disabled before revising the cpu time. The idle time looks okay when skipping the revise.

https://github.com/lxc/lxcfs/pull/501

**Comment by brauner** [comment]
Fix merged.
