### ISSUE TITLE
Write to cache was truncated

### ISSUE THREAD

**Issue by axfor** [lxc/lxcfs#503]
Nov 27 15:28:52 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:28:53 xxxnode lxcfs[5618]: proc_fuse.c: 1365: proc_meminfo_read: Write to cache was truncated
Nov 27 15:31:14 xxxnode systemd[1]: lxcfs.service: main process exited, code=killed, status=11/SEGV
Nov 27 15:31:14 xxxnode systemd[1]: Unit lxcfs.service entered failed state.
Nov 27 15:31:14 xxxnode systemd[1]: lxcfs.service failed.

Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated
Nov 27 15:27:08 xxxnode lxcfs[5618]: proc_fuse.c: 1011: proc_stat_read: Write to cache was truncated

kernel: lxcfs[47002]: segfault at 0 ip 00007fbb8559b433 sp 00007fb7ba7fb6c0 error 4

**Comment by mattsm** [comment]
I see these as well

**Comment by mihalicyn** [comment]
Let's close as it's a stale issue and we have no coredump/reproducer.
