### ISSUE TITLE
Changing of cpuset causes value in /proc/stat to be reset

### ISSUE THREAD

**Issue by phanhuy1502** [lxc/lxcfs#513]
### Summary

When `cpuset.cpus` of the container is updated, value under `/proc/stat` is reset according to the new cpuset

### Reproduce

- Start a container and assign cpuset=0

```bash
docker run --rm -it -m 256m --cpuset-cpus 0 -v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw       -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw       -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw       -v /var/lib/lxcfs/proc/stat:/proc/stat:rw       -v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw       -v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw       <image> /bin/bash
```

- Launch some task in the container, observe cpu time under "/proc/stat"

- Update the cpuset.cpus to 1 of a running container:

```bash
echo "1" > /sys/fs/cgroup/cpuset/{container-id}/cpuset.cpus
```

- Observe that cpu time under "/proc/stat" is reset

- See screencast:

[![asciicast](https://asciinema.org/a/459764.svg)](https://asciinema.org/a/459764)

### Solution

I understand this behaviour maybe intentional. Though is it possible to add a runtime flag so that lxcfs will calculate the cpu time base on all cpus, instead of just the cpus assigned to the container? 

Our use case is the cpus assigned to the containers can change during runtime, depending on the resource available. When cpuset is updated, we don't want to value under /proc/stats to change abnormally

**Comment by stgraber** [comment]
I think changing the default to look at all CPUs in the cgroup would be reasonable, moving the container to another CPU shouldn't reduce the total amount of CPU time reported.

@brauner thoughts?

**Comment by phanhuy1502** [comment]
@stgraber @brauner Fix proposed in https://github.com/lxc/lxcfs/pull/515
