### ISSUE TITLE
proc_fuse:get_memlimit(): provide useable info

### ISSUE THREAD

**Issue by jelmd** [lxc/lxcfs#516]
The current error message wrt. get_memlimit() is of very little use, because it does not describe the source of the error, i.e. cgroup name and attr. Something like the following patch is IMHO much better, helpful: 
[lxcfs.txt](https://github.com/lxc/lxcfs/files/8021035/lxcfs.txt)

**Comment by stgraber** [comment]
Want to send this as a PR?

**Comment by jelmd** [comment]
I think copy and paste is much faster ;-)
