### ISSUE TITLE
Override /proc/cmdline?

### ISSUE THREAD

**Issue by RoganDawes** [lxc/lxcfs#517]
Is it possible to override /proc/cmdline using this library?

I'd like to provide arguments to systemd as it boots in the container, but it is my understanding that these need to be provided via grub/bootloader, and that these then show up in /proc/cmdline, from which systemd can then derive its initial configuration, before reading the various config files.

In particular, I am trying to set arguments like:
```
systemd.log_level=debug systemd.log_target=console
```
as per https://freedesktop.org/wiki/Software/systemd/Debugging/

If I have misunderstood the lxc way to pass these arguments, please feel free to point me in the right direction :-) I did search man pages looking for "kernel" and "cmdline", but unsuccessfully.

**Comment by stgraber** [comment]
That feels out of scope for lxcfs. It's something that the container manager itself could do but we haven't seen any reason to do so in LXC or LXD at least as you can just pass those same flags directly to systemd instead.

For example: lxc.init.cmd=/sbin/init systemd.unified_cgroup_hierarchy=0

Or something along those lines (for LXD, this would then be set within a raw.lxc config key).

**Comment by stgraber** [comment]
systemd does directly look at /proc/cmdline for those flags but it also allows the same flags to be passed directly as arguments which is convenient in such cases.

**Comment by RoganDawes** [comment]
Thanks for the explanation.
