### ISSUE TITLE
cgmanager on centos7

### ISSUE THREAD

**Issue by ameyaGit** [lxc/lxcfs#52]
Anyone tried compiling cgmanager on centos7 ?
I compiled it successfully however service fails to start on centos 7 .

**Comment by hallyn** [comment]
> Anyone tried compiling cgmanager on centos7 ?
> I compiled it successfully however service fails to start on centos 7 .

I haven't, sorry.  It should just be a matter of finding and
installing the needed prerequisites.  The configure output
should help.

**Comment by ameyaGit** [comment]
Here is the output 

./configure --prefix=/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-li                                                                                        nux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format.                                                                                        .. func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libr                                                                                        aries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for nih-dbus-tool... /usr/local/bin/nih-dbus-tool
checking for setns... yes
checking for pivot_root... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for NIH... yes
checking for NIH_DBUS... yes
checking for DBUS... yes
checking host distribution... checking for /etc/redhat-release... yes
checking for /etc/oracle-release... no
checking for /etc/centos-release... yes
checking for /etc/fedora-release... no
checking for /etc/SuSE-release... no
checking for /etc/gentoo-release... no
checking for /etc/debian_version... no
checking for /etc/arch-release... no
checking for /etc/slackware-version... no
checking for /etc/frugalware-release... no
checking for /etc/mandrakelinux-release... no
checking for /etc/mandriva-release... no
checking for /etc/pardus-release... no
centos
checking for init system type... sysvinit
checking for help2man... false // No help2man //
checking for pam_authenticate in -lpam... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating config/init/Makefile
config.status: creating config/init/bsd/Makefile
config.status: creating config/init/systemd/Makefile
config.status: creating config/init/sysvinit/Makefile
config.status: creating config/init/upstart/Makefile
config.status: creating config/init/upstart/sessions/Makefile
config.status: creating libcgmanager.pc.in
config.status: creating cgmanager.spec
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by zhanghuanzhong** [comment]
I'm not really sure that why do you try compiling cgmanager on centos7. As you can see  the latest lxcfs picked the cgfs replaces the cgmanager

**Comment by zhanghuanzhong** [comment]
@hallyn I'm not really sure, why do you pick the cfgs rather than the cgmanager.

**Comment by hallyn** [comment]
On Tue, Nov 10, 2015 at 07:58:36PM -0800, anselm wrote:
> @hallyn I'm not really sure, why do you pick the cfgs rather than the cgmanager.

Because it speeds lxcfs (and hence systemd container boots) up 10-20x.

**Comment by ameyaGit** [comment]
compiled cgmanager however this is output for the below command

./lxcfs -s -f -o allow_other /var/lib/lxcfs/

Failed opening dbus connection: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /sys/fs/cgroup/cgmanager/sock: Connection refused
WARNING: failed to escape to root cgroup
Failed opening dbus connection: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /sys/fs/cgroup/cgmanager/sock: Connection refused

**Comment by zhanghuanzhong** [comment]
@ameyaGit  what does  the  `ps  -ef | grep cgmanager` returned?

I think you did not run cgmanager daemon currently.

**Comment by ameyaGit** [comment]
ps -ef | grep cgmanager
root      2859 30936  0 09:00 pts/0    00:00:00 grep --color=auto cgmanager

I did as instructed for compiling cgmanager, here's the output 

service cgmanager start
Starting cgmanager (via systemctl):                        [  OK  ]

**Comment by hallyn** [comment]
@ameyaGit 

Try running

cgmanager -m name=systemd --debug

by hand and see what you get.  Assuming that continues to run, check whether /sys/fs/cgroup/cgmanager/sock then exists.

**Comment by ameyaGit** [comment]
file /sys/fs/cgroup/cgmanager/sock
/sys/fs/cgroup/cgmanager/sock: socket

**Comment by ameyaGit** [comment]
Hi,

cgmanager -m name=systemd --debug gives me the below error on ./lxcfs -s -f -o allow_other /var/lib/lxcfs/

Connection from private client
MovePid: Client fd is: 6 (pid=14697, uid=0, gid=0)
14697 moved to blkio:/ by 14697's request
14697 moved to cpu:/ by 14697's request
14697 moved to cpuset:/ by 14697's request
14697 moved to devices:/ by 14697's request
14697 moved to freezer:/ by 14697's request
14697 moved to hugetlb:/ by 14697's request
14697 moved to memory:/ by 14697's request
14697 moved to net_cls:/ by 14697's request
14697 moved to perf_event:/ by 14697's request
14697 moved to name=systemd:/ by 14697's request
Connection from private client
Disconnected from private client
ListControllers: Client fd is: 7 (pid=14697, uid=0, gid=0)
Disconnected from private client



ps -ef | grep cgmanager
root     14509 13320  0 12:02 pts/1    00:00:00 cgmanager -m name=systemd --debug
root     14809 13343  0 12:30 pts/2    00:00:00 grep --color=auto cgmanager


cgmanager gets killed immediately on start.

**Comment by hallyn** [comment]
Can you run cgmanager in gdb and get a strack trace when it gets killed?

**Comment by ameyaGit** [comment]
Hi,
service cgmanager status gives me the below output
/etc/init.d/cgmanager: line 135: status_of_proc: command not found

**Comment by ameyaGit** [comment]
(gdb) bt
#0  0x00007ffff70728d3 in __select_nocancel () from /lib64/libc.so.6
#1  0x00007ffff79c603a in nih_main_loop () at main.c:581
#2  0x0000000000402b1d in main (argc=2, argv=0x7fffffffe588)
    at cgmanager.c:1583

**Comment by hallyn** [comment]
(lxcfs no longer uses cgmanager at all;  closing this issue;  please work with github.com/lxc/cgmanager if still needed)
