### ISSUE TITLE
Swap not working with cgroup2

### ISSUE THREAD

**Issue by antoinedheygerscrypto** [lxc/lxcfs#534]
When checking swap on container, reports 0.

```swapaccount and cgroup_enable=memory``` are active on grub_cmdline
```/boot/config... ``` show that ```CONFIG_MEMECG_SWAP``` is enabled in the kernel

But here is the result when lauching lxcfs : 
```
Running constructor lxcfs_init to reload liblxcfs
mount namespace: 5
hierarchies:
  0: fd:   6: cpuset,cpu,io,memory,hugetlb,pids,rdma
Kernel supports pidfds
Kernel does not support swap accounting
api_extensions:
- cgroups
- sys_cpu_online
- proc_cpuinfo
- proc_diskstats
- proc_loadavg
- proc_meminfo
- proc_stat
- proc_swaps
- proc_uptime
- shared_pidns
- cpuview_daemon
- loadavg_daemon
- pidfds
```
It tells me that Kernel does not support swap accouting

Is that a problem on LXCFS ?

**Comment by Blub** [comment]
We check for `memory.swap.max` & `memory.swap.current` in the cgroup *root* directory, but those do not exist there.
Maybe we should just have a command line option to override this, as I'm not sure it makes sense to assume specific cgroup directories to exist.
Of course, we *could* just test some well known ones like `systemd.slice` (at least when `-Dinit-script=systemd` was used at build time?)

@brauner, any better ideas?

**Comment by chn-lee-yumi** [comment]
Same problem here.

I am using LXD to run the container. I can control the swap limit through `echo $size > /sys/fs/cgroup/lxc.payload.test2/memory.swap.max`, and read the swap usage through `cat /sys/fs/cgroup/lxc.payload.test2/memory.swap.current`, but the value of swap just doesn't show in the container.

**Comment by chn-lee-yumi** [comment]
Well, I found a comment by @stgraber https://github.com/lxc/lxcfs/issues/551#issuecomment-1215990485, hope it helps.
