### ISSUE TITLE
k8s shareProcessNamespace not supported

### ISSUE THREAD

**Issue by Hellojungle** [lxc/lxcfs#543]
Hello, there are problems when use shareProcessNamespace in k8s. The initpid is pause when using shareProcessNamespace, could we always use the caller's pid to lookup the cgroup hierarchy?

**Comment by silenceper** [comment]
encountered the same problem

**Comment by stgraber** [comment]
I'm pretty sure we can't. We're doing things this way to properly handle containers that have nested cgroups.

That's unlikely to be common place in the k8s world, but in the LXC/LXD world, most containers run systemd which means that most tasks within those containers will belong to a nested cgroup. We want CPU, memory, ... information reported to those processes to match that of the entire container, not just their particular service.
