### ISSUE TITLE
In a busy environment /proc/stat does the impossible and decrements values

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxcfs#554]
This was reported by our friend Phillipe from VPSBenchmarks as he was doing some runs on our LXD VPS instances.

The system he tested this on is:

LXD v5.1
Ubunty Jammy
Linux leeta 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LXCFS version should be whatever ships with LXD 5.1 as this system has had a reboot following upgrade to LXD v5.1

This is the issue as reported by him (edited for clarity in bold)

======

To reproduce the /proc/stat issue, you need to run a cpu intensive task on the container while monitoring /proc/stat with
`while [ true ]; do head -1 /proc/stat >> proc_stat.log; sleep 60; done `

You can also just run `vmstat 60`.

**The container this was run on was on a busy system, 50+ containers performing various workloads** container reports an alarming number of context switches.

After 3 hours on the instance, anomalous readings started being reported. This is the vmstat output:

```
$ vmstat 60
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
38  1      0 8383060      0 362972    0    0   533  1931    1    1  0  0 100  0  0
53  0      0 8379872      0 364328    0    0    79 19361 59518 158456 50  2 48  0  0
44  0      0 8380120      0 364332    0    0    58 18528 59563 121217 51  2 47  0  0
159  1      0 8380084      0 364336    0    0    68 21544 60957 118035 51  2 47  0  0
68  0      0 8379848      0 364336    0    0    96 32579 61261 119957 50  2 48  0  0
90  1      0 8380092      0 364340    0    0   106 27598 62348 129374 51  2 47  0  0
38  1      0 8379956      0 364340    0    0   464 23640 71868 174484  0  0  0  0  0
71  0      0 8380048      0 364344    0    0    60 21478 71283 156429 3431564517 3431564571 157  0  0
86  1      0 8380032      0 364348    0    0   432 22262 76010 169993  0  0  0  0  0
```

and here is proc_stat.log around the same time:

```
cpu   858972 0 20222 5490693976 0 0 0 0 0 0
cpu   888332 0 20928 5490722391 0 0 0 0 0 0
cpu   917797 0 21594 5490750787 0 0 0 0 0 0
cpu   947177 0 22306 5490779307 0 0 0 0 0 0
cpu   976604 0 23045 5490807765 0 0 0 0 0 0
cpu   1006132 0 23805 5490836103 0 0 0 0 0 0
cpu   1389109 0 51003 5477063276 0 0 0 0 0 0
cpu   1418761 0 51601 5477090648 0 0 0 0 0 0
cpu   1448159 0 52263 5477117811 0 0 0 0 0 0
cpu   1477833 0 52734 5477145225 0 0 0 0 0 0
cpu   1507567 0 53220 5477172264 0 0 0 0 0 0
cpu   1537166 0 53839 5477199163 0 0 0 0 0 0
cpu   1566656 0 54352 5477226417 0 0 0 0 0 0
cpu   1321745 0 25054 5499420223 0 0 0 0 0 0
cpu   1351019 0 25511 5499447458 0 0 0 0 0 0
cpu   2177128 0 151672 5503498912 0 0 0 0 0 0
```

As you can see the number of cpu_idle ticks (5th column) suddenly decreased from 5490807765 to 5477063276 before jumping up to 5499420223. At the same time, cpu_system ticks (4th column) jumped up and then down and then up. All those values are cumulative values and should never go down.

**Comment by zrav** [comment]
We are currently experiencing a similar issue. LXD 5.8 on Ubuntu Jammy is causing the number of CPUs reported by /proc/stat in the container to fluctuate, regardless if cpu.limits is set or not. This is causing problems for some applications.

**Comment by mihalicyn** [comment]
@webdock-io please upgrade your LXD snap. It should help.

We can close this, I think.

**Comment by stgraber** [comment]
Indeed, timing wise, this was almost certainly the VFS cache issue.
