### ISSUE TITLE
"CPU views based on quotas" is invalid after 3.1.2( 3.1.2 is ok)

### ISSUE THREAD

**Issue by fjibj** [lxc/lxcfs#556]
Recently, when I upgraded lxcfs to version 5.0.2, I found that when checking the number of CPUs in the container, the number of CPUs of the host was displayed, that is, the "CPU display by quota" function failed. So I checked the version after 3.1.2 and found that this function is invalid.

**Comment by fjibj** [comment]
Recently, when I upgraded lxcfs to version 5.0.2, I found that when checking the number of CPUs in the container, the number of CPUs of the host was displayed, that is, the "CPU display by quota" function failed. So I checked the version after 3.1.2 and found that this function is invalid.

test case: 
`#docker run -dt -m 5g --cpu-period=10000 --cpu-quota=20000  \
-v /sys/fs/cgroup:/sys/fs/cgroup:ro  \
-v /var/lib/lxc/:/var/lib/lxc/:shared \
-v /var/lib/lxc/lxcfs/proc/diskstats:/proc/diskstats:rw,rslave \
-v /var/lib/lxc/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw,rslave \
-v /var/lib/lxc/lxcfs/proc/meminfo:/proc/meminfo:rw,rslave \
-v /var/lib/lxc/lxcfs/proc/stat:/proc/stat:rw,rslave \
-v /var/lib/lxc/lxcfs/proc/swaps:/proc/swaps:rw,rslave \
-v /var/lib/lxc/lxcfs/proc/uptime:/proc/uptime:rw,rslave \
-v /var/lib/lxc/lxcfs/proc/loadavg:/proc/loadavg:rw,rslave \
-v /var/lib/lxc/lxcfs/sys/devices/system/cpu/online:/sys/devices/system/cpu/online:rw,rslave \
centos7-xrdp-systemd:20220628`

in 3.1.2
`# cat /proc/cpuinfo|grep processor|wc -l
2`

in other version, such as 4.0.12, 5.0.2
`# cat /proc/cpuinfo|grep processor|wc -l
4`

so, what happened?

**Comment by suxiaobei1024** [comment]
Looks like also not work on cgroup-v2

**Comment by fjibj** [comment]
I solved it.

from 4.0.0 to 4.0.12， please don't use -l，just
lxcfs /var/lib/lxc/lxcfs/

but after 5.0.0, please add **--enable-cfs**
/usr/bin/lxcfs --enable-cfs -l /var/lib/lxc/lxcfs/
