### ISSUE TITLE
Mount hook fails on sysfs-less containers

### ISSUE THREAD

**Issue by allixx** [lxc/lxcfs#559]
`share/lxcfs/lxc.mount.hook` fails to mount `/sys/devices/system/cpu` when target container doesn't have sysfs mounted, erroring the whole script due to `#/bin/sh -e` shebang, and preventing container start.

I propose making hook script more robust by adding a corresponding check.

https://github.com/allixx/lxcfs/commit/29ef6dce5fd5706d06a46f814ccfe04bde921abb

**Comment by mihalicyn** [comment]
Fixed by @stgraber
