### ISSUE TITLE
Wierd swap info on lxcfs 0.12

### ISSUE THREAD

**Issue by changwuf31** [lxc/lxcfs#56]
Saw this on lxc 1.1.4 or 1.1.5, and lxcfs 0.12 on ubuntu 14.04.

free -m output on lxcfs 0.11:
-----------------------------------
             total       used       free     shared    buffers     cached
Mem:           992        326        666          0          0        155
-/+ buffers/cache:        170        822
Swap:            0          0          0

free -m output on lxcfs 0.12:
-----------------------------------
             total       used       free     shared    buffers     cached
Mem:           992        343        648          0          0        156
-/+ buffers/cache:        187        804
Swap:   17592186043423          0 17592186043423

**Comment by hallyn** [comment]
Hi,

could you show what you get (on the host) for

cat /proc/meminfo

cgm getvalue memory . memory.memsw.limit_in_bytes
cgm getvalue memory . memory.memsw.usage_in_bytes
cgm getvalue memory . memory.usage_in_bytes
cgm getvalue memory . memory.stat

**Comment by changwuf31** [comment]
Sure, here it is:

cat /proc/meminfo
```
MemTotal:        1016340 kB
MemFree:           70732 kB
Buffers:           50588 kB
Cached:           330612 kB
SwapCached:            0 kB
Active:           668304 kB
Inactive:         188404 kB
Active(anon):     475720 kB
Inactive(anon):      912 kB
Active(file):     192584 kB
Inactive(file):   187492 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               176 kB
Writeback:             0 kB
AnonPages:        475508 kB
Mapped:            41824 kB
Shmem:              1124 kB
Slab:              55768 kB
SReclaimable:      38608 kB
SUnreclaim:        17160 kB
KernelStack:        1792 kB
PageTables:         7420 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      965520 kB
Committed_AS:     827796 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       13296 kB
VmallocChunk:   34359694416 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       36864 kB
DirectMap2M:     1142784 kB
```

cgm getvalue memory . memory.memsw.limit_in_bytes
```
18446744073709551615
```

cgm getvalue memory . memory.memsw.usage_in_bytes
```
13123584
```

cgm getvalue memory . memory.usage_in_bytes
```
13148160
```

cgm getvalue memory . memory.stat
```
cache 6053888
rss 6971392
rss_huge 0
mapped_file 61440
writeback 0
swap 0
pgpgin 14480
pgpgout 11300
pgfault 47820
pgmajfault 68
inactive_anon 0
active_anon 6975488
inactive_file 5632000
active_file 417792
unevictable 0
hierarchical_memory_limit 18446744073709551615
hierarchical_memsw_limit 18446744073709551615
total_cache 6053888
total_rss 6971392
total_rss_huge 0
total_mapped_file 61440
total_writeback 0
total_swap 0
total_pgpgin 14480
total_pgpgout 11300
total_pgfault 47820
total_pgmajfault 68
total_inactive_anon 0
total_active_anon 6975488
total_inactive_file 5632000
total_active_file 417792
total_unevictable 0
```

Just let me know if you need anything else

**Comment by hallyn** [comment]
Thanks I can confirm when I enable the swap controller.
