### ISSUE TITLE
Overlap used memory/cpu/uptime etc inside containers

### ISSUE THREAD

**Issue by gribchenko** [lxc/lxcfs#565]
* Distribution:
 Ubuntu 
 * Distribution version:
 20.04.5 LTS
 * The output of "lxc info" or if that fails:
 lxc info ct7839
Name: ct7839
Status: RUNNING
Type: container
Architecture: x86_64
PID: 2404105
Created: 2022/10/25 06:19 EEST
Last Used: 2022/11/03 18:12 EET

Resources:
  Processes: 39
  Disk usage:
    root: 5.40GiB
  CPU usage:
    CPU usage (in seconds): 2
  Memory usage:
    Memory (current): 184.11MiB
    Memory (peak): 186.48MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: veth17b24774
      MAC address: 00:16:3e:4f:f2:29
      MTU: 1500
      Bytes received: 13.33kB
      Bytes sent: 39.75kB
      Packets received: 154
      Packets sent: 319
      IP addresses:
        inet:  *.*.*.248/32 (global)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

   * Kernel version:
    5.4.0-131-generic lxc/lxd#147-Ubuntu
   * LXC version:
   5.7

   * LXD version:
   5.7

   * Storage backend in use:

# Issue description
When run top inside containers

seen flapping info from other containers

top - 18:13:19 up 9 days, 13:49,  0 users,  load average: 0.00, 0.00, 0.00
Tasks:  22 total,   1 running,  21 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.0 sy,  0.0 ni, 99.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  16384.0 total,  15026.1 free,    659.4 used,    698.4 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  15724.6 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
      1 root      20   0  151508  10100   7928 S   0.0   0.1   0:00.26 systemd
     77 root      20   0  187400  31912  31096 S   0.0   0.2   0:00.06 systemd-journal
     99 root      20   0   17192   3156   2860 S   0.0   0.0   0:00.00 cron
    100 message+  20   0    8268   4220   3760 S   0.0   0.0   0:00.01 dbus-daemon
    110 root      20   0 1116604   7264   5648 S   0.0   0.0   0:00.01 hosting-agent
    128 root      20   0  880408  27180  25196 S   0.0   0.2   0:00.04 syslog-ng
    131 root      20   0   13420   5596   4952 S   0.0   0.0   0:00.05 systemd-logind
    139 root      20   0  258860  45900  35568 S   0.0   0.3   0:00.05 /usr/sbin/apach
    140 root      20   0 1048440   6744   4576 S   0.0   0.0   0:00.00 process-slayer
    141 root      20   0   13372   7140   6264 S   0.0   0.0   0:00.00 sshd
    143 root      20   0   15540   2148   2032 S   0.0   0.0   0:00.00 agetty
    153 apache    20   0   57140   7920   4100 S   0.0   0.0   0:00.00 /usr/sbin/apach
    154 apache    20   0   58316   7396   3576 S   0.0   0.0   0:00.00 /usr/sbin/apach
    156 root      20   0   19796   1308      0 S   0.0   0.0   0:00.00 nginx
    157 apache    20   0   24380   7712   2220 S   0.0   0.0   0:00.00 nginx
    180 apache    20   0  259380  19636   9252 S   0.0   0.1   0:00.00 /usr/sbin/apach
    181 apache    20   0  259380  19636   9252 S   0.0   0.1   0:00.00 /usr/sbin/apach
    369 nobody    20   0   29192   2572   1628 S   0.0   0.0   0:00.00 proftpd
    370 mysql     20   0 1802904  76400  22648 S   0.0   0.5   0:00.13 mariadbd
    420 Debian-+  20   0   16884   6376   5304 S   0.0   0.0   0:00.12 exim4
    516 root      20   0   20120   5132   3600 S   0.0   0.0   0:00.01 bash
    519 root      20   0   20108   3768   3224 R   0.0   0.0   0:00.03 top

in  10 sec

top - 18:13:30 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00
Tasks:  22 total,   1 running,  21 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  16384.0 total,  15025.4 free,    660.1 used,    698.5 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  15723.9 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
      1 root      20   0  151508  10100   7928 S   0.0   0.1   0:00.26 systemd
     77 root      20   0  187400  31856  31040 S   0.0   0.2   0:00.06 systemd-journal
     99 root      20   0   17192   3156   2860 S   0.0   0.0   0:00.00 cron
    100 message+  20   0    8268   4216   3756 S   0.0   0.0   0:00.01 dbus-daemon
    110 root      20   0 1116604   7264   5648 S   0.0   0.0   0:00.01 hosting-agent
    128 root      20   0  880408  27176  25192 S   0.0   0.2   0:00.04 syslog-ng
    131 root      20   0   13420   5596   4952 S   0.0   0.0   0:00.05 systemd-logind
    139 root      20   0  258860  45900  35568 S   0.0   0.3   0:00.05 /usr/sbin/apach
    140 root      20   0 1048440   6744   4576 S   0.0   0.0   0:00.00 process-slayer
    141 root      20   0   13372   7140   6264 S   0.0   0.0   0:00.00 sshd
    143 root      20   0   15540   2148   2032 S   0.0   0.0   0:00.00 agetty
    153 apache    20   0   57140   7920   4100 S   0.0   0.0   0:00.00 /usr/sbin/apach
    154 apache    20   0   58316   7396   3576 S   0.0   0.0   0:00.00 /usr/sbin/apach
    156 root      20   0   19796   1308      0 S   0.0   0.0   0:00.00 nginx
    157 apache    20   0   24380   7704   2212 S   0.0   0.0   0:00.00 nginx
    180 apache    20   0  259380  19636   9252 S   0.0   0.1   0:00.00 /usr/sbin/apach
    181 apache    20   0  259380  19636   9252 S   0.0   0.1   0:00.00 /usr/sbin/apach
    369 nobody    20   0   29192   2572   1628 S   0.0   0.0   0:00.00 proftpd
    370 mysql     20   0 1802904  76400  22648 S   0.0   0.5   0:00.13 mariadbd
    420 Debian-+  20   0   16884   6376   5304 S   0.0   0.0   0:00.12 exim4
    516 root      20   0   20120   5132   3600 S   0.0   0.0   0:00.01 bash
    519 root      20   0   20108   3768   3224 R   0.0   0.0   0:00.04 top

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

Config :

 lxc config show ct7839 --expanded
architecture: x86_64
config:
  boot.autostart: "true"
  limits.cpu: "6"
  limits.hugepages.1GB: 4GiB
  limits.hugepages.2MB: 100MiB
  limits.memory: 16GiB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  limits.processes: "800"
  raw.lxc: lxc.cgroup.memory.oom_control=1
  security.idmap.base: "51345450"
  security.idmap.isolated: "true"
  user.fqdn: *1.m*.net
  volatile.cloud-init.instance-id: 3479b700-4ad6-4a3f-a423-650bebca2138
  volatile.eth0.host_name: veth17b24774
  volatile.eth0.hwaddr: 00:16:3e:4f:f2:29
  volatile.idmap.base: "51345450"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":51345450,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":51345450,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":51345450,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":51345450,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":51345450,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":51345450,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 78df104f-44ce-4969-92df-02761d2bbc71
devices:
  eth0:
    ipv4.address: *.*.*.248
    mtu: "1500"
    name: eth0
    nictype: routed
    type: nic
  resolvconf:
    path: /etc/resolv.conf
    readonly: "true"
    source: /etc/resolv.conf
    type: disk
  root:
    limits.read: 2000iops
    limits.write: 1000iops
    path: /
    pool: default
    size: 256GiB
    type: disk
  shared:
    path: /shared
    readonly: "true"
    source: /shared
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by mihalicyn** [comment]
https://github.com/lxc/lxcfs/pull/571
