### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxcfs#58]
Hello, I have test pùt 99 cpu, but failed due to "truncated write to cache", mean if you have 12 core, 24, 36 core, due to size of cpuinfo lxcfs will bug, right?

The patch:

```
> diff -U 3 -H -d -r -N -- lxcfs-master-org/lxcfs.c lxcfs-master/lxcfs.c
> --- lxcfs-master-org/lxcfs.c	2015-12-07 19:08:04.000000000 +0100
> +++ lxcfs-master/lxcfs.c	2015-12-09 07:35:27.673636198 +0100
> @@ -33,6 +33,8 @@
>  #include <sys/mount.h>
>  #include <wait.h>
>  
> +#define FAKECPUCOUNT 99
> +
>  #ifdef FORTRAVIS
>  #define GLIB_DISABLE_DEPRECATION_WARNINGS
>  #include <glib-object.h>
> @@ -2132,12 +2134,17 @@
>  	if (!f)
>  		goto err;
>  
> +    do
> +    {
> +
>  	while (getline(&line, &linelen, f) != -1) {
>  		size_t l;
>  		if (is_processor_line(line)) {
>  			am_printing = cpuline_in_cpuset(line, cpuset);
>  			if (am_printing) {
>  				curcpu ++;
> +                if((curcpu+1)>=FAKECPUCOUNT)
> +                    break;
>  				l = snprintf(cache, cache_size, "processor	: %d\n", curcpu);
>  				if (l < 0) {
>  					perror("Error writing to cache");
> @@ -2186,6 +2193,11 @@
>  			}
>  		}
>  	}
> +	
> +	if(fseek(f,0,SEEK_SET)!=0)
> +        break;
> +    }
> +	while((curcpu+1)<FAKECPUCOUNT);
>  
>  	d->cached = 1;
>  	d->size = total_len;
> 
```

**Comment by hallyn** [comment]
It shouldn't BUG because proc_open() allocates the size of the original /proc/cpuinfo file (plus 256).

If you can reproduce this using lxcfs in a qemu vm (i.e. -cpu 99) please give the qemu args you used so I can reproduce it.

(I at one point tried with some large number and had no problem)

**Comment by alphaonex86** [comment]
Mean: https://github.com/lxc/lxcfs/blob/master/lxcfs.c#L256 ?
Qemu is not afted by this bug, in aemu I can put 99 cpu and 1TB of memory.

**Comment by hallyn** [comment]
On Sat, Dec 12, 2015 at 04:51:51AM -0800, BRULE Herman wrote:
> Mean: https://github.com/lxc/lxcfs/blob/master/lxcfs.c#L256 ?
> Qemu is not afted by this bug, in aemu I can put 99 cpu and 1TB of memory.

(I think we're talking past each other)

Are you saying that if you run lxcfs inside a qemu VM with 99cpus you cannot reproduce this?

I'm looking for a qemu configuration for a VM wherein lxcfs will reproduce the bug you're talking about.

**Comment by alphaonex86** [comment]
I try on real quad core with this patch:
diff -U 3 -H -d -r -N -- lxcfs-master-org/lxcfs.c lxcfs-master/lxcfs.c
--- lxcfs-master-org/lxcfs.c	2015-12-07 19:08:04.000000000 +0100
+++ lxcfs-master/lxcfs.c	2015-12-17 12:51:24.078907017 +0100
@@ -33,6 +33,8 @@
 #include <sys/mount.h>
 #include <wait.h>
 
+#define FAKECPUCOUNT 99
+
 #ifdef FORTRAVIS
 #define GLIB_DISABLE_DEPRECATION_WARNINGS
 #include <glib-object.h>
@@ -253,7 +255,7 @@
 	if (strcmp(querycg, "/") == 0)
 		start =  strdup(taskcg + 1);
 	else
-		start = strdup(taskcg + strlen(querycg) + 1);
+		start = strdup(taskcg + strlen(querycg)*FAKECPUCOUNT + 1);
 	if (!start)
 		return NULL;
 	end = strchr(start, '/');
@@ -2132,12 +2134,17 @@
 	if (!f)
 		goto err;
 
+    do
+    {
+
 	while (getline(&line, &linelen, f) != -1) {
 		size_t l;
 		if (is_processor_line(line)) {
 			am_printing = cpuline_in_cpuset(line, cpuset);
 			if (am_printing) {
 				curcpu ++;
+                if((curcpu+1)>=FAKECPUCOUNT)
+                    break;
 				l = snprintf(cache, cache_size, "processor	: %d\n", curcpu);
 				if (l < 0) {
 					perror("Error writing to cache");
@@ -2186,6 +2193,11 @@
 			}
 		}
 	}
+	
+	if(fseek(f,0,SEEK_SET)!=0)
+        break;
+    }
+	while((curcpu+1)<FAKECPUCOUNT);
 
 	d->cached = 1;
 	d->size = total_len;


And failed with: Internal error: truncated write to cache. No problem under vm with 99 cpu (cpu count <= real cpu count)

**Comment by hallyn** [comment]
If this is still happening please let us know.
