### ISSUE TITLE
lxcfs on /sys/devices/system/cpu

### ISSUE THREAD

**Issue by deemon87** [lxc/lxcfs#585]
# Required information
LXD 5.0.2

# Issue description

After update lxd  5.0.1 -> 5.0.2 inside container (with cpu limit) there is mount point
`lxcfs on /sys/devices/system/cpu/online type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)`, but in `/sys/devices/system/cpu` i see all cpu from hypervisor

Before update was mount point `/sys/devices/system/cpu` and all cpu limits was correct. Now i have some problem with node_exporter (it show me all cpu not only limit), with clickhouse-client (`<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.`)

**Comment by deemon87** [comment]
Yes, `lxcfs.cfs=true` solves the problem with node_exporter but doesn't solve the problem with clickhouse-client
`<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.`
but I think this is a question for the clickhouse developers

**Comment by mihalicyn** [comment]
Hello, Dmitry!

Yep `lxcfs.cfs=true` is only help to workaround buggy software after https://github.com/lxc/lxcfs/commit/4eed66b3026495095c08c2b4b9b2f779ed8f6d06
Speaking about ClickHouse, your problem most probably caused by this change https://github.com/lxc/lxcfs/commit/0a0948b62d9d00729fee8fb17d628b5adab11b09. And again, both these patches are correct. We just need to fix software to properly handle the offlined CPUs.

**Comment by mihalicyn** [comment]
@deemon87 couldn't you clarify something. After upgrading to LXD 5.0.2, have you restarted your clickhouse service or not? I'm just trying to understand why jemalloc decided that CPU index numbers are not stable. :)

**Comment by deemon87** [comment]
@mihalicyn I don't have clickhouse server inside lxc which have this problem (maybe because i haven't restart the service yet). But clickhouse-client which use on-demand became get this message

**Comment by deemon87** [comment]
Oh, interesting. Thank you for help

**Comment by tych0** [comment]
For what it's worth, I have seen incorrect behavior under various allocators (tcmalloc, nodejs/libuv) even with git master lxcfs. Other than the two patches I sent, I couldn't find any difference between what the kernel actually does and what lxcfs does, but those allocators both misbehaved even with my patches applied.

All that is to say: there are definitely allocators that do not handle offlined CPUs well.
