### ISSUE TITLE
when i use lxcfs-5.0.0/5.0.1/5.0.3 docker's cpu limit is not in effect

### ISSUE THREAD

**Issue by use-epoll** [lxc/lxcfs#587]
# Required information 

System: ubuntu20.04
Kernel: 5.4.0-139-generic
Docker: 20.10.12
containerd: 1.5.9 (Controlled by docker)

Installation steps:
1、cd ~/lxcfs-5.0.3
2、meson setup -Dinit-script=systemd --prefix=/usr build/
3、meson install -C build/
4、mkdir /var/lib/lxcfs/
5、/usr/bin/lxcfs  /var/lib/lxcfs

docker run -it -rm --cpus=4 -m 4096m \
-v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
-v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw \
-v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw \
-v /var/lib/lxcfs/proc/stat:/proc/stat:rw \
-v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw \
-v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw \
-v /var/lib/lxcfs/proc/slabinfo:/proc/slabinfo:rw \
-v /var/lib/lxcfs/sys/devices/system/cpu:/sys/devices/system/cpu:rw \
golang:1.19 /bin/bash

golang:1.19 (Debian 11)

# Issue description

Question 1: When I use docker run in lxcfs-5.0.3 environment, the -m parameter limit does limit the memory space in the container, but when I use `-c 4` or `--cpus=4`, the container still shows the full cpu number of the host and does not limit it.

PS: However, when I use `--cpuset-cpus="1,2,3,4"` parameter, the cpu is limited in the container.

Question 2: I am currently using lxcfs-4.0.12 on my kubernetes(1.23.x) cluster (the current cpu and memory limits in k8s are normal), when I use python:3.9 image pyhton can correctly get the number of cpu I limit. However, when I use the golang:1.19 mirror, the `top` command correctly identifies my cpu limit, but golang's `runtime.Numcpu()` still gets the full number of cpus on the host

PS:  But I used docker  `--cpuset-cpus="1,2,3,4"` in lxcfs-5.0.3, I used `runtime.Numcpu()` in golang:1.19 to also get the correct number of cpu after the limit

**Comment by mihalicyn** [comment]
Hi!

`--cpus` and `--cpuset-cpus` are not about limiting cpu set (cores) of the container. Is about weights for cpu sharing in the scheduler.

`--cpuset-cpus` allows you to limit cpu set inside the cgroup

If I understand you correctly, you tried to limit cpu set with `cpuset-cpus` and it works well for Golang's `runtime.Numcpu()` but you don't know how to properly configure the Kubernetes cpu limits to achieve the same result, correct?

Probably you need to take a look on https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy

**Comment by mihalicyn** [comment]
JFYI: `runtime.Numcpu()` uses [sched_getaffinity](https://cs.opensource.google/go/go/+/refs/tags/go1.20.1:src/runtime/os_linux.go;drc=e7cfcda67d430a6e3cf4e8dfef27416870a2b007;bpv=1;bpt=1;l=459)

**Comment by use-epoll** [comment]
Hi! 
When I tried to solve the problem, I found that the application of the application I used in version 4.0.12 was different from the 5.0.3.
So I added parameters used in version 4.0.12 in the 5.0.3 version.
At this time, I used the TOP or CAT /Proc /CPUINFO in the Limit container created in the LXCFS-5.0.3 version.
The start command is as follows:
/usr/local/bin/lxcfs /var/lib/lxcfs/ --enable-cfs -o nonempty -l

But Golang's runtime.numcpu () can still get all the CPUs and memory of the host

Thank you very much for your answer. I know what you said, but it is currently not suitable for the cluster that has been built.
@mihalicyn

**Comment by mihalicyn** [comment]
>But Golang's runtime.numcpu () can still get all the CPUs and memory of the host

yes, and it's not a bug technically. It's a correct behavior. First of all, lxcfs does nothing with `sched_getaffinity`. And your current cgroup parameters are also not affect on the cpu affinity but only on the scheduler weights for the cgroup.

I wonder why it's important for you to limit *number* of CPUs inside PODs? Having CPU time weights configured looks sufficient for most usecases.

**Comment by use-epoll** [comment]
Because some of my business is written in golang.
So if I want to do concurrency I need to adjust GOMAXPROCS.
But every time I have to add a long code to get the data in the cgroup and calculate the relevant parameters to get the real cpu count

**Comment by mihalicyn** [comment]
Catch it. It looks like this was already reported to Golang project https://github.com/golang/go/issues/33803
