### ISSUE TITLE
 The `/proc/diskstats` fields does not match the kernel

### ISSUE THREAD

**Issue by ysysljjyjq** [lxc/lxcfs#589]
I tried successfully isolating `/proc/diskstats` using lxcfs, but the data it shows is wrong with the **wrong number of fields**.

## Environment
OS：Linux 5.3.7-301.fc31.x86_64
lxcfs version：4.0.11
engine：docker

## Steps：
1.  run lxcfs
```bash
mkdir /var/lib/lxcfs
/usr/local/bin/lxcfs /var/lib/lxcfs
```
2. start container
```bash
docker run -it --rm -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw ubuntu /bin/bash
```
3. cat /proc/diskstats
```bash
root@829024bd5696:/# cat /proc/diskstats 
8       0 sda 18 0 1808 0 0 0 0 0 0 0 0 0 0 0
253       0 dm-0 18 0 1808 0 0 0 0 0 0 0 0 0 0 0
```

## Questions:
As mentioned above, after lxcfs isolation, the disk data used by the current container is successfully displayed, and then the number of fields is problematic (**17** fields).
![image](https://user-images.githubusercontent.com/26273331/226111321-7ed51044-3f86-47d5-ab38-69a5f8a12fc1.png)

In the host, cat /proc/diskstats has **18** fields.
![image](https://user-images.githubusercontent.com/26273331/226111340-b472a1ed-61d5-4746-ae21-da5b8c76dce1.png)

Obviously, this phenomenon is unreasonable.

## Reason
When we checked the code, we found that in the `proc_diskstats_read` function of `/src/proc_fuse.c`:
https://github.com/lxc/lxcfs/blob/6a312987219675ed9f5fa1223bc1647858023357/src/proc_fuse.c#L597-L620

Obviously, the code does not take into account the **discard** field, which is originally **located at the 15th position**.
The discard field has not been supplemented in the current version.

## Influence:
For some standard libraries, such as some python libraries for monitoring disk data, only the length of the diskstats field is allowed to be 14, 18, etc. in the code. However, **when the length of the diskstats field is abnormal, such as 17, it cannot be used**.

The original intention of lxcfs isolation is to isolate container and host resources. Here, lxcfs obviously modifies the kernel interface. That is to say, the data format obtained after lxcfs isolation is inconsistent with that of the unisolated (host).
I think it is more appropriate to **add the discard field to 0 than to delete this field directly**.

I wonder why the community considered deleting the `discard` field at that time? Considering compatibility, is it more appropriate to keep the length field of `/proc/diskstats` consistent with the host?

**Comment by stgraber** [comment]
@mihalicyn want to take a look?

**Comment by mihalicyn** [comment]
@ysysljjyjq thanks for your report. Of course it's a bug.

**Comment by ysysljjyjq** [comment]
thanks everyone！
