### ISSUE TITLE
Release date of lxcfs 5.0.4

### ISSUE THREAD

**Issue by peppaJoeng** [lxc/lxcfs#603]
It has been nearly 6 months since the release of 5.0.3. Is there any plan to release 5.0.4 in the near future? @stgraber

**Comment by stgraber** [comment]
Now that LXD is decoupled from LXC and LXCFS, that should be a fair bit easier to do.

**Comment by peppaJoeng** [comment]
lxcfs 5.0.4 has been released, close the issue
