### ISSUE TITLE
Lxcfs On centos7

### ISSUE THREAD

**Issue by ameyaGit** [lxc/lxcfs#61]
Hi,

i can't restrict memory in lxc containers on centos 7, cgmanager and lxcfs are compiled, here is the config of the container

# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Distribution configuration
lxc.include = /usr/share/lxc/config/centos.common.conf
lxc.arch = x86_64
lxc.include = /usr/local/share/lxcfs/lxc.mount.hook
lxc.include = /usr/local/share/lxcfs/lxc.reboot.hook
# Allow for 1024 pseudo terminals
lxc.pts = 1024

# Setup 4 tty devices
lxc.tty = 4

# Drop some harmful capabilities
lxc.cap.drop = mac_admin mac_override sys_time sys_module

# Container specific configuration
lxc.rootfs = /var/lib/lxc/ramCheck/rootfs
lxc.utsname = ramCheck

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0

lxc.cgroup.memory.limit_in_bytes = 536870912
lxc.cgroup.memory.kmem.limit_in_bytes = 536870912
lxc.cgroup.memory.memsw.limit_in_bytes = 1073741824
lxc.cgroup.cpu.cfs_period_us = 100000
lxc.cgroup.cpu.cfs_quota_us = 100000
lxc.cgroup.cpu.shares = 250

# CGroup whitelist
lxc.cgroup.devices.deny = a
## Allow any mknod (but not reading/writing the node)
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
### /dev/null
lxc.cgroup.devices.allow = c 1:3 rwm
### /dev/zero
lxc.cgroup.devices.allow = c 1:5 rwm
### /dev/full
lxc.cgroup.devices.allow = c 1:7 rwm
### /dev/tty
lxc.cgroup.devices.allow = c 5:0 rwm
### /dev/console
lxc.cgroup.devices.allow = c 5:1 rwm
### /dev/ptmx
lxc.cgroup.devices.allow = c 5:2 rwm
### /dev/random
lxc.cgroup.devices.allow = c 1:8 rwm
### /dev/urandom
lxc.cgroup.devices.allow = c 1:9 rwm
### /dev/pts/*
lxc.cgroup.devices.allow = c 136:* rwm
### fuse
lxc.cgroup.devices.allow = c 10:229 rwm

The containers starts fine the restrictions do not work.

**Comment by nehaljwani** [comment]
It worked for me after I added: ``lxc.mount.auto = cgroup:mixed``

**Comment by ameyaGit** [comment]
HI,
@nehaljwani you on centos 7?
can you share the config ? Here's my config after I made the change and it did not work,

# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Distribution configuration
lxc.include = /usr/share/lxc/config/centos.common.conf
lxc.arch = x86_64
lxc.include = /usr/local/share/lxcfs/lxc.mount.hook
lxc.include = /usr/local/share/lxcfs/lxc.reboot.hook
# Allow for 1024 pseudo terminals
lxc.pts = 1024
lxc.mount.auto = cgroup:mixed


# Setup 4 tty devices
lxc.tty = 4

# Drop some harmful capabilities
lxc.cap.drop = mac_admin mac_override sys_time sys_module


# Container specific configuration
lxc.rootfs = /var/lib/lxc/ramCheck/rootfs
lxc.utsname = ramCheck

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0

lxc.cgroup.memory.limit_in_bytes = 536870912
lxc.cgroup.memory.kmem.limit_in_bytes = 536870912
lxc.cgroup.memory.memsw.limit_in_bytes = 1073741824
lxc.cgroup.cpu.cfs_period_us = 100000
lxc.cgroup.cpu.cfs_quota_us = 100000
lxc.cgroup.cpu.shares = 250

# CGroup whitelist
lxc.cgroup.devices.deny = a
## Allow any mknod (but not reading/writing the node)
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
## Allow specific devices
### /dev/null
lxc.cgroup.devices.allow = c 1:3 rwm
### /dev/zero
lxc.cgroup.devices.allow = c 1:5 rwm
### /dev/full
lxc.cgroup.devices.allow = c 1:7 rwm
### /dev/tty
lxc.cgroup.devices.allow = c 5:0 rwm
### /dev/console
lxc.cgroup.devices.allow = c 5:1 rwm
### /dev/ptmx
lxc.cgroup.devices.allow = c 5:2 rwm
### /dev/random
lxc.cgroup.devices.allow = c 1:8 rwm
### /dev/urandom
lxc.cgroup.devices.allow = c 1:9 rwm
### /dev/pts/*
lxc.cgroup.devices.allow = c 136:* rwm
### fuse
lxc.cgroup.devices.allow = c 10:229 rwm

**Comment by ameyaGit** [comment]
Hi,
FYI I have not made any changes to the kernel, is it required ?

**Comment by nehaljwani** [comment]
Yes, in my case, the host is CentOS7 and container is CentOS6. I have not made any modifications to the kernel. I just did the following over the default parameters in a fresh VM running CentOS7-minimal:
1. Compile and install lxcfs:
```bash
cd lxfs
./bootstrap.sh
./configure
make install
```
2. Run lxcfs:
```bash
mkdir -p /usr/local/var/lib/lxcfs/
lxcfs /usr/local/var/lib/lxcfs/
```
3. Create block storage:
```bash
truncate -s 10G ~/lxc_block_storage.img
kpartx -va ~/lxc_block_storage.img
```
4. Create 'lxc' lvm group:
```bash
vgcreate lxc /dev/loop0
```
3. Creat container 'test':
```bash
lxc-create -n test -t centos -B lvm --vgname lxc --fssize=2G --fstype ext4  -- --release=6
```
4. Add the following lines to `/var/lib/lxc/test/config`:
```bash
lxc.mount.auto = cgroup:mixed
lxc.hook.mount = /usr/local/share/lxcfs/lxc.mount.hook
lxc.hook.post-stop = /usr/local/share/lxcfs/lxc.reboot.hook
lxc.cgroup.memory.limit_in_bytes = 256M
lxc.cgroup.memory.memsw.limit_in_bytes = 512M
```

**Comment by ameyaGit** [comment]
Hi,
it worked for me thanks a lot!

official documentation says 
mkdir -p /var/lib/lxcfs
sudo ./lxcfs -s -f -o allow_other /var/lib/lxcfs/

which does not work for centos 7
it shd be 
mkdir -p /usr/local/var/lib/lxcfs/
lxcfs /usr/local/var/lib/lxcfs/

@nehaljwani  can you explain the reason for it ? would be very helpful.
Thanks again.

**Comment by nehaljwani** [comment]
When you compile lxcfs without specifying any `prefix` the following happens:
`$prefix` is set to `/usr/local`
`$localstatedir` is set to `${prefix}/var`, which is equal to `/usr/local/var`
`$LXCFSTARGETDIR` is set to `${localstatedir}/lib/lxcfs`, which is equal to `/usr/local/var/lib/lxcfs`
Now, the file `lxc.mount.hook` is created from `lxcfs/share/lxc.mount.hook.in`, which relies on the the value of `$LXCFSTARGETDIR` for figuring out the lxcfs target directory. Hence, we need to mount lxcfs to the directory which is pointed at by `$LXCFSTARGETDIR`

**Comment by ameyaGit** [comment]
hey,
Thanks a lot for the information.

**Comment by ameyaGit** [comment]
Hi,
I need your help, the method you gave works well , however if I do it manually it does not work,

eg:-  I created lv manually and created a directory named /var/lib/lxc/VPS_NAME
I mounted the lv on /var/lib/lxc/VPS_NAME/rootfs and untar the os and then umount the lv . The config files looks like this


lxc.network.type=veth
lxc.network.link=viifbr0
lxc.network.flags=up
lxc.utsname = 1001
lxc.tty = 4
lxc.pts = 1024
lxc.network.veth.pair = viif1001
#lxc.rootfs = /var/lib/lxc/1001/rootfs
lxc.rootfs = /dev/vg/vs1001-0rlf-at3jjfm8m2c9bf6y
#lxc.mount  = /var/lib/lxc/1001/rootfs/
lxc.autodev = 1
lxc.mount.auto = cgroup:mixed
lxc.hook.mount = /usr/local/share/lxcfs/lxc.mount.hook
lxc.hook.post-stop = /usr/local/share/lxcfs/lxc.reboot.hook

# uncomment the next line to run the container unconfined:
#lxc.aa_profile = unconfined

## Limits
lxc.cgroup.cpu.shares                  = 0
lxc.cgroup.cpuset.cpus                 = 2
lxc.cgroup.memory.limit_in_bytes       = 512M
lxc.cgroup.memory.memsw.limit_in_bytes = 512M

Gives me below error

lxc-start -n 1001
lxc-start: utils.c: open_without_symlink: 1494 No such file or directory - Error examining fs in /usr/lib64/lxc/rootfs/sys/fs/cgroup
lxc-start: cgfs.c: cgroupfs_mount_cgroup: 1371 No such file or directory - could not mount tmpfs to /sys/fs/cgroup in the container
lxc-start: conf.c: lxc_mount_auto_mounts: 838 No such file or directory - error mounting /sys/fs/cgroup
lxc-start: conf.c: lxc_setup: 4178 failed to setup the automatic mounts for '1001'
lxc-start: start.c: do_start: 688 failed to setup the container
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-start: start.c: __lxc_start: 1080 failed to spawn '1001'
lxc-start: lxc_start.c: main: 341 The container failed to start.
lxc-start: lxc_start.c: main: 345 Additional information can be obtained by setting the --logfile and --logpriority options.


I am using lxcfs and cgmanager . Thanks!

**Comment by hallyn** [comment]
is this still an issue for you?

**Comment by ameyaGit** [comment]
Hi,
no, it's fixed.

**Comment by PumpkinSeed** [comment]
Can you explain how can be this fixed for the official Vagrant CentOS 7.x box? This issue is still happening for me.

**Comment by zhanghuanzhong** [comment]
+1
