### ISSUE TITLE
Patch to hide loadaverage

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxcfs#65]
Hello, I'm developping patch to hide the load average, but it loop, do you see why?:
diff -U 3 -H -d -r -N -- lxcfs-master-org/lxcfs.c lxcfs-master/lxcfs.c
--- lxcfs-master-org/lxcfs.c	2015-12-07 19:08:04.000000000 +0100
+++ lxcfs-master/lxcfs.c	2015-12-27 20:50:53.000000000 +0100
@@ -49,6 +49,7 @@
 	LXC_TYPE_PROC_UPTIME,
 	LXC_TYPE_PROC_STAT,
 	LXC_TYPE_PROC_DISKSTATS,
+    LXC_TYPE_PROC_LOADAVG,
 };
 
 struct file_info {
@@ -2791,6 +2842,21 @@
 	return rv;
 }
 
+static int proc_loadavg_read(char *buf, size_t size, off_t offset,
+        struct fuse_file_info *fi)
+{
+    struct file_info *d = (struct file_info *)fi->fh;
+    char *cache = d->buf;
+    size_t cache_size = d->buflen;
+    int total_len = snprintf(d->buf, d->size, "0.01 0.01 0.01 1/99 99");
+    if (total_len < 0){
+        perror("Error writing to cache");
+        return 0;
+    }
+    if (total_len >= cache_size) {
+        fprintf(stderr, "Internal error: truncated write to cache\n");
+        return 0;
+    }
+    cache_size -= total_len;
+    d->cached = 1;
+    d->size = total_len;
+    return total_len;
+}
+
 static off_t get_procfile_size(const char *which)
 {
 	FILE *f = fopen(which, "r");
@@ -2826,7 +2883,8 @@
            strcmp(path, "/proc/cpuinfo") == 0 ||
            strcmp(path, "/proc/uptime") == 0 ||
            strcmp(path, "/proc/stat") == 0 ||
-           strcmp(path, "/proc/diskstats") == 0) {
+           strcmp(path, "/proc/diskstats") == 0 ||
+            strcmp(path, "/proc/loadavg") == 0) {
        sb->st_size = 0;
        sb->st_mode = S_IFREG | 00444;
        sb->st_nlink = 1;
@@ -2843,7 +2909,8 @@
 				filler(buf, "meminfo", NULL, 0) != 0 ||
 				filler(buf, "stat", NULL, 0) != 0 ||
 				filler(buf, "uptime", NULL, 0) != 0 ||
-				filler(buf, "diskstats", NULL, 0) != 0)
+                filler(buf, "diskstats", NULL, 0) != 0 ||
+                filler(buf, "loadavg", NULL, 0) != 0)
 		return -EINVAL;
 	return 0;
 }
@@ -2861,8 +2928,10 @@
 		type = LXC_TYPE_PROC_UPTIME;
 	else if (strcmp(path, "/proc/stat") == 0)
 		type = LXC_TYPE_PROC_STAT;
-	else if (strcmp(path, "/proc/diskstats") == 0)
-		type = LXC_TYPE_PROC_DISKSTATS;
+    else if (strcmp(path, "/proc/diskstats") == 0)
+        type = LXC_TYPE_PROC_DISKSTATS;
+    else if (strcmp(path, "/proc/loadavg") == 0)
+        type = LXC_TYPE_PROC_LOADAVG;
 	if (type == -1)
 		return -ENOENT;
 
@@ -2907,8 +2976,10 @@
 		return proc_uptime_read(buf, size, offset, fi);
 	case LXC_TYPE_PROC_STAT:
 		return proc_stat_read(buf, size, offset, fi);
-	case LXC_TYPE_PROC_DISKSTATS:
-		return proc_diskstats_read(buf, size, offset, fi);
+    case LXC_TYPE_PROC_DISKSTATS:
+        return proc_diskstats_read(buf, size, offset, fi);
+    case LXC_TYPE_PROC_LOADAVG:
+        return proc_loadavg_read(buf, size, offset, fi);
 	default:
 		return -EINVAL;
 	}

**Comment by hallyn** [comment]
On Fri, Jan 08, 2016 at 06:31:18AM -0800, BRULE Herman wrote:
> Hello, I'm developping patch to hide the load average, but it loop, do you see why?:
> diff -U 3 -H -d -r -N -- lxcfs-master-org/lxcfs.c lxcfs-master/lxcfs.c
> --- lxcfs-master-org/lxcfs.c	2015-12-07 19:08:04.000000000 +0100
> +++ lxcfs-master/lxcfs.c	2015-12-27 20:50:53.000000000 +0100
> @@ -49,6 +49,7 @@
>  	LXC_TYPE_PROC_UPTIME,
>  	LXC_TYPE_PROC_STAT,
>  	LXC_TYPE_PROC_DISKSTATS,
> +    LXC_TYPE_PROC_LOADAVG,
>  };
>  
>  struct file_info {
> @@ -2791,6 +2842,21 @@
>  	return rv;
>  }
>  
> +static int proc_loadavg_read(char *buf, size_t size, off_t offset,
> +        struct fuse_file_info *fi)
> +{
> +    struct file_info *d = (struct file_info *)fi->fh;
> +    char *cache = d->buf;
> +    size_t cache_size = d->buflen;

Not seeing why it would loop, though i notice that you don't have a if (offset)
{ } block here for if the data has already been cached

> +    int total_len = snprintf(d->buf, d->size, "0.01 0.01 0.01 1/99 99");
> +    if (total_len < 0){
> +        perror("Error writing to cache");
> +        return 0;
> +    }
> +    if (total_len >= cache_size) {
> +        fprintf(stderr, "Internal error: truncated write to cache\n");
> +        return 0;
> +    }
> +    cache_size -= total_len;
> +    d->cached = 1;
> +    d->size = total_len;
> +    return total_len;

**Comment by alphaonex86** [comment]
static int proc_loadavg_read(char *buf, size_t size, off_t offset,
        struct fuse_file_info *fi)
{
    struct file_info *d = (struct file_info *)fi->fh;
    char *cache = d->buf;
    size_t cache_size = d->buflen;
    if (offset){
        if (offset > d->size)
            return -EINVAL;
        if (!d->cached)
            return 0;
        int left = d->size - offset;
        int total_len = left > size ? size: left;
        memcpy(buf, cache + offset, total_len);
        return total_len;
    }
    int total_len = snprintf(d->buf, d->size, "0.01 0.01 0.01 1/99 99");
    if (total_len < 0){
        perror("Error writing to cache");
        return 0;
    }
    if (total_len >= cache_size) {
        fprintf(stderr, "Internal error: truncated write to cache\n");
        return 0;
    }
    cache_size -= total_len;
    d->cached = 1;
    d->size = total_len;
    return total_len;
}

Not inifinity loop, but remain buggy

**Comment by hallyn** [comment]
On Sat, Jan 09, 2016 at 11:38:12AM -0800, BRULE Herman wrote:
> static int proc_loadavg_read(char *buf, size_t size, off_t offset,
>         struct fuse_file_info *fi)
> {
>     struct file_info *d = (struct file_info *)fi->fh;
>     char *cache = d->buf;
>     size_t cache_size = d->buflen;
>     if (offset){
>         if (offset > d->size)
>             return -EINVAL;
>         if (!d->cached)
>             return 0;
>         int left = d->size - offset;
>         int total_len = left > size ? size: left;
>         memcpy(buf, cache + offset, total_len);
>         return total_len;
>     }
>     int total_len = snprintf(d->buf, d->size, "0.01 0.01 0.01 1/99 99");
>     if (total_len < 0){
>         perror("Error writing to cache");
>         return 0;
>     }
>     if (total_len >= cache_size) {
>         fprintf(stderr, "Internal error: truncated write to cache\n");
>         return 0;
>     }
>     cache_size -= total_len;
>     d->cached = 1;
>     d->size = total_len;
>     return total_len;
> }
> 
> Not inifinity loop, but remain buggy

I'd recommend using proc_uptime_read as an example.  Note you are not copying
the d->buf contents to buf, so the first (non-cached) read() will return
whatever was already in the user-provided buffer.  The whole second half
of the function should probably be rewritten.

**Comment by alphaonex86** [comment]
It what I was, but admit d->buf vs buf it's not clear variable name. Maybe it can be improved
