### ISSUE TITLE
Does not work on debian jessie

### ISSUE THREAD

**Issue by mortzu** [lxc/lxcfs#66]
Have 3 different unprivileged LXC containers. If the container boots for a small period of time the correct memory assignment is visible in free -m and then the total memory of the host is shown.

**Comment by mortzu** [comment]
It occured if I restart a service on the host e.g. ssh or so

**Comment by hallyn** [comment]
On Mon, Jan 11, 2016 at 06:23:53AM -0800, Moritz Kaspar Rudert wrote:
> Have 3 different unprivileged LXC containers. If the container boots for a
> small period of time the correct memory assignment is visible in free -m and
> then the total memory of the host is shown.

Which version of lxcfs are you using?  Commit
a2de34bad72fb1b30af05d2f39a2b7bc6f20e42d "meminfo: fix report swap usage" from
dec 6 fixed some free -m behavior.  This is in 0.16, but not in the 0.13
release.  Depending on where you got the package it may or may not have been
cherrypicked.

**Comment by mortzu** [comment]
Git version. Freshly built yesterday

**Comment by ameyaGit** [comment]
Hi,
This issue can be replicated on centos7.x as well.

**Comment by ameyaGit** [comment]
Hi,
The mount on lxcfs /usr/local/var/lib/lxcfs/  unmounts after ssh service is restarted,

**Comment by mortzu** [comment]
Nope, not at my site

**Comment by ameyaGit** [comment]
how do i put this lxcfs /usr/local/var/lib/lxcfs/ in background coz lxcfs /usr/local/var/lib/lxcfs/ & does not work as umounts when shell is closed

**Comment by mortzu** [comment]
I start it with systemd

**Comment by hallyn** [comment]
On Tue, Jan 12, 2016 at 05:57:47AM -0800, Moritz Kaspar Rudert wrote:
> I start it with systemd

Also when lxcfs crashes you can 'umount -l /usr/local/var/lib/lxcfs'
to release the mount

**Comment by hallyn** [comment]
I haven't tested this on jessie, but see no reason why it should not work at this point, especially as there is even a debian package.  Closing.
