### ISSUE TITLE
init scripts are only in ubuntu package

### ISSUE THREAD

**Issue by smemsh** [lxc/lxcfs#71]
it seems that the init scripts are only in http://github.com/lxc/lxcfs-pkg-ubuntu/ and really they should exist in the upstream package just like they do in cgmanager, for those of us building from source.  looks like just these are needed to bring over:
```
debian/lxcfs.init
debian/lxcfs.service
debian/lxcfs.upstart
```
I don't know if the whole `--with-init-script` stuff needs to be ported over so they can be part of `install` target.

**Comment by hallyn** [comment]
Yes, they should.  Patch to add them would be appreciated.

**Comment by schammy** [comment]
I got burned by this this week, building the 2.0 betas of LXC and LXCFS on Debian 8. Hope this makes it into the final release :) I'm not familiar enough with the code to make a patch unfortunately.

**Comment by smemsh** [comment]
patch looks straightforward, just copy over the style already done for cgmanager.  I'll take a stab if nobody beats me to it, but will not have time for a couple weeks.

**Comment by schammy** [comment]
Thanks @hallyn !

:+1: :+1: :+1: :+1: :+1: :+1: :+1:
