### ISSUE TITLE
lxcfs high(?) cpu usage cost/container

### ISSUE THREAD

**Issue by nick4u** [lxc/lxcfs#82]
Hello.. 
I am using Ubuntu 15.10 at Hyper-V (2CPUs, 4GB RAM) as I wanted to test lxd before switching some of my noncritical www ct's currently running at debian/openvz
I added to my apt sources "with "deb http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu wily main" && update && upgrade && reboot 

_dpkg -l|grep lx[cd]_
ii  liblxc1                            2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (library)
ii  lxc                                2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools
ii  lxc-templates                      2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (templates)
ii  lxcfs                              0.17-0ubuntu3~ubuntu15.10.1~ppa1        amd64        FUSE based filesystem for LXC
ii  lxd                                2.0.0~beta1-0ubuntu4~ubuntu15.10.1~ppa1 amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                         2.0.0~beta1-0ubuntu4~ubuntu15.10.1~ppa1 amd64        Container hypervisor based on LXC - client
ii  python3-lxc                        2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (Python 3.x bindings)

All I did till now is to add some CTs 
_lxc config set storage.zfs_pool_name lxd
lxc remote add images images.linuxcontainers.org
lxc launch images:ubuntu/wily/amd64 ct01
lxc launch images:ubuntu/wily/amd64 ct02_
etc..
I added 10 CTs ... played with it for a while (start,stop,create profile,clone,install mysql at one, postgresql on other) just to learn lxc tool and zfs integration.

Now the **BUG(?)** part..
Thou none of CTs does ~anything now, lxcfs process consumes quite significant portion of CPU per every running CT. With 20CTs running now this is constant 30%(of 200% - 2 CPUs) as htop shows. Munin graph shows flat 30% system,10% user. If I stop half of CTs this is cut by half ... 

This is something to be expected with beta version (debug?) or am I running some strange hyper-v issue?

**Comment by hallyn** [comment]
I've not noticed this, I think this.  Perhaps it is a hyperv issue with fuse itself, or with epoll (which lxcfs uses)?

**Comment by nick4u** [comment]
I think this may be my (hyperv) issue.
I noticed just after posting that downloading with wget _bigfile_ also produces a lot of cpu stress so if lxcfs is communicating via net dev this is probably just my fault. Sorry for taking your time I really thought i have this HV guest set up properly as hv_* modules are loaded  

root@ubuntu:~# lsmod|grep hv
hv_netvsc              36864  0
hv_utils               24576  0
hv_storvsc             24576  2
hv_vmbus               65536  5 hv_netvsc,hid_hyperv,hv_utils,hyperv_fb,hv_storvsc

Close this issue please as I feel shame for bringing this without proper checks :)

**Comment by hallyn** [comment]
Thanks for the update.
