### ISSUE TITLE
libpam-cgfs hangs instead of failing when no cgroupfs tree is mounted

### ISSUE THREAD

**Issue by stgraber** [lxc/lxcfs#86]
We had a few reports (and I had it myself on about 20 containers)  that if libpam-cgfs is installed on a system which doesn't have a cgroupfs tree mounted, it will hang the login session.

Instead I'd expect it to just fail, as its marked optional, PAM will move on and the user will get a working session albeit without configured cgroups (as expected).

**Comment by hallyn** [comment]
Hm, cannot trivially reproduce this:

ubuntu@t1:~$ grep pam_cgfs /etc/pam.d/common-session
session optional        pam_cgfs.so -c freezer,memory,name=systemd
ubuntu@t1:~$ mount | grep cgroup
cgroup on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/cgroup/cgmanager type tmpfs (rw,relatime,size=4k,mode=755)
ubuntu@t1:~$ ssh localhost -l ubuntu
The authenticity of host 'localhost (127.0.0.1)' can't be established.
ECDSA key fingerprint is bd:29:d4:0a:f7:26:73:8a:94:63:8f:27:61:68:4f:c8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
ubuntu@localhost's password:

**Comment by hallyn** [comment]
Never mind, got it.
