### ISSUE TITLE
lxcfs not able to boot with systemd 218 or at least hanging

### ISSUE THREAD

**Issue by brauner** [lxc/lxcfs#9]
I created a privileged `archlinux` container and used @serge's `uidmapshift` tool to convert it to an unprivileged container and moved it from `/var/lib/lxc/arch/` to `~/.local/share/lxc/arch`. I have `lxc 1.1`, `cgmanager 0.35` and `lxcfs 0.5`. `lxcfs` was downloaded from `git` and compiled and installed with 
     
    ./bootstrap.sh
    ./configure
    make
 installed with `sudo make install` to `/usr/local/share/lxcfs`. I then ran it with:

    sudo mkdir -p /usr/local/var/lib/lxcfs
    sudo lxcfs -s -f -o allow_other /usr/local/var/lib/lxcfs/

The permissions for `usr/local/var/lib/lxcfs` are `root:root`; `00-lxcfs.conf` and `lxcfs.mount.hook` are both executable.

The container used the following config file (leaving out the network section):

    # Template used to create this container: /usr/share/lxc/templates/lxc-archlinux
    # Parameters passed to the template:
    # For additional config options, please look at lxc.container.conf(5)

    # Distribution configuration
    lxc.include = /usr/share/lxc/config/archlinux.common.conf
    lxc.include = /usr/share/lxc/config/archlinux.userns.conf
    lxc.include = /usr/local/share/lxc/config/common.conf.d/00-lxcfs.conf
    lxc.arch = x86_64
    lxc.autodev = 1
    lxc.kmsg = 0

    # Container specific configuration
    lxc.id_map = u 0 100000 65536
    lxc.id_map = g 0 100000 65536
    lxc.rootfs = /home/chb/.local/share/lxc/arch/rootfs
    lxc.utsname = arch

When I boot the container it takes a really long time to switch from

    Welcome to Arch Linux!
    Set hostname to <arch>

it then fails to mount the fuse control file system and the huge pages file system:

    [FAILED] Failed to mount FUSE Control File System.
    See "systemctl status sys-fs-fuse-connections.mount" for details.
    [FAILED] Failed to mount Huge Pages File System.
    See "systemctl status dev-hugepages.mount" for details.

It also takes a long time when starting `dbus` and permanently hangs at `Started Permit User Sessions` and never goes any further. If I log into the container with `lxc-attach -n arch` I get a shell.

I tried booting a systemd-based unprivileged `Debian Jessie` container. This works! Although it also takes a long time to boot, hanging at:

    Welcome to Debian Jessie!
    Set hostname to <jessie>

But once it is passed this point it works and I am presented with a login screen and can login. So it seems that `systemd 218` is not working even with `lxcfs` installed. Is there a workaround or am I doing something wrong?

**Comment by brauner** [comment]
Here is a link to the file `unpriv_archlinux_systemd218.txt` containing the `debug` output of the command `sudo lxcfs -d -s -f -o allow_other /usr/local/var/lib/lxcfs/ &>` [unpriv_archlinux_systemd218.txt](https://drive.google.com/file/d/0B_UAut69TSAiOGxZUnhUVVllMXc/view?usp=sharing).

**Comment by brauner** [comment]
Doesn't seem to be `systemd 218` related. I just downloaded an `Ubuntu Vivid` unprivileged container and installed `systemd-sysv` package and booted it again. It works without a problem. So it seems to be specifically `Arch Linux` related.

**Comment by stgraber** [comment]
Note that Ubuntu's systemd 218 does contain upstream patches to systemd to work in unprivileged containers, so does Debian sid.

If Ubuntu systemd booted fine for you, then lxcfs worked properly, any thing else holding up the boot is most likely a distro/systemd/unit issue.
