### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [lxc/lxcfs#93]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/lxc/lxcfs/blob/34b858d21be74e7958a6a8e375be25ac1f4e399b/configure.ac#L32 "Configuration checks")?

**Comment by hallyn** [comment]
Thanks - but not particularly.  Keeping in mind that this is purely linux-only (being fuse), the aix specific notes don't make the extra complication seem worthwhile.  Do you know of specific examples where the current Makefile.am would not suffice?
