### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lxc/lxcfs#96]
Would you like to add more error handling for return values from functions like the following?
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [main](https://github.com/lxc/lxcfs/blob/7c82d95e4241da38d1f19fd90aac2332b8012ff1/lxcfs.c#L883)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [swallow_option](https://github.com/lxc/lxcfs/blob/7c82d95e4241da38d1f19fd90aac2332b8012ff1/lxcfs.c#L699)

**Comment by hallyn** [comment]
On Thu, Mar 17, 2016 at 08:00:33AM -0700, Markus Elfring wrote:
> Would you like to add more error handling for return values from functions like the following?
> - [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [main](https://github.com/lxc/lxcfs/blob/7c82d95e4241da38d1f19fd90aac2332b8012ff1/lxcfs.c#L883)

Thanks, added in my 2016-03-20/misc branch

> - [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [swallow_option](https://github.com/lxc/lxcfs/blob/7c82d95e4241da38d1f19fd90aac2332b8012ff1/lxcfs.c#L699)

nothing to change here.

**Comment by elfring** [comment]
>nothing to change here

Would you like to care also for the potential of a failed memory allocation at this source code place?

**Comment by hallyn** [comment]
On Mon, Mar 21, 2016 at 01:02:45AM -0700, Markus Elfring wrote:
> >nothing to change here
> 
> Would you like to care also for the potential of a failed memory allocation at this source code place?

Maybe we're talking about different pieces of code?  I thought you were
referring to

		do {
			*v = strdup(argv[i+1]);
		} while (!*v);

which will loop until it succeeds (or is killed by oom).

**Comment by elfring** [comment]
* How do you think about to care for a configuration variant which will also work without [an "out-of-memory killer"](http://linux-mm.org/OOM_Killer "Description for the Linux 'oom killer'")?
* Does the loop condition need to be more advanced for "special cases"?

**Comment by hallyn** [comment]
Quoting Markus Elfring (notifications@github.com):
> * How do you think about to care for a configuration variant which will also work without [an "out-of-memory killer"](http://linux-mm.org/OOM_Killer "Description for the Linux 'oom killer'")?

No.  I do not want callers to have to deal with failures.  That adds
complexity and complexity is fragility.  However,

> * Does the loop condition need to be more advanced for "special cases"?

I think there are two things we can do to improve it:

1. throttle failed requests.  Maybe a sleep(1) after each failure?
2. send a message to syslog on each failure.

Patches welcome :)  (else I may do it tomorrow but not today)
